### ISSUE TITLE
Loadout: coin effect %'s still displaying wrong

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#104]
same as #98, doesn't seem like the fix (if there was one) changed anything

**Comment by ramunecarbonated** [comment]
oh yeah, that fix got lost during the rebase. will upload shortly.

**Comment by ramunecarbonated** [comment]
also, please comment on your previous issue next time for these kind of things. (dunno what i said in the past to be honest, but for website related bugs it would help a bit)
