### ISSUE TITLE
Crate #5 having missing Icon

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#105]
![crate5](https://user-images.githubusercontent.com/33488710/33804479-e205bd50-dd9d-11e7-95b1-ebd5e54123f8.png)

**Comment by ramunecarbonated** [comment]
@koopa516 @EgocentricPoliceDick I do not possess the source image, please address.

**Comment by EgocentricPoliceDick** [comment]
I don't have it either, it's up to @koopa516

**Comment by ramunecarbonated** [comment]
Apparantly the FTP uploaded the file @koopa516 uploaded yesterday actually without the .png extension, should be fixed now.
