### ISSUE TITLE
Class Warfare: Player skins don't get removed after switching classes between rounds

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#11]
Example image (taken by Count Sexulus):
![image](https://user-images.githubusercontent.com/33163183/32386065-32032342-c0a7-11e7-982a-355249ccd6f8.png)

Previous round consisted of a team of Pyros.

**Comment by ramunecarbonated** [comment]
I'll fix this before I leave for my party tonight, bit occupied with in the noon so expect a fix in ~2-3 hours.

**Comment by ramunecarbonated** [comment]
Addressed in today's server update. Thanks for reporting!
https://steamcommunity.com/groups/redsunoverparadise#announcements/detail/1452835735000425987
