### ISSUE TITLE
Caravan Palace Premium Music Kit (482) has no icon

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#110]
![image](https://user-images.githubusercontent.com/33851923/33819815-30b0ea20-de01-11e7-9b34-54082f8651cf.png)
![image](https://user-images.githubusercontent.com/33851923/33819857-6d922238-de01-11e7-84cb-00e9ccf43071.png)

**Comment by ramunecarbonated** [comment]
fixed
