### ISSUE TITLE
quality for collector trails in the crafting page showing up as unique instead of collector's

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#111]
(credit to 42 for the pic)

![marble](https://user-images.githubusercontent.com/20176719/33851513-d1cd837a-de7c-11e7-9d51-222540450861.png)

**Comment by FortyTwoFortyTwo** [comment]
Should also mention the X4 trail shows haunted when hovering it
![x4](https://user-images.githubusercontent.com/33488710/33854461-b89cc554-deb9-11e7-82fd-1b7fe6bf38ef.png)
also there quite a bit of Halloween crafting items that shows unique when hovering it

**Comment by woisalreadytaken** [comment]
with 42's comment in mind, here's the rest of the list of incorrect output item qualities in the crafting page: 

- All 3 types of haunted metal will show up as unusual, whether it's a crafting ingredient or the crafting output
![chrome_2017-12-13_04-33-04](https://user-images.githubusercontent.com/33163183/33924904-297550e2-dfbf-11e7-988a-99a153991d92.png)

- Title: I Gave Blood shows up as genuine
![chrome_2017-12-13_04-32-15](https://user-images.githubusercontent.com/33163183/33924949-59614482-dfbf-11e7-9550-583d1e9c3bc6.png)

they're just a visual issue and crafted items will have the quality they're supposed to have (halloween titles will still be haunted, metal will still be unique, etc.), I assume the same happens with collector recipes.

**Comment by ramunecarbonated** [comment]
Fix will be uploaded later today: I have been working on the new christmas event (which will be pretty rad, ignore my trolling on the Discord chat, i am obviously not adding back council of the coins levels of RNG or making you guys do B1 max power to finish the event lol)

As for what is exactly affected: only the tooltip is affected in this bug, output quality did remain consistent with the intended output quality per the crafting recipe, apologies for the inconvinience.
