### ISSUE TITLE
Loadout will always display the "Übers Popped" strange type as "Unknown Strange Type: 0"

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#112]
Servers recognize the übers popped strange type when an item is unboxed, but the Loadout will always display it as "unknown strange type." The counter also never goes up.

edit: thought that the title didn't really match the issue so I renamed it to make it clearer

**Comment by ramunecarbonated** [comment]
Nobody from the management team told me this strange type was added, so I had no way to know this was to be added to the website as "Übercharges: ". Thanks for the report.
