### ISSUE TITLE
long badge names break the quality wrap

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#114]
(dunno proper term)

<img width="378" alt="screen shot 2017-12-12 at 11 11 52 pm" src="https://user-images.githubusercontent.com/20176719/33922706-26366ea2-df92-11e7-8e42-51f95f7685c2.png">

**Comment by ramunecarbonated** [comment]
Thanks for the report, fix will be uploaded shortly.
