### ISSUE TITLE
SZF: scouts still affected by health penalty from the sandman

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#118]
see also: #8 #72 

the issue I mentioned with the sandman in #72 is still present, but the other weapons appear to be fixed

**Comment by ramunecarbonated** [comment]
will be fixed when Snow Sniffer is out.

**Comment by ramunecarbonated** [comment]
This issue is quite complicated to fix, so if it works it works, if not then I will be in for quite a fun ride.

**Comment by itVictor** [comment]
@ramunecarbonated bumping as this isn't fixed/uploaded

**Comment by ramunecarbonated** [comment]
@koopa516 @Benoist3012 
For this issue, the Sandman seems to completely ignore the tf2items overwrite originally added by Benoist, could be that _giveweapon is overwriting/breaking the change.

**Comment by Benoist3012** [comment]
hopefully fixed, bump the issue if it's not

**Comment by itVictor** [comment]
@Benoist3012 there's definitely an improvement, but I don't know if I would consider it fixed because the hp still drains. It's better in the sense in that it goes back to 125 after a while of draining/regaining hp (and then repeats), where as before it would just slowly drain to 110.

in other words it's not staying at 125 all the time, but I don't know if it can be improved beyond what it is right now

**Comment by Benoist3012** [comment]
I think I know why, will fix now.

**Comment by itVictor** [comment]
@Benoist3012 that actually undid the improvement that was happening and now scouts are seeing the original issue I mentioned in the OP

**Comment by Benoist3012** [comment]
I'll do tests this weekend, for now everything I did is based on assumptions.

**Comment by ramunecarbonated** [comment]
aiming to update szf soon with gameplay changes and try to address these.

**Comment by EgocentricPoliceDick** [comment]
SZF updates are being pushed to a development branch which should fix this.
Closing.
