### ISSUE TITLE
Mistral: SZF Plugin slightly broken

### ISSUE THREAD

**Issue by JustABLUToon** [redsunservers/LoadoutBugTracker#119]
As I was playing on Mistral, I noticed a few things: For one, the zombie skins were not loading on the players of the zombie team. Another bug I saw occurring was Zombie players being autobalanced to Survivors mid game. This isn't happening on the other servers, and the rest of the plugin works just fine (special zombies, weapon pickups, etc.)

**Comment by ramunecarbonated** [comment]
addressed, thanks for reporting

**Comment by itVictor** [comment]
@ramunecarbonated bumping because this isn't fixed/uploaded

**Comment by itVictor** [comment]
small update, autobalance bug seems to be gone, but zombie skins are still missing

**Comment by EgocentricPoliceDick** [comment]
I have no idea what is causing this. Oddly enough, the plugins don't seem to be updating for Mistral normally, might be an issue with the buildbot, which @Benoist3012 would need to look into.

**Comment by ramunecarbonated** [comment]
plugins seem to update on Mistral so I will say it is fixed, if it is not a new bug report should be made.
