### ISSUE TITLE
Strange DB Kit not showing counter in chat

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#12]
<img width="293" alt="screen shot 2017-11-03 at 1 37 01 pm" src="https://user-images.githubusercontent.com/20176719/32392271-ee5fba64-c0a2-11e7-89a0-03121852913c.png">

my strange kit did not show the counter in chat at the end of the round, but I do not know why it did not show the counter, I suspect that it's because it tracks round wins (instead of plays) or because it was gifted.

(frosty told me it was supposed to be showing the counter in chat so I'm assuming this is a bug)

**Comment by woisalreadytaken** [comment]
Adding to this, definitely looks like that happens because it counts round wins, as my strange DB Kit was also gifted, but tracks "Round win song played" and always shows the counter in chat.

![image](https://user-images.githubusercontent.com/33163183/32396748-b7911232-c0cd-11e7-860d-bae91c5bacd4.png)

**Comment by ramunecarbonated** [comment]
Both these types are different: Round win song tracks the amount of times your kit played your song, Rounds won simply means how many rounds you won in Dodgeball.

**Comment by ramunecarbonated** [comment]
If this is indeed a bug I will address this, until then I will flag it as wont-fix and close it a few days later.

**Comment by ramunecarbonated** [comment]
Anyway, I addressed the chances on the messages. It will now show off your new count if you got 4 or more kills in the round or when the new number is a number dividable by 10.
https://steamcommunity.com/groups/redsunoverparadise#announcements/detail/1452835735000425987
