### ISSUE TITLE
Self-made Hazardous environment charge overlaps the "Domination" text for the Domination box.  

### ISSUE THREAD

**Issue by bungthebadger** [redsunservers/LoadoutBugTracker#120]
This is most likely due to it being a long name which may apply to other items with a long name as well.

Image: 
 ![darth](https://user-images.githubusercontent.com/34408241/34131679-9559e462-e41a-11e7-80ca-e2fdf2004e8a.PNG)

**Comment by ramunecarbonated** [comment]
low priority, fix will be shipped prolly next loadout update.

**Comment by ramunecarbonated** [comment]
fix will be released in a loadout update for next week.
