### ISSUE TITLE
/unusual does not hide particle effects from first person

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#122]
Despite having first-person view disabled, you can still see the particle effects if you have an unusual skin
![image](https://user-images.githubusercontent.com/33851923/34180651-66fb2b94-e4c4-11e7-8feb-344603f9b72d.png)

**Comment by Benoist3012** [comment]
nobody is supposed to have unusuals yet. This is intended for testings. I'll change that later.

**Comment by EgocentricPoliceDick** [comment]
According to the commit logs for the Loadout repo, this has been implemented. Closing.
