### ISSUE TITLE
Battlecry Replacements overlap UberCharge music and Medic Call replacement overlaps Crafting Materials

### ISSUE THREAD

**Issue by bungthebadger** [redsunservers/LoadoutBugTracker#123]
![overlap](https://user-images.githubusercontent.com/34408241/34182527-a8ff226e-e4e4-11e7-970a-da8de380e9df.PNG)
I do not know if this is a mistake with CSS padding or other CSS elements/formatting or something else of the matter.

**Comment by ramunecarbonated** [comment]
low priority, fix will be shipped prolly next loadout update. for the time being, browse on a higher resolution if possible.

**Comment by ramunecarbonated** [comment]
implemented locally, fix will be supplied with a future loadout update.
