### ISSUE TITLE
Strange types assigned to Collectors items do not track

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#124]
![image](https://user-images.githubusercontent.com/33851923/34184981-c45eb69e-e4d7-11e7-8c63-f8e228b26505.png)

**Comment by bwauts** [comment]
Additionally, the kit is not properly tracking in game
![image](https://user-images.githubusercontent.com/33851923/34194994-3a1576ba-e510-11e7-89c9-1b7683e1a047.png)
As well, the kit on the website still says 0 kills

**Comment by ramunecarbonated** [comment]
bug was due to collector items not having their stranges increase due to the hardcoded condition that it only worked for strange items along with a wrong order of checking kills and showcasing, fix being upload today.
