### ISSUE TITLE
Death: Fox is unable to play because of its sample rate

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#125]
Whenever the sound tries to be played, the console displays this line:

> *** Invalid sample rate (32000) for sound 'redsun\items\death\470.mp3'.

here's a quick fix I made by resampling the sound file to 44100 Hz:
https://cdn.discordapp.com/attachments/332809334339665930/393072035686776841/470_fix.mp3

**Comment by ramunecarbonated** [comment]
community suggested items are so nice

**Comment by ramunecarbonated** [comment]
Fix will be uploaded later tonight.
