### ISSUE TITLE
Non-announcer sounds for Music Kits: Shin Megami Tensei IV, Persona 3, Persona 4 & Persona 4 Arena don't download

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#126]
The announcer sounds for the Persona 3/4 kits download fine, but all other sounds from the new kits (with the exception of Caravan Palace) don't.

**Comment by ramunecarbonated** [comment]
Fix will be uploaded later tonight.

**Comment by woisalreadytaken** [comment]
@ramunecarbonated bumping because the Persona 4 Arena kit doesn't play any sounds still, but all other kits are fine now

**Comment by EgocentricPoliceDick** [comment]
Looks like the item itself wasn't listed within the plugin code. I've since added it and will push the fix.

**Comment by EgocentricPoliceDick** [comment]
fix finally went through, closing again
