### ISSUE TITLE
SZF: Special Zombies that have increased max health don't actually have increased max health

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#127]
(unless it was stealthily changed)

this applies to stalkers so far, I'm assuming it also happens to kingpin and any other zombie that gets higher health than normal. I don't think it happens to the tank but will try to test that.

edit: to clarify they have the stock max health for their respective class

**Comment by ramunecarbonated** [comment]
was intended but i actually forgot to document it

**Comment by ramunecarbonated** [comment]
@koopa516 @Benoist3012 
For this issue, this is an undocumented inconsistensy.

**Comment by Benoist3012** [comment]
what should be do then?

**Comment by ramunecarbonated** [comment]
Remove references in-game where it says that special zombies have more health.

**Comment by itVictor** [comment]
bumping this to say that the tank is also affected, he gets some overheal for killing players and such but his default HP is 300.

**Comment by ramunecarbonated** [comment]
aiming to update szf soon with gameplay changes and try to address these.

**Comment by EgocentricPoliceDick** [comment]
SZF updates are being pushed to a development branch which should fix this.
Closing.
