### ISSUE TITLE
Player requirement for event item drops is not working

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#128]
You can receive items from round win by being alone on a server
![image](https://user-images.githubusercontent.com/33851923/34231703-e853eb22-e591-11e7-9aa4-7554a40d8d93.png)
![image](https://user-images.githubusercontent.com/33851923/34231723-fcd2ce74-e591-11e7-93fc-8ba15cfbe7d5.png)

**Comment by ramunecarbonated** [comment]
fixed, i guess? i can recall adding code for that as well but i did something different now 🤔
