### ISSUE TITLE
turtle attack badges not awarding correctly

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#129]
we beat turtle attack (level 1) on raiden and only one person on red got the badge, I was also on red and didn't get the badge

**Comment by ramunecarbonated** [comment]
@koopa516 implemented the badge so I am gonna throw this at him

**Comment by ramunecarbonated** [comment]
attempting a fix on my side

**Comment by ramunecarbonated** [comment]
should work now as the code check for valid client was not applied correctly, if it isn't feel free to re-open the issue.
