### ISSUE TITLE
PvM maps are broken, because both teams are available for choice.

### ISSUE THREAD

**Issue by SilvaStars** [redsunservers/LoadoutBugTracker#13]
Both team Blu and Red are available in PvM maps like boss_flowey and b1_remake, allowing Blu and Red to kill each other.

**Comment by ramunecarbonated** [comment]
I'll fix this before I leave for my party tonight, bit occupied with in the noon so expect a fix in ~2-3 hours.

**Comment by ramunecarbonated** [comment]
Addressed in today's server update. Thanks for reporting!
https://steamcommunity.com/groups/redsunoverparadise#announcements/detail/1452835735000425987
