### ISSUE TITLE
Collector's Übercharge Music items potentially can only receive the "kills made" strange type

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#131]
All crafted Collector's über music items (and maybe all collector's items crafted overall except music kits?) so far have the kills made strange type, I assume this is not intended and they should receive the Übercharges strange type instead.

**Comment by ramunecarbonated** [comment]
will be shipped in a later loadout update next week

**Comment by ramunecarbonated** [comment]
implemented locally, fix will be supplied with a future loadout update.
