### ISSUE TITLE
Implement the first original strange types in the plugin

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#132]
Music Kits were fixed with issue #124, but other Collector's items never make it past 0 on their strange counters.

Now, this can be an issue with either the Collector's quality or the kills made strange type, as all items have that strange type and I genuinely can't tell what specifically doesn't work.

**Comment by ramunecarbonated** [comment]
strange types that are not db or uber were never coded in at this time

**Comment by ramunecarbonated** [comment]
will be uploaded later
