### ISSUE TITLE
Freeze tag arena round doesn't end despite enemy team being completely frozen

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#137]
![image](https://user-images.githubusercontent.com/33851923/34342685-4758f990-e96c-11e7-9b2d-0c61461d8890.png)

**Comment by EgocentricPoliceDick** [comment]
iirc darth made a change to koth which prevented a full freezeout causing a round win

**Comment by ramunecarbonated** [comment]
this is arena, not koth, don't assign this to me.

**Comment by EgocentricPoliceDick** [comment]
i am saying that the change might not have stuck to koth only

**Comment by ramunecarbonated** [comment]
koth and arena are completely different things in the freezetag config, besides that freezetag is completely stock and we don't seem to have a repo for it.

**Comment by EgocentricPoliceDick** [comment]
we don't? what the fuck i swear we had one
nevermind i'll quickly conjure one up

**Comment by ramunecarbonated** [comment]
Here is the line in question confirming that it is set correctly for Arena.

Closing as no other incidents have been reported since. Comment in case it does happen again.

```
"arena_"
{
	"eliminations"     "1"
```

**Comment by woisalreadytaken** [comment]
@ramunecarbonated the issue is happening because all arena maps in the freeze tag rotation are workshop maps, and the config doesn't seem to support that (we played on a stock arena map and it worked fine, shoutout to blotz for letting me test this)

**Comment by koopa516** [comment]
I'm on it

**Comment by koopa516** [comment]
Fixed
