### ISSUE TITLE
Hex code at end of jukebox

### ISSUE THREAD

**Issue by gunmore2** [redsunservers/LoadoutBugTracker#14]
![image](https://user-images.githubusercontent.com/7016156/32405696-868f1a6c-c140-11e7-948d-49a33c6e84a3.png)
![image](https://user-images.githubusercontent.com/7016156/32405722-056a43a2-c141-11e7-8ab8-0b1b86179a9d.png)
End of jukebox names has the hex code, seems to be every song.

**Comment by ramunecarbonated** [comment]
Thanks, will have it fixed in ~10 minutes.

**Comment by ramunecarbonated** [comment]
Addressed in today's server update. Thanks for reporting!
https://steamcommunity.com/groups/redsunoverparadise#announcements/detail/1452835735000425987
