### ISSUE TITLE
Possible missing functionality: special effect companions no longer comment on someone else's kill/death against the item's owner

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#140]
title gore am i right

When many sound files changed directories to be more organized earlier this year, a bunch of sound-related items broke as a result. Most of them were fixed, but this might have gone unnoticed.

Back then, for example, when a player who had Mini-Merasmus equipped killed another player without it, the player that was killed would hear Merasmus comment on his death, while not owning the item. The same applied when a player without the item killed a player with it equipped.

I believe the way it works now isn't intended because music kit companions still have that feature, and I can't think of a reason why it'd be purposefully removed (plus it'd be a neat way for high-leveled donators to show off their new Tohru companion instead of just hearing it themselves, yeah?)
But if the way it works now happens to be the intended way, feel free to disregard this.

**Comment by EgocentricPoliceDick** [comment]
I'm not sure about this myself. Either it was a legitimate functionality that was removed/broken without documentation, or it was one of these unintended bug-features that was "fixed".

I'll ask about and see what answers I can get.

**Comment by ramunecarbonated** [comment]
- music kits are not intended to play sounds to someone other than the owner of the kit
- companions have this same logic.

so at minimum, it should be made that both the music kit and announcers actually play sounds, along with that announcers probably need to be given their own slot OR trails are taken to their own slot.

@EgocentricPoliceDick @koopa516 what do you think

**Comment by EgocentricPoliceDick** [comment]
I think trails should be allowed their own slot. Music Kit announcers are built-in to the kits in some way, so it'd be fairly convoluted to split them up.

**Comment by ramunecarbonated** [comment]
Will implement trail slot then.

**Comment by ramunecarbonated** [comment]
Implemented.
