### ISSUE TITLE
Loadout: shop preview for Australium Oculus plays a sound that was removed from the item

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#142]
The sound that plays when previewing the item from the shop is for winning a round, it was cut from the item (alongside the sound for losing a round) shortly before the Dodgeball Cup went live. Just in case this somehow becomes misleading to someone in the future.

**Comment by EgocentricPoliceDick** [comment]
The sound is still in the server files, so I've just assumed that it's being used. I'll change the associated sound used for preview.

**Comment by EgocentricPoliceDick** [comment]
Alright, the sound has been changed. Please allow a while for the CDN to recache the fresh file and this should be all fixed.
