### ISSUE TITLE
Ammo bug with the classic in randomizer

### ISSUE THREAD

**Issue by TheStriderr** [redsunservers/LoadoutBugTracker#144]
Game mode: Randomizer

Map: Dustbowl

Bug: As heavy I was able to get 200 ammo with the classic inside randomizer mode.

How it was caused: I shot the classic. After that, my ammo number was flashing as it would if my gun was low on ammo, so I went to my resupply locker to see if that would make it stop. After I resupplied, the classic had 200 ammo, the normal amount of ammo for the Heavy's stock mini gun (Most likely because I was playing as heavy).

Other notes: This bug is probably repeatable with other classes (Most likely Pyro because he has a primary with no reload, just like Heavy). 
I shot the gun 26 times just to be sure that it wasn't just a visual bug.

Screenshots: 
![image](https://user-images.githubusercontent.com/22581649/34428079-1a2f101e-ec17-11e7-98ad-05a6531cdf67.png)

**Comment by Benoist3012** [comment]
Merging this issue with #151
