### ISSUE TITLE
Crafting Genuine Puzzle Box consumes any and all duplicate puzzle pieces you have.

### ISSUE THREAD

**Issue by Waifers** [redsunservers/LoadoutBugTracker#145]
No picture of before since obviously I didn't know this would end up happening.

All my pieces, whether I had atleast 4 of one piece or whatever disappeared when I crafted the puzzle box.

Happened 12/29, ~2:19 CST.

**Comment by Benoist3012** [comment]
Crafting a normal box does exactly the same effect.

**Comment by ramunecarbonated** [comment]
addressed immediatley when it was reported through steam PMs by minicrit ~3.5 days ago
