### ISSUE TITLE
Eating Sandvich in Smash Fortress during Sudden Death.

### ISSUE THREAD

**Issue by xMasterDizzy** [redsunservers/LoadoutBugTracker#146]
GM : Smash Fortress

Issue : Eating Sandvich (Or any healing lunchbox) in a game of Smash Fortress during a Sudden Death round can reduce your percentage like during a regular round, which means you can actually go from 300% to 0%, which, of course, gives you too much of an advantage when you are fighting three opponents that have 300% HP but you do have 10% only.

Possible Fix N°1 : Make the Sandvich cap his healing ability from a limit of 300% to above. You can still heal yourself, but you will not go under 300%.

Possible Fix N°2 : Remove the whole Sandvich healing ability during these rounds. It is the easiest one to develop on, but, as a counterpart, it makes any healing lunchbox useless during Sudden Death.

**Comment by ramunecarbonated** [comment]
will probably go with number 2 and disable heal drops and medkits from being used.

**Comment by ramunecarbonated** [comment]
addressed.
