### ISSUE TITLE
Music Kit: Persona 3 is using Persona 4's death sound

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#147]
this was overlooked when testing a couple of days ago. This is the same issue that the Persona 4 music kit had (it was using P4A's death sound), but that was fixed on the spot.

**Comment by EgocentricPoliceDick** [comment]
Shouldn't take long to fix.

**Comment by EgocentricPoliceDick** [comment]
Fix has been made, will be pushed during next build.
