### ISSUE TITLE
Missing sound previews in the store

### ISSUE THREAD

**Issue by GameBro1** [redsunservers/LoadoutBugTracker#148]
A few items from flower power(2017) and one item that isn't from any events are all missing their sound previews in the store.

These items include:

taunt effects:
	-Sudden celebration
	
Ubercharge music:
	- Your best nightmare

Spray sounds:
	-Zelda puzzle chime

Death effects:
	-My leg!

Respawn effects:
	-Advanced wars 1

**Comment by EgocentricPoliceDick** [comment]
Sudden Celebration uses in-game sounds and particle effects, which don't exactly need a preview. Sound previews are more for custom files.
As for the rest of these items, I'll add previews for them.

**Comment by EgocentricPoliceDick** [comment]
Previews have been added, please allow for some time for the CDN to propagate the new files.
