### ISSUE TITLE
Suggestion: make !trail also apply to spectating

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#149]
currently the !trail command only enables/disables trails for your own trail, I suggest extending the setting so it also applies when spectating other players

**Comment by ramunecarbonated** [comment]
@Benoist3012 @koopa516 
is this even possible or useful to add?

**Comment by koopa516** [comment]
while technically possible it would probably be pretty buggy and incredibly hard to code, I'm afraid this one's gonna have to stay a no unless @Benoist3012 wants to take a crack at it
