### ISSUE TITLE
The Transparent Trousers hide all team colouring from the Vetterlein's Velocity player skin

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#15]
This cosmetic (id 30889) should be added to the item blacklist that the skin already has.

![image](https://user-images.githubusercontent.com/33163183/32406465-f1435fd4-c15f-11e7-992c-cabdccf91b12.png)

**Comment by ramunecarbonated** [comment]
Addressed in today's update, thanks for reporting! http://steamcommunity.com/groups/redsunoverparadise#announcements/detail/1452835735006037811
