### ISSUE TITLE
PropHunt: second-to-last prop receives 2 battle points on death

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#150]
As intended, a player gets a 2 bp bonus when becoming the last prop standing, however, the bp bonus is also given to the player who just died as the second-to-last prop remaining.

**Comment by ramunecarbonated** [comment]
that is a prophunt bug so old that it grew its own grey hairs based on how last player stuff is calculated

**Comment by ramunecarbonated** [comment]
let's see if this works
