### ISSUE TITLE
Randomizer, bunch of bugs

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#151]
-Warrior's Spirit does a shitton of damage (like 23400 i think?)
-All flamethrowers are messed up and only work at point blank range
-Can't charge with demo shields
-Weapon stats are pre-jungle inferno

**Comment by itVictor** [comment]
the issue with flamethrowers affects multiple gamemodes (szf, gungame, etc.) and isn't fixable right now afaik

**Comment by woisalreadytaken** [comment]
flamethrowers in gungame and szf were fixed a while ago

**Comment by koopa516** [comment]
pretty much can't be fixed without re-writing the whole damn plugin

**Comment by koopa516** [comment]
Fixed the flamethrowers, not sure of any way to fix the other issues as of now
