### ISSUE TITLE
Reacts enabled in Reports/Appeals + Staff Applications

### ISSUE THREAD

**Issue by VoidBlitz16** [redsunservers/LoadoutBugTracker#154]
I don't know if this was intended or not, but I know that previously for as long as I've been here reacts were disabled on both sub-forums.

**Comment by EgocentricPoliceDick** [comment]
Seems to be a permissions error. I'll fix this up.

**Comment by itVictor** [comment]
seems like I can still react in report/appeals

**Comment by EgocentricPoliceDick** [comment]
Like I said, it'll take a while to clean it up.
