### ISSUE TITLE
Dodgeball: Dragon's Fury Airblast is not normalized

### ISSUE THREAD

**Issue by VoidBlitz16** [redsunservers/LoadoutBugTracker#155]
**Frosty** told me to put it in here.

Dragon's Fury still has it's original re-compression time, was told could be fixed by applying attribute.

**Comment by ramunecarbonated** [comment]
oops i accidentally assigned frosty

anyway,

it is a static attribute, i can try plastering a item_meter_charge_rate 1.0 over it, cannot guarantee it works.

**Comment by ramunecarbonated** [comment]
addressed, not sure if it will actually work though. post here again if it doesnt work.
