### ISSUE TITLE
Massive spy cloak bug possibly due to vsh rewrite

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#156]
Spy's cloak gives you a ridiculously huge damage resistance (90%), meaning you can tank taunt kills. I'm pretty sure this is because of vsh rewrite but idk. Was happening on raiden, currently happening on armstrong as of writing.

**Comment by CountSexulus** [comment]
also i pm'd beno but he aint been on all day :(

**Comment by Benoist3012** [comment]
Hey hai hayo!
You're rigth it's VSH-Rewrite, `tf_stealth_damage_reduction` I forgot to reset the cvar on plugin end. I'll fix this asap.

**Comment by Benoist3012** [comment]
Alright it's fixed, you should wait a server restart though.
