### ISSUE TITLE
(Smash Bros) Sentries usable in smash

### ISSUE THREAD

**Issue by GeeNoVoid** [redsunservers/LoadoutBugTracker#157]
^Title^
It's probably just a maverick thing but yeah

Here's a demo https://mega.nz/#!iRkFTAZJ!Il1yVkY7KD0K1svU-4iBQvhDA9SNy1pPvmNacgIiwWg

Also the map just in case https://mega.nz/#!GNUBER4J!7m2IgOWXkXurW8Y3X9HIaOutxQ237YD-mZpFe2Rs1IU

**Comment by ramunecarbonated** [comment]
What exactly is the bug being showcased here?

**Comment by EgocentricPoliceDick** [comment]
Haven't engineers always been able to use sentries? If so, what's the bug?

**Comment by GeeNoVoid** [comment]
Right, forgot to mention it was during a melee only special round.

**Comment by ramunecarbonated** [comment]
fixed.
