### ISSUE TITLE
Missing SZF map in Raiden

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#158]
Happened at 8th Jan 19:30 GMT time in Raiden

![missing](https://user-images.githubusercontent.com/33488710/34688666-cff8ddb2-f4aa-11e7-96fb-21bd5d6bb6d6.jpg)

**Comment by EgocentricPoliceDick** [comment]
Seeing as there was no clue in the logs about this, please tell us if it happens again.

**Comment by koopa516** [comment]
szf_4way_jugfix was missing, fixed

**Comment by koopa516** [comment]
nvm it was just szf_4way_v12, thanks 42
