### ISSUE TITLE
"Evangelion 3.0 - Bataille d'Espace" sound file is missing

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#159]
When that song gets selected from a jukebox coin, the console spews these errors:

> MP3 initialized with no sound cache, this may cause janking. [ redsun\box\aeiou\evangelion3.0_batailled'espace.mp3 ]
> Failed to create decoder for MP3 [ redsun\box\aeiou\evangelion3.0_batailled'espace.mp3 ]
> *** Invalid sample rate (0) for sound 'redsun\box\aeiou\evangelion3.0_batailled'espace.mp3'.

(that means it doesn't exist)

I've checked my local files and it's not there, others are having this issue as well. Checked in Raiden and Ocelot

**Comment by ramunecarbonated** [comment]
The sound file exists on both mentioned servers and CDN.

**Comment by ramunecarbonated** [comment]
> 'redsun\box\aeiou\evangelion3.0_batailled'espace.mp3'.

Oh, three quotes, I think removing the quote in the actual song file name will fix this.

**Comment by ramunecarbonated** [comment]
addressed
