### ISSUE TITLE
Contracts: Scream Fortress Round Wins

### ISSUE THREAD

**Issue by GentlemannOfSwing** [redsunservers/LoadoutBugTracker#16]
Scream Fortress round wins seem strange. Others say that they only work on maps that have spell books and hell, Count Spookulus completed his on VSH. It is confirmed that round wins do not work on koth_viaduct_event. I will gather more info on this as I keep playing.

**Comment by koopa516** [comment]
looking into this now

**Comment by ramunecarbonated** [comment]
@koopa516 was this addressed?

**Comment by ramunecarbonated** [comment]
Should be addressed with this server update, thanks for reporting! https://forum.redsun.tf/threads/server-update-november-11th-2017.2385/
