### ISSUE TITLE
Server shop: misplaced trails

### ISSUE THREAD

**Issue by GameBro1** [redsunservers/LoadoutBugTracker#160]
![image](https://user-images.githubusercontent.com/22581649/34740661-2f169d04-f54e-11e7-9bcb-1770932b4997.png)
As you can see here, the trails are inside the other items section instead of the player trails section.

**Comment by EgocentricPoliceDick** [comment]
This will be addressed in a future update. Currently, the code which sorts items by category isn't in there for trails just yet.
