### ISSUE TITLE
Prophunt: Last prop alive does not get beacon or weapons

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#162]
Nor does the music play, and the jarate effect is not given to Blue team. The last man effects (and bp drop) are only granted when the final prop dies.

**Comment by bwauts** [comment]
Badge however still works if one prop is left alive at the end of the round (provided they have no already received the badge)
![image](https://user-images.githubusercontent.com/33851923/34741382-57032718-f537-11e7-8eef-3f6b395d0b64.png)

**Comment by ramunecarbonated** [comment]
I fucking hate prophunt

**Comment by ramunecarbonated** [comment]
will be addressed shortly.
