### ISSUE TITLE
Loadout: Flowey's petal fuckery

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#166]
https://i.gyazo.com/ee24a2dfccffe7b0632270a247b5b986.mp4
searching for "petal" in the loadout brings up nothing when i have the flowey's real petal in my inventory. what's weirder is that searching up "flowey" brings it up as intended.

**Comment by ramunecarbonated** [comment]
Very likely due to the stray quote to designate it is Flowey his petal.

**Comment by ramunecarbonated** [comment]
ready for deploy on next loadout update
