### ISSUE TITLE
SZF: issues with ammo (again)

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#167]
(already reported/known to Benoist, but putting it here for consistency)

1. Getting a kill/assist on a zombie with any rocket launcher/grenade launcher sets your reserve ammo to 2, instead of adding 2 to your current ammo.
2. The Engineer's pistol gets 200 reserve ammo like stock tf2, instead of the normal 60. Picking up ammo boxes is also consistent with normal tf2 (so overall it doesn't drain the reserve ammo to 60 under any circumstance).

Edit 1/10: Flamethrowers are also affected by same issue as pistols (200 ammo)

**Comment by ramunecarbonated** [comment]
aiming to update szf soon with gameplay changes and try to address these.

**Comment by EgocentricPoliceDick** [comment]
SZF updates are being pushed to a development branch which should fix this.
Closing.
