### ISSUE TITLE
The taunt effect items for the Schadenfreude doesn't work on Heavy

### ISSUE THREAD

**Issue by olkyt** [redsunservers/LoadoutBugTracker#168]
While having a taunt effect equipped for the Schadenfreude Heavy doesn't get affected at all and still uses the vanilla sound.
Rest of the classes still work and I have tested this with two items which were Flowey's Curse and The Humiliating Laugh. They both worked on all classes except for Heavy.

**Comment by ramunecarbonated** [comment]
Should be fixed next server upload, didn't notice this was here so sorry for the long wait!
