### ISSUE TITLE
The Stupidifier does not adapt to the class you are disguised as

### ISSUE THREAD

**Issue by JustABLUToon** [redsunservers/LoadoutBugTracker#169]
Title.
Basically, let me set an example:
You're a Spy. Let's say you have the swearing Medic call. When you disguise as, say, an Engineer, you'll have an Engineer's default Medic call. Simple, right?
With the Stupidifier, however, this does not apply. When disguised as any other class and do C+3, it still does the Spy's Stupidifier voice clip. I'm unsure if this is intended or not, but either way it could give a Spy away.

**Comment by koopa516** [comment]
fixed
