### ISSUE TITLE
Dodgeball kits not playing proper audio. 

### ISSUE THREAD

**Issue by GeeNoVoid** [redsunservers/LoadoutBugTracker#17]
Looks like a few of the dodgeball kits aren't working properly, with some audios playing at the wrong time or other audios not playing entirely. More specifically:
-Pendulum Kit not working at all
-Preround audio not playing for some of the deluxe kits (SMW and kirby kit may not be affected by this, might want to check anyways)
-Nuke death audio being played instead of normal death audio for deluxe kits.
-Doom and thriller kits might not be working at all.

**Comment by ramunecarbonated** [comment]
@koopa516 was this addressed?
