### ISSUE TITLE
SZF: Sentry Guns's ammo can be repaired

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#171]
You can repair sentry's ammo (with szf limit) as you would normally smack with your wrench.
You can also upgrade sentry, but upgrading to lvl 2 auto destroys itself anyway.
Don't remember if it intended to also repair sentry's HP, but way well then put it here.

Only affects Raiden, Armstrong and Maverick, Mistral works fine as it should.

**Comment by ramunecarbonated** [comment]
That should not happen, at all, nor upgrading. This is probably due to another plugin influencing the ConVars which allow SZF to do these things.

This needs to be addressed as soon as possible.

**Comment by ramunecarbonated** [comment]
@Benoist3012 please check if vsh-rewrite is not screwing around with these convars:

`tf_obj_upgrade_per_hit`
`tf_sentrygun_metal_per_shell`

**Comment by Benoist3012** [comment]
Nope it doesn't touch these.

**Comment by ramunecarbonated** [comment]
aiming to update szf soon with gameplay changes and try to address these.

**Comment by EgocentricPoliceDick** [comment]
SZF updates are being pushed to a development branch which should fix this. Closing.
