### ISSUE TITLE
VSH Rewrite: Painis spawns corpses on you, despite you not dying.

### ISSUE THREAD

**Issue by VoidBlitz16** [redsunservers/LoadoutBugTracker#172]
So I was playing on the Maverick event Blotz was hosting, and we went up against Painis Cupcake. Despite me not dying, Demoman corpses were spawning on me.

**Comment by Benoist3012** [comment]
That issue, if it's even an issue should have a demo cause without proof I can't agree that it's a real bug.
Ragdolls have a bad habit of spawning at your local pos (on client's end) but are in fact at the rigth place on the server.

**Comment by VoidBlitz16** [comment]
The next time I'm on I'll record a demo, thanks for the info!
