### ISSUE TITLE
AFK manager weirdness

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#173]
![afgaymanager](https://user-images.githubusercontent.com/33283392/35352356-9564090e-013b-11e8-8ef0-5871f2cf53e8.jpg)

as you can see by the image, i am both in red team and in spectator, and i was out of the game for a bit so i assume afk manager put me in spectator and this is how it happened

**Comment by EgocentricPoliceDick** [comment]
I've seen this happen before, so if the afk manager is causing this, then it'd be the plugin author who needs to fix this since we're basically running the stock version now.

**Comment by koopa516** [comment]
no more reports and we updated to a new version, closing
