### ISSUE TITLE
Unable to bulk buy despite having correct BP count

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#175]
![image](https://user-images.githubusercontent.com/33851923/35782532-1e600076-09ae-11e8-80e4-92cd0d5063cf.png)
![image](https://user-images.githubusercontent.com/33851923/35782535-2b9284ee-09ae-11e8-9ffd-21064a95b0e3.png)

**Comment by ramunecarbonated** [comment]
limit of 50
