### ISSUE TITLE
Server List Stuck on Loadout

### ISSUE THREAD

**Issue by Waifers** [redsunservers/LoadoutBugTracker#179]
![788af816ba12e26239f03436109d4b03](https://user-images.githubusercontent.com/34947804/35890325-ee6ec1b4-0b64-11e8-8b8a-0b2abd8d2ad0.png)

List is stuck like this even if ingame the map and player count is clearly different.
Can confirm that another shares this issue who tested that hard reloading and emptying cache doesn't fix it.

**Comment by ramunecarbonated** [comment]
re-deployed webcrons since there were some back end changes to them, prolly were not succesfully uploaded before
