### ISSUE TITLE
"Scream Fortress Kill Contract Mk. II" and Mk. I not working correctly

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#18]
Tried on both mann manor and eyeaduct, no kills would count towards the Mk. II contract. /refreshcontract does nothing. According to Unit, this is also happening with the level 1 scream fortress kills contract as well.

This was on Raiden, it seemed to work on eyeaduct yesterday on Armstrong, as i have 6/50 towards the contract.

**Comment by CountSexulus** [comment]
Update on the issue: 
Scream fortress wins don't work either. Even stranger, if the previous map was a scream fortress/halloween workshop map, the next map will count as a scream fortress/halloween workshop map, meaning the contracts work there. 
For example, if a game of mann manor has finished, and the next map is vsh_crevice, any wins/kills on crevice will count as scream fortress wins and kills.

**Comment by ramunecarbonated** [comment]
Should be addressed with this server update, thanks for reporting! https://forum.redsun.tf/threads/server-update-november-11th-2017.2385/
