### ISSUE TITLE
ph_depot always fail to load PH plugin

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#180]
every time ph_depot is played, PH plugin did not load, this could be because it a workshop map

![20180207165442_1](https://user-images.githubusercontent.com/33488710/35929633-d595bbe8-0c27-11e8-9252-ba0b85518a72.jpg)

**Comment by koopa516** [comment]
fixed

**Comment by EgocentricPoliceDick** [comment]
Right, I think I know what this is.
It's down to the map's configuration file using the exact mapname which causes it to not load in the data required (props allowed, roundtime etc) - the propcunt config should only use the first section of the map name aka ph_name, disregarding anything after and including a second underscore.

I'll correct this for any maps that have this problem and mark this as closed.

**Comment by EgocentricPoliceDick** [comment]
Just this map or...?

**Comment by FortyTwoFortyTwo** [comment]
only this map, ph_depot

**Comment by EgocentricPoliceDick** [comment]
I'm going to take the specific map off of active rotation for now until we know exactly what's wrong.

**Comment by FortyTwoFortyTwo** [comment]
Apparently raiden still have ph_depot in rotation

**Comment by EgocentricPoliceDick** [comment]
map's been gone out of rotation since fuck knows
closed
