### ISSUE TITLE
Loadout: issues with browsing when not signed in

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#182]
**Trying to sign in via Steam from the shop page causes the loadout to be stuck loading for a significant time period**
To reproduce:
1. Go to the loadout and make sure you are signed out
2. Go to the Shop page
3. Try to sign in via Steam
4. Loadout will be stuck loading for a significant period of time, if you try to go back to the homepage you won't be able to load the homepage for a significant time as well

**Viewing a player's profile while signed out doesn't redirect you correctly**
To reproduce:
1. Go to the loadout and make sure you are signed out
2. Go to any profile (eg  https://redsun.tf/player/76561198041374163)
3. Sign in via Steam
4. When it goes back to the loadout, you are redirected to https://redsun.tf/player/ , not the home page or the profile mentioned above

**Comment by EgocentricPoliceDick** [comment]
"Significant time period" seems to only just be for you. I am however getting the redirection to the /player/ route.

As for the loading time, I'll need more users demonstrating this.

**Comment by FortyTwoFortyTwo** [comment]
Can confirm from me when trying to sign in via Steam from shop page stuck me into loading

**Comment by EgocentricPoliceDick** [comment]
And it's only the shop? No other page causing this?

**Comment by infinitephantasm** [comment]
just tested shop login issue, gets stuck waiting for redsun.tf, and as mentioned, won't let me return to the homepage until an undetermined amount of time has passed.

i'll attempt to see if it occurs on other pages when i can log back in

**Comment by VoidBlitz16** [comment]
Can confirm this happens as well.

**Comment by EgocentricPoliceDick** [comment]
and this is _only_ the shop page getting the slowdown? no other pages suffering?

**Comment by FortyTwoFortyTwo** [comment]
only affects shop, equip/inv/crafting redirects you to sign in steam, and loads normal/fast

**Comment by VoidBlitz16** [comment]
Sorry, commented too early.

None of the other pages have this effect when I try logging in.

**Comment by infinitephantasm** [comment]
yeah, not occuring on any other pages for me

**Comment by ramunecarbonated** [comment]
addressed.
