### ISSUE TITLE
Collector's Uber Music: didn't receive a strange part

### ISSUE THREAD

**Issue by ShavedFanatic** [redsunservers/LoadoutBugTracker#183]
[https://i.imgur.com/AnMgYsB.png](url)

Can I get a strange part added to my Collector's please and thank you.

**Comment by EgocentricPoliceDick** [comment]
Could I get the unique Item ID? Open inspect element and hover over the item in question, you should see something like this: 
![image](https://user-images.githubusercontent.com/23524293/36229368-e50c54cc-11ce-11e8-8115-4cc101360a40.png)

**Comment by EgocentricPoliceDick** [comment]
For the record, the problem was hotfixed. I'll close this and await comment from @ShavedFanatic for the requested information so I can rectify any problems.
![image](https://user-images.githubusercontent.com/23524293/36234894-7c47ce1e-11e5-11e8-9184-9d12da14b2bb.png)

**Comment by ShavedFanatic** [comment]
Oh my bad, didn't see the reply till now, here's the ID.

<div class="col inventory-item" id="302494">
