### ISSUE TITLE
koth_variousartists_rc4 missing from fastDL/won't download on raiden

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#185]
![image](https://user-images.githubusercontent.com/23409983/36280290-d17c7b46-1267-11e8-807c-7544393505d1.png)

happened at about 3:49PM EST. map was swapped to something different

**Comment by EgocentricPoliceDick** [comment]
Map was missing from the cdn. I've since added it back.
