### ISSUE TITLE
Badge Collector and Mod Panel overlap

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#186]
![image](https://user-images.githubusercontent.com/33851923/36355986-57c27ef0-14a0-11e8-8de3-a6bd82f6b178.png)

**Comment by EgocentricPoliceDick** [comment]
What is the size of the window you're using? Works fine at 1920x1080.

**Comment by CountSexulus** [comment]
similar thing happens on mobile (2560x1440) https://i.imgur.com/zXVn3kK.png

**Comment by ramunecarbonated** [comment]
cdn related, try to force a refresh with your mobile.
