### ISSUE TITLE
Some/All badges awarded from loadout does not work

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#187]
(thanks to Mr. R for img)

![bp](https://user-images.githubusercontent.com/33488710/36609080-ac12ac2e-18c3-11e8-90d8-c403379168b6.png)

**Comment by EgocentricPoliceDick** [comment]
Nothing in the code suggests this should be happening. You could try logging out, then back in again. See if that does it, as it's calling the coin check function within the website to award the badge.

**Comment by FortyTwoFortyTwo** [comment]
still did not get badge after logging out and back in

**Comment by EgocentricPoliceDick** [comment]
I'll try and look into it, since darth's away this weekend.

**Comment by ramunecarbonated** [comment]
could be that the check that is done is heavily delayed to save resources.

**Comment by ramunecarbonated** [comment]
overwrote the shortcode file, should work now, if it doesn't just comment here-- I will lock this in a day.

**Comment by FortyTwoFortyTwo** [comment]
Still did not get badge, even when logging out and back in again

**Comment by ramunecarbonated** [comment]
i'll investigate further

**Comment by FortyTwoFortyTwo** [comment]
It actually seems to be more of any badges awarded from the loadout that does not work correctly.

Example that some peoples said they have gifted (non BP token) item and still did not get 1 gifts badge.

Another loadout badge is the surf mastery, as one person have completed atleast 10 maps and did not get the 10 surf completes badge.

**Comment by ramunecarbonated** [comment]
assigned higher priority

**Comment by ramunecarbonated** [comment]
addressed https://github.com/EgocentricPoliceDick/redsun-website/commit/f73793e1c487250821331cf97dcf44c16ea17d6b https://github.com/EgocentricPoliceDick/redsun-website/commit/e3728d0e051d7db7c4d7f9357b0fc6832e8cd0b0
