### ISSUE TITLE
Music Kit and Spawn Effect items does not work/appear on loadout slot filter

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#188]
![music](https://user-images.githubusercontent.com/33488710/36645688-96f693bc-1a64-11e8-83bb-6d5dca954dee.png)
![spawn](https://user-images.githubusercontent.com/33488710/36645689-9708ec4c-1a64-11e8-9b19-f3f6b430f1a4.png)

**Comment by EgocentricPoliceDick** [comment]
This issue has been fixed in https://github.com/EgocentricPoliceDick/redsun-website/commit/7fe73a63f5c96f5648b3e9fba63a21c24e723a9b. The issue will be closed and locked.
