### ISSUE TITLE
Forum reactions don't update in real-time.

### ISSUE THREAD

**Issue by VoidBlitz16** [redsunservers/LoadoutBugTracker#189]
![image](https://user-images.githubusercontent.com/35159767/36651133-c5798a5c-1a6c-11e8-94ef-6f1ed3683d65.png)

_To be honest, I'm not even sure if this is anything you guys can do, but I don't know shit about coding, so..._

Anyway, as you can see from the image attached, Forum reactions don't properly update the list of ratings until a page refresh is issued. I think it could be the same deal as issue #187 ?

**Comment by EgocentricPoliceDick** [comment]
Not a bug, this is just the behaviour of the ratings addon.
