### ISSUE TITLE
GunGame:  Flamethrower's flame particles do not move forward

### ISSUE THREAD

**Issue by DaveFlare** [redsunservers/LoadoutBugTracker#19]
All of the flamethrowers you are given have almost no range because the flame particles do not move after being fired.  You can still do damage with the flame particles but you have to be nearly touching the enemy in order for the flames to be able to hit the enemy.

**Comment by ramunecarbonated** [comment]
"Addressed" (Assuming this is a typical "TF2items" thing, we removed Flamethrowers from the rotation) in a server build we will have up in 3 minutes, thanks for your report!

GunGame needs a brush up anyway.
