### ISSUE TITLE
SZF: zombie skins still missing on mistral

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#191]
(see also: #119 )

Title.
Besides that, I didn't see anything glaringly wrong with the plugin itself so I will assume it's just the skins that are broken.

**Comment by EgocentricPoliceDick** [comment]
If this is a duplicate issue, why bother reposting?

**Comment by ramunecarbonated** [comment]
I told him to remake the issue if the bug persists, which it still does, so I will just re-open it and label it the usual things.

Does Mistral even have the skins in the server files? 🤔🤔

**Comment by ramunecarbonated** [comment]
Looked at this before my flight but forgot to post here: skins exist on the server. Suspecting possible convar conflict with redsun_skins plugin.

**Comment by ramunecarbonated** [comment]
attempted to address, seemed to be resetting the properties for BLU team's allowance of Loadout skins back to a parameter which is not the same parameter as used within Raiden / Armstrong.
