### ISSUE TITLE
Forums allow moderation in a certain section(???)

### ISSUE THREAD

**Issue by VoidBlitz16** [redsunservers/LoadoutBugTracker#192]
![screen shot 2018-03-02 at 3 06 43 pm](https://user-images.githubusercontent.com/35159767/36921936-b9d4f552-1e2b-11e8-88b3-10075536c59c.png)

Not sure if same issues happens in Review and Pictures due to lack of post.

I'm not a loser who stalks the forums 24/7 promise.

**Comment by EgocentricPoliceDick** [comment]
Seems like a permissions error. I'll look into it.

**Comment by EgocentricPoliceDick** [comment]
Seems as though someone mischecked a box when initially setting the section up.
Permissions should now be inherited from additional roles (e.g. donator, moderator etc).
