### ISSUE TITLE
Crafting (IMO) completion window is too lengthy

### ISSUE THREAD

**Issue by VoidBlitz16** [redsunservers/LoadoutBugTracker#193]
![image](https://user-images.githubusercontent.com/35159767/36961270-2f010b5a-2010-11e8-863f-0fbea3d70d36.png)

TL;DR lower display timer for crafting completion (please)

**Comment by ramunecarbonated** [comment]
The notification will stay, instead, I will add a differential for crafting notifications, as they are coded the same as the normal notifications I will have to take a bit to do this.

**Comment by EgocentricPoliceDick** [comment]
This issue has been addressed in https://github.com/EgocentricPoliceDick/redsun-website/commit/0c574297de1488d517962ccaac33d3aa2ac2fa1a.

The changes should be live as noted in https://github.com/EgocentricPoliceDick/redsun-website/commit/4a7f5acbfa9f25d14aafed54e246fbca12ecb144, so I will be closing and locking this issue.
