### ISSUE TITLE
"Egocentrick police dick" skin bugged

### ISSUE THREAD

**Issue by tacticturtle123** [redsunservers/LoadoutBugTracker#194]
I've currently only seen this in randomizer at the time of writing, but it seems the new skin for spy seems to be bugged.

the new skin causes the character model to do a t-pose..

and then turn upside down.

not only can you not see any of the viewmodel except the bottom of their feet, it's also really ugly to look at and has been pretty confusing for some people (people trying to shoot my feet, not realising that this issue doesn't effect hitboxes)

the character does not always appear like this though, it only happens at certain times, and probably with certain weapons.

**Comment by EgocentricPoliceDick** [comment]
This is because of Crowbar (modelling tool) causing some hilarity-tier fuckups when rigging models over Spy's model. Nothing anyone can do about it until the tool itself is fixed.

**Comment by EgocentricPoliceDick** [comment]
I'm disabling skins on Randomizer, since that's the biggest culprit at the moment. Anything else is completely out of my control, since it's down to the tools used to make the models, which we can do nothing about.
