### ISSUE TITLE
Add actual donator titles to join/leave messages

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#196]
If a player has a custom donator title, it appears as "(placeholder text)" in join messages. The titles seem to appear normally otherwise. Don't know if it also applies to leave messages.

**Comment by ramunecarbonated** [comment]
christ i did a big whoops

anyway, uh, i will get to this on sunday unless @EgocentricPoliceDick or @koopa516 beat me to it

**Comment by ramunecarbonated** [comment]
should be fixed next server upload.
