### ISSUE TITLE
GunGame:  Skins stay attached to the player

### ISSUE THREAD

**Issue by DaveFlare** [redsunservers/LoadoutBugTracker#20]
If you are given a class with a skin it doesn't get removed when it switches to a different class.  
![skinsbroken](https://user-images.githubusercontent.com/20734136/32623050-c21c5eb2-c539-11e7-81c6-8e914fc4176e.jpg)

**Comment by ramunecarbonated** [comment]
Addressed in a server build we will have up in 3 minutes, thanks for your report!
