### ISSUE TITLE
[EPIC] Add trading requests

### ISSUE THREAD

**Issue by ramunecarbonated** [redsunservers/LoadoutBugTracker#200]
Includes:
- A view to display incoming and outgoing (history of) trades requests.
- A view to create or manage a specific trade request.
- A route to create trades.
- A route to deny trades.
- A route to finalize a trade.
- A cron to check trades and deem them as invalid if they meet the following conditions:
  - One of the items in the trade no longer exists
  - The trade request is older than 3 days.
  - The trader / traded player has any ban on record.
  - The trader / traded player does not have enough Battle Points as they are willing to trade in a trade request.

Differences between gifting:
- Trade multiple items at the same time while being guaranteed to receive that which you are being offered by the other player.
- No fee.
- Players will be encouraged to follow artifically determined values on the virtual items, this does not happen in gifting due to the Battle Point fee

**Comment by Benoist3012** [comment]
Closed since Darth left.
