### ISSUE TITLE
Strange items: Minutes played is displayed as kills in chat

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#201]
i dont have a screencap of it on me at the moment, but basically, the strange counter for minutes played shows up as kills. it still tracks minutes, but it's only a visual thing.

edit: will update when i have a screenshot of it

**Comment by FortyTwoFortyTwo** [comment]
Strange round win items also displays as "kills", i'm assuming it affects all non-dodgeball strange items

![strange1](https://user-images.githubusercontent.com/33488710/37801365-4e65cdd4-2e1e-11e8-96dc-f4af4ff92992.jpg)
![strange2](https://user-images.githubusercontent.com/33488710/37801366-4e7d33d4-2e1e-11e8-8dd4-a8a2665180f9.jpg)

Also, non-dodgeball collectors never appears in chat, e.g. collectors x4 trail with kills tracked

**Comment by EgocentricPoliceDick** [comment]
I've found the code causing this.

**Comment by ramunecarbonated** [comment]
> Also, non-dodgeball collectors never appears in chat, e.g. collectors x4 trail with kills tracked
Intended.
