### ISSUE TITLE
Fart coin sounds not playing properly, causing sound cut offs and even game crashes

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#202]
Upon activation of a fart coin, this got spammed in my console https://i.imgur.com/suGlWtH.png

I was not the only person to get this error either https://i.imgur.com/oNq3xWu.png , https://i.imgur.com/lSVuoQW.png

even after the fart coin ends, the console spam can still happen.  after a while, i got an out of memory error.

edit: i tried deleting all the sound.cache files in the team fortress 2 folder like the szf bug but that didnt seem to do anything

**Comment by EgocentricPoliceDick** [comment]
![image](https://user-images.githubusercontent.com/23524293/37995442-68963b8e-320c-11e8-8339-fa1bb06e6e8a.png)

Given that these are the last changes made to the plugin that handles fart coins, this is a strange occurance.

**Comment by ramunecarbonated** [comment]
bug has been around for quite some time but never got to it since I never remembered it happening, now we got an issue for this

**Comment by Benoist3012** [comment]
Solutions:
- Change all sounds to different path
- Precache the sounds with preload on true (I don't think that will do anything)
- Ask people suffering from this issue to clear their sound.cache (in tf, custom, download ect...)
- Recompile the sound

What we should check:
- Make sure the sounds are on the fastDL
- Make sure the sounds are on the server
- Make sure the sounds are precached at the right place inside the plugin
- Make sure we are not forgetting to precache some sound files
- Make sure clients suffering from this issue have the sound files in their download folder

I'll come back and update this comment to keep you all aware of my progress.

**Comment by ramunecarbonated** [comment]
i got it

**Comment by EgocentricPoliceDick** [comment]
Fixed in https://github.com/EgocentricPoliceDick/Loadout/commit/b37166fe92e634762839009a51d14576d87edd5d and https://github.com/EgocentricPoliceDick/Loadout/commit/3df67429aa64f991006bec83f2d913197d8515cf
