### ISSUE TITLE
Smash: Ledge grab fuckery

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#203]
In Smash Fortress, everyone is able to do ledge grab everytime you jump, and anywhere. Causing everyone able to fly around the map and stays still in air.

Will get screenshot next time if needed.

**Comment by ramunecarbonated** [comment]
if it was a severe bug it would have been reported multiple times, additionally: the ledge grab code is from the Parkour Fortress plugin, so indirectly assigning this to them through @koopa516 if the bug still is there.

**Comment by Benoist3012** [comment]
Bug was still there on april 2nd, it's also not being reported because smash is disabled. It should probably explain why we don't have many bug report about it. But I've witnessed it and can confirm it is definitively happening.

**Comment by Benoist3012** [comment]
As you new ledge grab code is being developed I close this issue.
