### ISSUE TITLE
salvaged #8 crate takes the wrong keys

### ISSUE THREAD

**Issue by MugginsHere** [redsunservers/LoadoutBugTracker#204]
the salvaged #8 crate only takes regular keys, despite the fact that it is a _salvaged crate_. I'm a little salty about the fact I just bought a salvaged key, found out I couldn't use it and now can't afford a regular key

**Comment by ramunecarbonated** [comment]
We will address this internally

**Comment by ramunecarbonated** [comment]
`Salvaged Supply Crate #8: Obligatory Celebrations` now requires the salvaged key from the shop to open instead of the regular key..
