### ISSUE TITLE
Strange kills not counting on pyro skin

### ISSUE THREAD

**Issue by MugginsHere** [redsunservers/LoadoutBugTracker#205]
I unboxed a strange combustible science earlier today that's supposed to track kills, but for some reason isn't. I've got it equipped, I've made multiple non-assist kills as pyro across multiple gamemodes and it just doesn't seem to track anything. This might be another case of description fuckery or me simply being retarted, but the name and description both say that it counts kills so it may be an _actual bug_ this time

**Comment by ramunecarbonated** [comment]
Why is this assigned to website @EgocentricPoliceDick

**Comment by EgocentricPoliceDick** [comment]
@ramunecarbonated it was?
 my bad

**Comment by koopa516** [comment]
fixed strange counts not working on skins in general

**Comment by EgocentricPoliceDick** [comment]
solved in https://github.com/EgocentricPoliceDick/Loadout/commit/fc916d6e6edbc7a672faa88df934d867de0635c6
