### ISSUE TITLE
#8 salvaged crate refusing to open in-game/returns with 'This coin cannot be used right now.'

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#207]
![firefox_2018-04-04_23-22-26](https://user-images.githubusercontent.com/23409983/38345853-676699a8-385f-11e8-8924-dedcff655967.png)
![hl2_2018-04-04_23-22-35](https://user-images.githubusercontent.com/23409983/38345858-6c37cfec-385f-11e8-9b41-7b57d2360f38.png)

the crate dropped, and i set it to action item. refreshed ingame, did /action and was told i didn't have a supply crate key. i bought one (since i didn't have one), refreshed loadout, did /action again and was simply told that the coin couldn't be used right now.

this all happened on maverick. for good measure i retested it on both raiden and armstrong and it still didn't open.

i have both a regular and salvaged key in my inventory. it just seems to refuse to open for whatever reason.

**Comment by infinitephantasm** [comment]
![hl2_2018-04-05_00-44-35](https://user-images.githubusercontent.com/23409983/38347763-6970f368-386b-11e8-98c2-dcce7bb14172.png)

apparently it was able to open like an hour later. unsure if this was just a loadout issue or not but i have my skin, so it's fine now. closing.

**Comment by EgocentricPoliceDick** [comment]
Servers can take a short while to parse your inventory after a refresh. If it didn't appear within 10 seconds, you can try another /refresh.
