### ISSUE TITLE
"Battle Points Needed" notice does not take discounts into consideration

### ISSUE THREAD

**Issue by EgocentricPoliceDick** [redsunservers/LoadoutBugTracker#209]
(on request from @ramunecarbonated I have put this up as a bugtracker issue for transparency.)

Item modals on the shop do not take discounts into consideration. 
![image](https://user-images.githubusercontent.com/23524293/38472392-4b34d4f0-3b77-11e8-86ea-ef1b2352e060.png)
![image](https://user-images.githubusercontent.com/23524293/38472397-6ae7850e-3b77-11e8-8929-c5fb561072ed.png)
As shown here, the Salvaged Key for crate 2 is at a cost of 88 BP. I have set my BP to 87 to highlight this discrepancy, as the notice should denote that only 1 BP is needed, however it is still using the original price to get the figure.

**Comment by ramunecarbonated** [comment]
fixed, will upload in a few
