### ISSUE TITLE
Class Warfare: Cant use CW coins

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#21]
In Class Warfare, when trying to use "Class Mirror Coin", you get a message "This coin cannot be used right now". Someone also cant use his "Melee Only Coin" as well. Haven't tested the "Class Showdown Coin" but i'm assuming same thing goes to it.

Bug happened in Raiden.

**Comment by FortyTwoFortyTwo** [comment]
Just found out you can use CW coin in VSH gamemode (that does nothing and just wastes your coin)

**Comment by ramunecarbonated** [comment]
Addressed in a server build we will have up in 3 minutes, thanks for your report!
