### ISSUE TITLE
badge notifications not going away

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#210]
I recently got "the lucky one" badge, which gave me a popup that I had found it (at it should). However, the popup did not go away at all and I could not go anywhere on the loadout until I refreshed the page.

Obviously I can't reproduce it, so I don't know if it was just a one-time thing or if always happen with that badge/similar popups.

**Comment by ramunecarbonated** [comment]
fix will be up when map manager is done
