### ISSUE TITLE
Featured badge on the Loadout not changeable

### ISSUE THREAD

**Issue by MugginsHere** [redsunservers/LoadoutBugTracker#211]
Whenever you try to change the featured badge on your profile, the badge menu that pops up doesn't actually let you change it. It seems like the menu shows up in the background instead of the foreground, as it's greyed out and clicking on it exits the menu as clicking on the background would. I asked a few others on the server if they were having the same problem and they all reported it affecting them too

**Comment by EgocentricPoliceDick** [comment]
If you could, pictures would be appreciated.

**Comment by MugginsHere** [comment]
![badgebug](https://user-images.githubusercontent.com/37957965/38632908-02bb2bca-3db6-11e8-9d71-1a562317923f.png)

**Comment by ramunecarbonated** [comment]
give cdn like 15 min to update and it should be fixed
thanks for reporting
