### ISSUE TITLE
BP spending badges not being rewarded

### ISSUE THREAD

**Issue by MugginsHere** [redsunservers/LoadoutBugTracker#212]
It seems that the badges rewarded for spending specific amounts of BP in the store aren't being rewarded right now. I noticed this after buying 'the enriched' title and not getting the 1000bp badge. I asked others on the server and they also said that they weren't getting the badges. I'm not sure how long this has been going on for, but there's clearly something up with these badges right now

**Comment by ramunecarbonated** [comment]
fix will be up when map manager is done
