### ISSUE TITLE
Raiden Server Name and Population vanishing from front page.

### ISSUE THREAD

**Issue by GoatPrinceK** [redsunservers/LoadoutBugTracker#214]
Not sure if this is the correct place, but yesterday and part of today, I could not see the Raiden server's name, population, and what map it was currently hosting. I could still click on the link to be sent to the server, though. Might be something on my end or something in the page's end. Still, worth looking into?

**Comment by ramunecarbonated** [comment]
The Loadout should actually take into account when the cronjob polling the servers returns no data, guess I will have to increase the failure / success logic on said process to prevent writing to the server if it is missing anything.

**Comment by EgocentricPoliceDick** [comment]
Could you please elaborate?

**Comment by ramunecarbonated** [comment]
@EgocentricPoliceDick He means the front page that displays the servers in one of the first boxes.

_Sent from my Nokia 8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by GoatPrinceK** [comment]
On the tracker, where the server name would be was simply <>/.

**Comment by EgocentricPoliceDick** [comment]
Ah, right. That's a rare thing which has been around for a while but somehow resolves itself within a few hours

**Comment by ramunecarbonated** [comment]
Hm, yeah, so it returns unexpected data which is not empty, I will consider that also an unexpected change from the library we use. Since the empty check worked fine before. I get back home from Glasgow on Monday, so I will fix that on our development branch which contains other stuff I am working on atm.

**Comment by ramunecarbonated** [comment]
measurements added, will be live on next loadout update
