### ISSUE TITLE
Stop That Tank: Tank Occasionally Doesn't Take Damage

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#215]
Title, on Raiden now, blu couldn't damage our tank and we got a free win. Health got stuck at 76%.
https://i.imgur.com/bLhgj8H.png

edit: to add, the game right after allowed us to damage the tank and we destroyed it

**Comment by Benoist3012** [comment]
I may have an idea on what is happening there. Do you remember the map?

**Comment by CountSexulus** [comment]
no, unfortunately. is there anyway to check map history?

**Comment by Benoist3012** [comment]
Hmm, can you remember if damage were showing for blu despite the health not decreasing.

**Comment by CountSexulus** [comment]
forgot to mention as well, this has happened before, but i didnt report it in the case it was a one off or it was caused by something unrelated (probably event going on at the time), and i have been on the recieving end of this, the damage definitely showed for me. not 100% on if it counted for hp done percentage you see at the end of the round, but the hit numbers/sounds were there

**Comment by Benoist3012** [comment]
just as I suspected now one more question was the train watcher hud broken? Like the cart not moving on the hud?

**Comment by CountSexulus** [comment]
it was still moving iirc

**Comment by infinitephantasm** [comment]
i'm a bit late, but the map in question was pl_humidity_b4 if that helps

**Comment by Benoist3012** [comment]
I think I know what's happening I'm going to decompile that map and verify if my theory is right if not then I'll have to think of something else.

**Comment by FortyTwoFortyTwo** [comment]
Pretty sure it not the map fault, as the bug seems to occur in any maps

**Comment by Benoist3012** [comment]
Just an update on this i've not forgotten about it im just extremely busy right now

**Comment by FortyTwoFortyTwo** [comment]
Well, in the past week or so we seems to have not occur this bug again, no clue or idea on how the bug happened and disappeared. Though it may happen again later, but it definitely did in the past quite a few times.

**Comment by itVictor** [comment]
feels like the bug has been happening in more maps lately...

Given the severity of it would it be too much to ask to remove STT from the active rotation until a fix is found?

**Comment by infinitephantasm** [comment]
+1ing the idea of removing STT from rotation until this is fixed

it's starting to happen at the very start of maps now, when the tank has max HP. there's no real point in stop that tank when you have to just ignore the tank...

**Comment by EgocentricPoliceDick** [comment]
Right, I'm going to be possibly pushing some experimental changes to how the tank registers damage taken in an attempt to fix this.

**Comment by EgocentricPoliceDick** [comment]
Going through old tickets to clear out our backlog.

I haven't heard anything on this, so I'm going to close it, but leave unlocked. Please reopen if still occuring.

**Comment by itVictor** [comment]
just played stt again a few min ago, bug is 100% still occuring

**Comment by CountSexulus** [comment]
https://streamable.com/ucqpe still happening

**Comment by FortyTwoFortyTwo** [comment]
Still not fixed, going to be a long day

**Comment by EgocentricPoliceDick** [comment]
[SCREAMING IN SHOTGUN NOISES]

**Comment by EgocentricPoliceDick** [comment]
okay so after all this time it has probably been found
there's a netprop not properly being set which is somehow forcing the tank into this pseudo-buddha mode

i will post more as it is kicked about like a dead main discord meme

**Comment by EgocentricPoliceDick** [comment]
Haven't seen it about for quite a while, we're assuming it's dead

**Comment by FortyTwoFortyTwo** [comment]
We believe the reason for this bug to happen is because of one Benoist plugin, entity removal. It was meant to be removed long time ago, but we never got around to do it until 23rd feb.
Same day the bug did reappear, but it may be because the plugin actually still loaded until when server restarted.
If bug ever still appeared, make sure to comment here with whatever console debugs printed out during that.

**Comment by infinitephantasm** [comment]
still an issue, it seems
occured on armstrong, on pl_badwater_tilt
```Event_TankHurt_Post | Damage: 6 | Health: 11953
Tank_OnTakeDamage | Damage: 6.50 | Health: 11953
Tank_OnTakeDamageAlive | Damage: 6.50 | Health: 11953
Event_TankHurt | Damage: 6 | Health: 11953
Event_TankHurt_Post | Damage: 6 | Health: 11953
Tank_OnTakeDamage | Damage: 6.50 | Health: 11953
Tank_OnTakeDamageAlive | Damage: 6.50 | Health: 11953
Event_TankHurt | Damage: 6 | Health: 11953
Event_TankHurt_Post | Damage: 6 | Health: 11953
Tank_OnTakeDamage | Damage: 6.50 | Health: 11953
Tank_OnTakeDamageAlive | Damage: 6.50 | Health: 11953
Event_TankHurt | Damage: 6 | Health: 11953
Event_TankHurt_Post | Damage: 6 | Health: 11953
Tank_OnTakeDamage | Damage: 6.50 | Health: 11953
Event_TankHurt | Damage: 6 | Health: 11953
Tank_OnTakeDamageAlive | Damage: 6.50 | Health: 11953
Event_TankHurt_Post | Damage: 6 | Health: 11953
Tank_OnTakeDamage | Damage: 6.50 | Health: 11953
Event_TankHurt | Damage: 6 | Health: 11953
Tank_OnTakeDamageAlive | Damage: 6.50 | Health: 11953
Event_TankHurt_Post | Damage: 6 | Health: 11953
Tank_OnTakeDamageAlive | Damage: 95.22 | Health: 11953
Tank_OnTakeDamage | Damage: 90.00 | Health: 11953
Event_TankHurt | Damage: 95 | Health: 11953
Event_TankHurt_Post | Damage: 95 | Health: 11953

**Comment by EgocentricPoliceDick** [comment]
I'm looking for a debug comment that looks something like this: 
```
================
SETTING TANK TO BUDDHA MODE!!!!
REASON: SET DEFAULT HEALTH FOR TANK RACE
TANK: %d | CLASSNAME: %s
================
```

**Comment by infinitephantasm** [comment]
no such message seems to be in my console.log, all i see are the other debug events. using ctrl+f to check any of the text you mentioned doesn't seem to show either. maybe the debug alert didn't print?

![image](https://user-images.githubusercontent.com/23409983/53676655-726a8580-3c73-11e9-8aaf-7d1758b05338.png)
![image](https://user-images.githubusercontent.com/23409983/53676658-74344900-3c73-11e9-9ae6-a5528d32367c.png)

notepad++ logs of before and after it happened. health persisted all the way until i forcertv'd the map

**Comment by FortyTwoFortyTwo** [comment]
quick test in armstrong same map to see if debug works, it did print out when it suppose to happen/done in the first place, tank deploying the bomb at the end of the map.
```
================
SETTING TANK TO BUDDHA MODE!!!!
REASON: ENTITY DESTROYED
ENTITY: 412 | ENTITY CLASSNAME: func_tracktrain | TANK: 428 | TANK CLASSNAME: tank_boss
================
```
But if the debug did not print out during when hp glitches out, then the buddha command is done somewhere else in one of the many different plugins.
This will be a ride to find and go through each one.

**Comment by FortyTwoFortyTwo** [comment]
I've removed some plugins in raiden & armstrong that may be causing this bug. can't confirm if this is fixed for real, which case you can reopen if still happens (and tell which server it happened).
Server probably need a restart to get plugin actually gone.

**Comment by FortyTwoFortyTwo** [comment]
Of course bug still yet exists.
Time to bring the big guns

**Comment by Zane-Truesdale** [comment]
Might be a good idea to lock STT to special selection until the bug is fixed

**Comment by FortyTwoFortyTwo** [comment]
Yet another update for this, i notice an error threw during STT, which that infact causes console debug unable to print out stuffs, so that is fixed.
See if anything prints out in console when the bug happens this time.

**Comment by FortyTwoFortyTwo** [comment]
```
================
SETTING TANK TO BUDDHA MODE!!!!
REASON: ENTITY DESTROYED
ENTITY: -1 | ENTITY CLASSNAME: INVALID | TANK: 1545 | TANK CLASSNAME: tank_boss
================
```
We've finally found the reason behind it

**Comment by FortyTwoFortyTwo** [comment]
Basically i've made a pull request with a fix and full reason behind it in STT's public repo
https://github.com/akowald/StopThatTank/pull/13

Should be finally fixed for real, if not i'll fucking die.
