### ISSUE TITLE
SZF: If a Boomer is alive when losing a round, explosions won't kill him

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#218]
example: red capped the final point and won the round, a boomer that is alive can now spam medic calls and, as there's no cooldown for jarate bombs, will spam them as well. 

The catch is, bp rewards for bombing 5+ survivors are still active, and these can also be spammed.

**Comment by ramunecarbonated** [comment]
fixed, thanks.
