### ISSUE TITLE
SZF: can't pick up tide turner

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#220]
Same bug that was reported in playtesting but doesn't seem like it was ever fixed. If it's not going to be fixed at all it should at least be removed from the weapon pool.

**Comment by ramunecarbonated** [comment]
will remove tomorrow

**Comment by FortyTwoFortyTwo** [comment]
Same issue to splendid screen, could not be picked up

**Comment by EgocentricPoliceDick** [comment]
I'll close this as while the issue can't be fixed, it can be mitigated.

**Comment by EgocentricPoliceDick** [comment]
Mitigated in https://github.com/EgocentricPoliceDick/SZF-private/commit/ffa0909e802b9b4f95b3aaf81fa5086a2fb20e24
