### ISSUE TITLE
'Our Hunters are Blind' badge - broken?

### ISSUE THREAD

**Issue by haxtonsale** [redsunservers/LoadoutBugTracker#223]
We won a game of prophunt with 9 props surviving and didn't get the 'Our Hunters are Blind' badge 😡
https://i.imgur.com/5Uzj5PZ.jpg

**Comment by koopa516** [comment]
Not fixed

**Comment by Benoist3012** [comment]
Fix it?

**Comment by EgocentricPoliceDick** [comment]
Going through old tickets to clear out our backlog.

I haven't heard anything on this, so I'm going to close it, but leave unlocked. Please reopen if still occuring.
