### ISSUE TITLE
Crate #5 has a chance give out Strange Battlecry: Doctor Eggman

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#224]
It's been like this for a while, I'm not sure how it's set up but I believe this battle cry is replacing what should be a Strange Übercharge Music: Robotnik, as I've not seen any of these drop from the crate so far. The battlecry will always come with the ubers popped strange type (which won't work) and can't drop in unique/normal quality.

**Comment by ramunecarbonated** [comment]
fixed, thanks for reporting.

**Comment by ramunecarbonated** [comment]
(will take like 15-30 min to update)
