### ISSUE TITLE
outdated info for "Donator Rank on our Discord Server" reward

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#228]
<img width="453" alt="screen shot 2018-05-17 at 6 56 33 pm" src="https://user-images.githubusercontent.com/20176719/40209340-3081e9f8-5a04-11e8-9a92-1bc6268cdd83.png">

This is outdated because that channel no longer exists and getting the donator role on discord is done by linking your discord account with your forum/loadout account.

**Comment by EgocentricPoliceDick** [comment]
Fixed in https://github.com/EgocentricPoliceDick/redsun-website/commit/67136a14fe99064ef0ed3e40e916469c9e671cfc
