### ISSUE TITLE
[Suggestion] Yes/No/Thanks items to use equipped item variants?

### ISSUE THREAD

**Issue by scoottehbesht** [redsunservers/LoadoutBugTracker#229]
Posting this here as requested by Darthmule:

As of typing this, using the Shared Thanks or Yes/No chat items trigger the line replacements a player has equipped (ie. Player with No: Robotnik says "no" in chat, player with No: Geoffrey hears Geoffrey.) If this suggestion were to be accepted, players would now hear the audio of the item the person typing has equipped regardless of what they have equipped (ie. Player with Thanks: Okay says "thanks", everyone hears the DK line.)

**Comment by ramunecarbonated** [comment]
removed bug label

i got an idea how to do this but i prefer to spend doing so this weekend, got weekend off anyway,

**Comment by ramunecarbonated** [comment]
So I looked into this, and I cannot figure out for my life something to pull this off that doesnt require me to rewrite the saysound function or generate spaghetti without tomato sauce.

So instead, I made it that Yes / No / Thanks saysound items' sounds are no longer replaced by items that would normally replace a yes / no / thanks sound.
