### ISSUE TITLE
Loadout: Something is off with badges on other people's profiles

### ISSUE THREAD

**Issue by haxtonsale** [redsunservers/LoadoutBugTracker#230]
Since the last Loadout update you can see 'New' badges in other people's profiles, the 'Limited or exclusive' badge count is broken and shows a completely different number.
![ebin2](https://user-images.githubusercontent.com/26278199/40241999-0f71a124-5ac5-11e8-94b3-9d09adf21a72.png)
The 'Limited or exclusive' badge count works perfectly fine on your own profile though.

**Comment by ramunecarbonated** [comment]
fixed, deploying later
