### ISSUE TITLE
Prophunt Bugs

### ISSUE THREAD

**Issue by Lex4eus** [redsunservers/LoadoutBugTracker#231]
1. Sometimes at the start of the round, some props have their weapons visible.
2. Last alive still has their weapon visible too
3. When on BLU, some teammates may also appear as props

**Comment by ramunecarbonated** [comment]
1st and 2nd is not really fixable due to past changes in general.
3rd doesn't seem to be reliably happening according to chat logs and plugin-wise this bug should not even be occuring, perhaps something was lagging the server out or a different error happened unrelated to the plugin.
