### ISSUE TITLE
SZF: weird interaction with smoker/hunter

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#232]
Consider this scenario:

1. A hunter gets a survivor, both are stuck inside each other
2. A smoker uses the beam on the pair, the survivor will get pulled out but still stunned (as intended)
3. The hunter will still be in the place he got the survivor, unable to move even after the stun period ends

Expected behavior: hunter doesn't get stuck in place indefinitely after the survivor is pulled out by the smoker's beam and/or is able to move immediately once he/the survivor are no longer stuck inside each other

**Comment by itVictor** [comment]
bumping as the issue is still occurring

would need to double check in game but it seems like
>smoker will no longer be able to pull stunned players.

wasn't actually applied

**Comment by koopa516** [comment]
smoker can no longer pull stunned players
