### ISSUE TITLE
unnecessary extra space for badge collector

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#233]
<img width="248" alt="screen shot 2018-05-19 at 4 50 58 pm" src="https://user-images.githubusercontent.com/20176719/40273617-d2494616-5b88-11e8-867f-b8ff6ae0f5d5.png">

**Comment by ramunecarbonated** [comment]
yeah, so apple's font is too big. the loadout now uses operating system fonts, will adjust.

**Comment by ramunecarbonated** [comment]
to be addressed in a general update to the header after maintenance
