### ISSUE TITLE
loadout: raiden not existing on servers area of the homepage

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#234]
![image](https://user-images.githubusercontent.com/23409983/40273866-cdfa9098-5b96-11e8-8a25-1ea01c29832f.png)

armstrong, mistral, ocelot and maverick are all there. raiden's just...gone.
already refreshed and ctrl+f5'd several times, still nothing, just broken

**Comment by EgocentricPoliceDick** [comment]
known bug that's existed for a while
as of right now we have no idea what's causing this, however something is causing the local data we query to return literally nothing.
