### ISSUE TITLE
URF/Freeze Tag: URF attributes are not given back to a player who was unfrozen by a teammate

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#238]
"Fists" of frozen players have URF attributes, but they're lost when a teammate helps them out. Players who respawn by staying frozen long enough in koth maps get the attributes as intended, though.

**Comment by ramunecarbonated** [comment]
The issue has been addressed but will be "live" on a later time, thanks for reporting!
