### ISSUE TITLE
Player/Badge levels being inconstant

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#239]
I had 296 badges, lvl 37 and 8 badges to collect for next level, working as intended.

However as old TA lvl 3 got moved to limited, I now only have 295 badges. I'm supposed to be in level 36 with 1 badge to collect for next level. But got this instead, lvl 38 with 7 badges to collect.
![playerlevel](https://user-images.githubusercontent.com/33488710/40456236-1d056074-5ee8-11e8-9bca-9ef557d8febe.png)

**Comment by ramunecarbonated** [comment]
this is a bug related to make limited badges also count towards this counter, i will soft-reset everyone so it resyncs up correctly.
