### ISSUE TITLE
Loadout: Slot filter in Inventory page

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#24]
There 2 slot filter under top in Inventory page where there is zero differences between, "Mention" and "Mention Sound"

![mention](https://user-images.githubusercontent.com/33488710/32658537-4d5968ac-c612-11e7-85b9-ef2232eda242.jpg)

Also "Haunted Refined Metal" don't appear in "Crafting Material" filter, while scrap and reclaimed is still in the filter.

**Comment by ramunecarbonated** [comment]
Thank Jugador for the two duplicate mention slots.  😂

**Comment by ramunecarbonated** [comment]
I have left the "Mention Sound" option, gave the Metal the proper tag on our Database and re-ordered the options alphabetically.
