### ISSUE TITLE
SZF: Make Sentries spawned by the map not lose ammo/destoy itself over time

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#241]
Ever since major szf update got released, sentries spawned from map loses ammo and eventually auto destorys itself. Previously sentries from map don't lose ammo and stays alive until either team destorys it.

This affect maps with sentries, szf_manncoscience, szf_pen15 and new szf_turtle_attack_v5.

Also be aware maps can have sentries infinite ammo flag either ticked or not.

**Comment by ramunecarbonated** [comment]
maps should not rely on sentries since the code hooks on all of them, with the recent big update, this change is intended.

**Comment by ramunecarbonated** [comment]
considering this breaks turtle attack i will make a work-around for it

**Comment by FortyTwoFortyTwo** [comment]
Fix does work on sentries spawned in map, but it also gives inf ammo to every sentry built by engineers.

**Comment by ramunecarbonated** [comment]
A simple "owner" id check shouldn't result in this.

**Comment by ramunecarbonated** [comment]
Reverting.
