### ISSUE TITLE
Ocelot using nerfed version of URF

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#242]
Apparently Ocelot is using nerfed version of URF, where most weapons got 1.5x extra rate rather than 2x extra rate

**Comment by EgocentricPoliceDick** [comment]
Well, I've checked the latest upload dates on the files on Ocelot. They're dated to today (26th May), so there should be no problem.

**Comment by FortyTwoFortyTwo** [comment]
I only have 6 clip size on my Rocket Launcher when URF is on, whereas it should be 8. Even after the fix attempt and map change, it still at 6 clip size.

![urf](https://user-images.githubusercontent.com/33488710/40580751-5d4ee40a-613d-11e8-9737-ad9a8e44f9ab.jpg)

**Comment by ramunecarbonated** [comment]
URF is not on the build bot, so it requires manual uploading. Uploading URF will also actually fix #238.
