### ISSUE TITLE
Strange Items: Strange Medic Calls don't track kills.

### ISSUE THREAD

**Issue by Waifers** [redsunservers/LoadoutBugTracker#244]
Similar to this except its bugged for medic calls instead.
https://github.com/redsunservers/LoadoutBugTracker/issues/205

Had a Strange Meem equipped earlier while it was on surf_leet and it didn't track any kills while my Strange skin, which was equipped at the same time the Meem call was equipped, was tracking them.
Probably isn't related to specific medic calls since other users have been saying that their various stranges weren't counting kills either.

**Comment by ramunecarbonated** [comment]
I think I know what this is, gonna check on it after I get back from the doctor.
