### ISSUE TITLE
Equipped items in the loadout not updating on Raiden

### ISSUE THREAD

**Issue by MugginsHere** [redsunservers/LoadoutBugTracker#245]
Currently, changing equipped items on the loadout doesn't actually do anything. The server chat says the loadout has updated, but nothing actually changes. As a part of this, coins can't be used either. This is happening to everyone on Raiden, I'm not sure if it's global. If there's any more info needed, I'll try to provide it ASAP

**Comment by EgocentricPoliceDick** [comment]
So, to confirm, equipped item status is being applied within the Loadout but not within Raiden?

**Comment by ramunecarbonated** [comment]
```
L 05/30/2018 - 12:07:42: Triggered GetClientLoadout for MugginsHere<10><[U:1:192267232]><>
L 05/30/2018 - 12:08:01: Triggered GetClientLoadout for MugginsHere<10><[U:1:192267232]><>
```
This means that the function to execute the function was succesful. So the link does work.


>As a part of this, coins can't be used either.
That is normal, to prevent specific abuse with usable items, they are "detached" before the queries are fired to fetch your items.


However, during our Database downtime 8 days ago, we lost all the foreign keys in the Database it seems, those were to make sure that if you use an item or no longer own it, it automatically gets detached from the table where we store all of your equipped items. Hm.

**Comment by EgocentricPoliceDick** [comment]
Should be fixed as of this message.
