### ISSUE TITLE
Loadout: Items equipped not being updated

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#246]
Similar to issue #245, if you tried to change item in equip page, it says equip was successful and it automatically refresh ingame. However refreshing action page shows that your change actually did not apply into it and in servers, still using your previous equipped item.

**Comment by M-Dizzy** [comment]
I also have the same issue, which really sucks because I wanted to buy a URF coin to then use it on Raiden, but it seems no one will be able to activate URF-Mode since this bug doesn't allow people to use the said coin.

**Comment by EgocentricPoliceDick** [comment]
Sounds like a continuation or something from #245 which might have been overlooked.

**Comment by ramunecarbonated** [comment]
no, #245 simply straight out missed that detail, that makes the issue a complete different thing.
