### ISSUE TITLE
Freeze Tag: No Item drops during this gamemode

### ISSUE THREAD

**Issue by Drand0r** [redsunservers/LoadoutBugTracker#247]
After the Frostbite title was added to only drop in Freeze Tag, it seems that despite multiple maps of Freeze Tag with 20+ players and URF active, not a single person has been getting any BP or item drops.

**Comment by koopa516** [comment]
can anyone confirm whether this is still the case? I couldn't even find the frostbite title drop code

**Comment by woisalreadytaken** [comment]
i've seen items drop fine in freeze tag recently, just not the title

**Comment by EgocentricPoliceDick** [comment]
closing this because issue is misleading (items do drop) and the title was just never coded in as an event thing, maybe one day it will be
