### ISSUE TITLE
Bp drop does not play the "ka-ching!" sound

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#25]
Upon collecting BP, the administrator voice line is heard, but no "ka-ching" sound plays with it (or it is EXTREMELY quiet).

Happens all the time, whether you have the Isaac item or not.

edit: I should clarify that this makes the Isaac item do nothing when equipped

**Comment by ramunecarbonated** [comment]
The item does work but the volume between the voice line and the sound itself is way out of balance: the item should have been made louder during implementation.

With that said, a fix is almost ready.

**Comment by ramunecarbonated** [comment]
Addressed in today's server update. http://steamcommunity.com/groups/redsunoverparadise/announcements/detail/1455087914546564131
