### ISSUE TITLE
issue with @mentioning people after a saysound

### ISSUE THREAD

**Issue by tacticturtle123** [redsunservers/LoadoutBugTracker#251]
what I mean is, pinging somebody in the same line of text as a saysound will add "FFA 500" at the end of their name.

for example if I said: "ur so mad @tactic" it would appear as "ur so mad tacticFFA 500"
however, if I said "@tactic ur so mad", it would appear normally as "tactic ur so mad".

(also, this is unrelated but, why does saying "ur so mad" anywhere in a sentence trigger the say sound?, I'm curious because it's the only saysound that does this)

**Comment by EgocentricPoliceDick** [comment]
This is related to #249.

@Benoist3012 decided to entirely rewrite the code for that section of our chat plugin, however hasn't added in some of the features from the old one which actually protected against this. One of which is the bug you're mentioning.

(It's not just that saysound.)

**Comment by Benoist3012** [comment]
Fixed

**Comment by itVictor** [comment]
bumping as the bug is still occurring

**Comment by Benoist3012** [comment]
nope, it's fixed, it's just the bot that didn't upload to serv everything is resolved now

**Comment by Benoist3012** [comment]
the only instance left is mention at the end which I'll fix now

**Comment by Benoist3012** [comment]
fixed

**Comment by Benoist3012** [comment]
so it doesn't happen during my test, and after live testing on servers with several people then weeks later break? I suspect either a recent change from either Tohru or Frosty or Paddy or Wave has been made and broke some part of the code or it's a bug that flew under the radar. I'll check that later today, thanks for the report!

**Comment by EgocentricPoliceDick** [comment]
I haven't heard anything on this in a while. @Benoist3012 can I assume this is fixed?

**Comment by koopa516** [comment]
still happening on servers as of last night

**Comment by Benoist3012** [comment]
Til I get back (i.e tomorrow) nothing has been done, just thinking about the method to fix.

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/redsunservers/LoadoutBugTracker/issues/251
