### ISSUE TITLE
SZF: New zombie models aren't downloading

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#252]
Zombie models were updated yesterday (or earlier today depending on your timezone), but they're not downloading and zombies show up as errors. Seen on Armstrong and Mistral.
The Adachi and Kinessa skin overhauls that were added at the same time are working as intended.

![image](https://user-images.githubusercontent.com/33163183/42432177-b7f28750-831f-11e8-9a34-866f0d6595b7.png)

**Comment by EgocentricPoliceDick** [comment]
Unsure as to why this is happening. Will look into

**Comment by EgocentricPoliceDick** [comment]
Have found the issue, uploading fix.
