### ISSUE TITLE
constantly being logged out of loadout?

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#254]
not sure if this is just an issue with my browser or not, but it seems like i'm being logged out of the loadout for no real reason if i stay away from it for a couple hours. i'm still logged into steam and other websites just fine -- it just seems like i'm not able to keep a session going with the loadout. this only happened after the update to the code that handles sessions (at least according to what oWave posted in announcements on discord), so i don't know if this is intentional or not.

running firefox 61.0.1.

**Comment by Benoist3012** [comment]
The update to sessions isn't the root problem, I believe the problem is from the clean up cron that wave updated. Either way we will check both thanks for report.

**Comment by oWave** [comment]
Fairly sure I found the issue. Fix is live.
