### ISSUE TITLE
SZF: Frenzy & Tank spawns

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#256]
In all servers, forcing a frenzy using logic_relay szf_zombierage does not work when there an info_target szf_director_norage in the map, whereas force frenzy from the map should've bypass the no frenzy rule. Force tank however still works in this situation, bypassing the rule.

In mistral only, frenzy & tank from director did not appear at all after several maps. Force tank from map however still works.

**Comment by Benoist3012** [comment]
Done as of commit `952f43c872a24f8fcfcf0ebff815250942264625`
