### ISSUE TITLE
Unable to use hop command to join other servers

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#257]
When typing !hop, it shows a lit of servers as normal. However selecting a server to join does not work, as you have never been given a chance to press f3 to join other servers.

**Comment by EgocentricPoliceDick** [comment]
And you've checked multiple times, right? Sometimes it won't select the server because that server is currently changing maps (which makes it unavailable).

**Comment by FortyTwoFortyTwo** [comment]
tried multiple times in multiple servers, still did not get to press f3 to join said servers

**Comment by EgocentricPoliceDick** [comment]
The plugin we're currently using has been known to have a few minor hiccups, however this is a relatively minor thing. I'll look into replacing the hop plugin once we have fixed some of the more major issues.

**Comment by itVictor** [comment]
It's possible that !hop not working has nothing to do with the plugin itself.

Valve changed the default value of cl_showpluginmessages from 1 to 0 in an update a few months ago (don't know which exact update) and when it's set to 0, you do not see the confirmation overlay. Changing it to 1 will re-enable the overlay and !hop will work normally.

Just tested !hop a few minutes ago and found no issues with using it.

**Comment by EgocentricPoliceDick** [comment]
If it's still happening after following those instructions above then i'll keep this open.

**Comment by EgocentricPoliceDick** [comment]
Can confirm this is because of valve fucking over default convar settings again.
gdi john
