### ISSUE TITLE
maverick not querying on website after server move + misnamed country in server name

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#261]
![image](https://user-images.githubusercontent.com/23409983/43361068-b6746258-9293-11e8-9a5a-01a82b28ad80.png)
![image](https://user-images.githubusercontent.com/23409983/43361080-101c3c4a-9294-11e8-8999-20854f41f4ac.png)

small bugs i noticed, server isn't querying (assumingly because of server IP change because of the move) and the server name's country ingame is in china for some reason? i thought it was a US server

**Comment by oWave** [comment]
Thanks for the report. Issue has been resolved.

**Comment by EgocentricPoliceDick** [comment]
The servers tend to use city codes, not country codes. I was told by @koopa516 that CHI is used for Chicago servers.

Not a bug.
