### ISSUE TITLE
Excessive stuttering on Mistral

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#262]
Ever since the server got more populated recently, I've noticed that Mistral has been stuttering almost constantly, as well as increased timeouts in specific situations (such as between rounds). The move from LA to Chicago doesn't seem to have affected the stuttering at all so something else may be causing it. 

Can't say for sure but I think the stuttering is worse when a lot of people are on the server.

**Comment by EgocentricPoliceDick** [comment]
Probably just some teething issues. I'm looking into them.
