### ISSUE TITLE
VSH crashing Armstrong

### ISSUE THREAD

**Issue by Wes-the-mew** [redsunservers/LoadoutBugTracker#263]
The VSH game mode consistently crashed Armstrong at around 5 minutes before the map changes with out fail it seems. It also seems that Glitched Robot crashes Armstrong as well at random.

**Comment by EgocentricPoliceDick** [comment]
patched

**Comment by EgocentricPoliceDick** [comment]
t. benoist not applying convar changes to other servers

**Comment by Benoist3012** [comment]
I blame sm dev team
https://forums.alliedmods.net/showpost.php?p=2540106&postcount=324
Seriously though, yeah I won't forget to update it on all servers now.
