### ISSUE TITLE
SZF : Crashes your game more often... Too often

### ISSUE THREAD

**Issue by M-Dizzy** [redsunservers/LoadoutBugTracker#264]
For some reasons, when I play SZF since I came back from London, the game will crash after 5 to 15 minutes with the following message "Out of memory or address space. Texture quality may be too high."

However, the problem doesn't come from my PC since I hasn't this problem to begin with, so my best conclusion is that SZF overflows your CPU so much that it basically crashes.

Basically, fix the shitty optimization of SZF.

**Comment by EgocentricPoliceDick** [comment]
First off, this isn't "shitty optimisation". This is a known bug related to .cache files that Valve has not fixed.

I've mentioned before that there is a fairly simple workaround if you are having these issues, and that is simply to delete .cache files (eg. soundcache) within your TF install.

**Comment by EgocentricPoliceDick** [comment]
Second, please don't insinuate that our codebase is garbage badly optimised. It comes off as very rude. More often than not it's the engine itself causing some of these issues, meaning Valve is at fault for these issues, not us.

I'll be locking this.
