### ISSUE TITLE
DR: Cannot get badge but it should have happened

### ISSUE THREAD

**Issue by Lomek** [redsunservers/LoadoutBugTracker#267]
![20180801064835_1](https://user-images.githubusercontent.com/41980320/43501567-d7d357ce-955e-11e8-9be2-b3b0fd30b1e6.jpg)
It happened on Armstrong. There is problem with "Rainbow Run" badge, my team won the race and I stayed alive, but for some reason I didn't get the badge while my allies got it. I don't have this badge in my profile: https://redsun.tf/player/76561198043421228

**Comment by Benoist3012** [comment]
It is possible that the loadout didn't respond well to the query, I've verified the logs and yes you should have obtained it. I'll hand this one manually sorry for the inconvenience.
