### ISSUE TITLE
Golden Smash Coins not resetting options at end of map

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#269]
When somebody picks a round using a golden smash coin, the round can't be picked again by another golden smash coin (as expected). However, if smash appears again later, that round still won't be available to be picked, and I assume that only a crash/server restart will properly reset the list of special rounds.

Example:

1. Map A (smash): I use a golden smash coin and 20XX is an available option. I pick it. If I use another golden smash coin later, 20XX is not an available option. Same thing happens if anybody else uses a golden smash coin (so only way to get 20XX again is to be lucky with regular smash coins).

2. go to x maps afterwards that aren't smash

3. Map B (smash): I use another golden smash coin, but 20XX is not an available option, because the list of available special rounds did not reset when we switched off of Map A.

Expected behavior: The list of available special rounds for golden smash coins is reset upon map end instead of an instance where the server needs to be restarted (crash, etc.).

**Comment by EgocentricPoliceDick** [comment]
This isn't a bug.
The coin only re-enables options after a set time to prevent constant use of popular modes on the coin.
