### ISSUE TITLE
Store related buggy badges

### ISSUE THREAD

**Issue by Mr-Zetix** [redsunservers/LoadoutBugTracker#270]
As you know,there are a some badges about the store. And both of them aren't working for me because i have bought more than 20 items and spent more than atleast 500 on store but still haven't got some of those badges .

**Comment by EgocentricPoliceDick** [comment]
![image](https://user-images.githubusercontent.com/23524293/43647410-7b7d0f38-972f-11e8-97a6-972ea4245bbe.png)
