### ISSUE TITLE
!unusual command not working on specific servers

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#272]
[SM] Skin Effects are currently disabled!
You have disabled First-Person item effects.

shows in chat every time when you do !unusual on Raiden and Armstrong only, there is no way to enable the effects on those servers. The command works fine on the servers not mentioned, no issues with enabling/disabling effects there.

I'm aware that unusuals are disabled in certain gamemodes regardless, but I tested this in 5-10 gamemodes and got the same result every time.

**Comment by EgocentricPoliceDick** [comment]
Skin unusuals are controlled by a convar for gamemodes like PropHunt to prevent them being detrimental. Seems it's not resetting the convar.
