### ISSUE TITLE
Haunted Glow unusual effect not appearing on 'The Bounty Hunter' skin

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#274]
![image](https://user-images.githubusercontent.com/23409983/43751422-d246a71e-99ca-11e8-83f7-dfc46d765e96.png)
![image](https://user-images.githubusercontent.com/23409983/43751446-ed385d10-99ca-11e8-9e05-34db3016569f.png)

unsure if this effect also glitches on other skins, this is the only unusual i have with this problem

**Comment by EgocentricPoliceDick** [comment]
duplicate issue of #272 afaik

**Comment by infinitephantasm** [comment]
this was on mistral, though, and i'm able to enable and disable them just fine. other unusual skins also appear ok on my end with first person effects enabled, including my stylish medicine w/ team sparks & john henry w/ haunted flames

**Comment by EgocentricPoliceDick** [comment]
spawned one in for myself, seems to be an issue with the particle itself
wish these bugs would fuck off

**Comment by FortyTwoFortyTwo** [comment]
Another 2 skins also have this similar problem, Sentry Specialist with Haunted Glow (same effect) and Stylish Medicine with Holy Glow

![](https://i.imgur.com/rcgUL6M.png)
![](https://cdn.discordapp.com/attachments/467001266820874250/475650736244391936/unusual.png)

However though, one person was able to see the Holy Glow effect while others cant see it, which may be to do with client side. Dunno if he could also see the Haunted Glow effect or not.

**Comment by koopa516** [comment]
Assigning Benoist to this one since I honestly don't know anything about how the haunted glow particle works, and as for Holy Glow I need to do some testing to see if it really is broken and how broken if so

**Comment by EgocentricPoliceDick** [comment]
In regards to the broken particle, in all likelihood I may just replace it with one known to work. As for Comm. Sparkle items, that is another story.

**Comment by EgocentricPoliceDick** [comment]
first point: blame valve for that. Particle systems are fucky to start off with post-attachables.
second point: it's been low prio for now, might look into a new effect for it.

**Comment by FortyTwoFortyTwo** [comment]
fixed
