### ISSUE TITLE
Dodgeball: Missing particles

### ISSUE THREAD

**Issue by haxtonsale** [redsunservers/LoadoutBugTracker#275]
Missing particle appears when a mono rocket or nuke is spawned or airblasted. Happened to everyone on Raiden, not sure if other servers have the same issue

![20180807152549_1](https://user-images.githubusercontent.com/26278199/43776443-90df076a-9a58-11e8-813e-178e8067a068.jpg)

**Comment by EgocentricPoliceDick** [comment]
That's a map issue, you'd have to raise it with the map's creator.

**Comment by tacticturtle123** [comment]
It’s not a map issue, we’ve had it on every DB map we’ve played today.

Only remember seeing it once yesterday though, and that was on tfdb_ring_slag and I’m not sure if the bug occurred before that map.

**Comment by koopa516** [comment]
this was an issue caused by changes I made to the precache system throwing an error before it had a chance to precache the proper particle systems. This also broke a lot of other features which should all be working now.

**Comment by EgocentricPoliceDick** [comment]
Invalid particles are caused by the map not knowing what particle to attach to a specific event. It CAN carry over sometimes, but the bug is caused by a map, not the plugin.

Again, you'd need to contact the map's creator.

**Comment by EgocentricPoliceDick** [comment]
hah yes github please dont show me updates
