### ISSUE TITLE
Class limit plugin precaches outdated/invalid sound files

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#276]
Since it was readded, people try to download vo/[class]_no[number].wav files every time it changes to a map with the class limit plugin being active, these sound files should be .mp3 instead. Seen on Raiden

**Comment by EgocentricPoliceDick** [comment]
one of the reasons i removed this plugin last time
@Benoist3012 @koopa516 this is your fix

**Comment by Benoist3012** [comment]
I'll fix this asap it is likely due to the public plugin classrestrict

**Comment by Benoist3012** [comment]
dunno why was closed

**Comment by EgocentricPoliceDick** [comment]
iirc this should be fixed now, i uploaded a fixed ver which now correctly precaches a few months back
