### ISSUE TITLE
Randomizer: interaction with PASS Time does not allow players to properly hold the Jack

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#277]
Some maps were recently added to the randomizer rotation, one of them is pass_brickyard_event (I don't know if there are any other pass time maps), if someone tries to grab the Jack/ball with the randomizer plugin being active, the game will know that a player has the ball, but the player will hold the last weapon they were using before grabbing it. This means that people can't pass or shoot the ball to score until they die (or drop the ball if that's even possible), making the experience overall really boring (and people keep whining about it).

Now, I know that the randomizer plugin is a mess and you might not be able to/want to work around it right now, so I just ask you to remove pass time maps from its rotation for the time being instead.

**Comment by EgocentricPoliceDick** [comment]
yes, it is a complete hot mess that no one is prepared to sift through and rewrite into a decent working state, but i will  at the very least take the pass time maps out of rotation

consider this closed

**Comment by EgocentricPoliceDick** [comment]
actually fuck since i forgot to do this last night i will reopen this & unassign myself since i am gone for a few days

**Comment by koopa516** [comment]
took a look
legit can't fix this as much as I hate to say it
