### ISSUE TITLE
Dodgeball rocket speed/reflects panel not showing up

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#279]
title -- it's just not showing up. not sure if this is a server-specific thing, as i've only played dodgeball on armstrong recently and that's where i'm seeing this issue.

not sure if this just happened to be removed on purpose, but it used to be there, and now it's not.

**Comment by koopa516** [comment]
i really fucking hope i fixed this

**Comment by itVictor** [comment]
bumping again as issue still occurs

**Comment by woisalreadytaken** [comment]
i'd like to add that this is fixed in raiden, still happens in armstrong and i dunno about the 2 other servers

**Comment by EgocentricPoliceDick** [comment]
i am making sure all servers run the same version now
locked
