### ISSUE TITLE
A szf duplication bug

### ISSUE THREAD

**Issue by Mr-Zetix** [redsunservers/LoadoutBugTracker#280]
I was a demoknight with a shield then i saw a scottish resistance and went to pick it, after that i got stuck into the shield so i picked it back but i somehow managed to pick another scottish resistance 
So i tried picking the real one on ground they both were working.

**Comment by EgocentricPoliceDick** [comment]
Do you have any screenshots or more detailed steps on reproduction? Otherwise I will close this as invalid as you're not providing much detail.

**Comment by EgocentricPoliceDick** [comment]
Going through old tickets to clear out backlog.
If this is still a problem, please send a reply here to reopen the ticket otherwise I will just leave this closed but unlocked.
Entirely possible this was never documented in one of the pushes, but wouldn't like to be 100% certain

**Comment by FortyTwoFortyTwo** [comment]
Bumping to say this bug is still here with same steps to reproduce it

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/EgocentricPoliceDick/SZF-private/commit/845e2cd37e6cca661a816a602a4bc5a8f411e2ba
