### ISSUE TITLE
titan.tf not in website/name filtering

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#283]
![image](https://user-images.githubusercontent.com/23409983/44814037-737a0780-aba9-11e8-86f1-086866477ba2.png)
![image](https://user-images.githubusercontent.com/23409983/44814066-84c31400-aba9-11e8-9b8b-8ae99567d9f4.png)

not sure if this is the place to submit this, but i'm just figuring this is a bug since (from what i can tell) it's not an attempt to bypass the filter

**Comment by EgocentricPoliceDick** [comment]
Name filter has been shitting the bed recently because of the sheer number of shit i have had to filter resulting in it hitting the memory limit for the compiler.

**Comment by EgocentricPoliceDick** [comment]
PSA: hardcoded filters are bad, boys and girls.
