### ISSUE TITLE
Dodgeball maps using workshop don't have functioning dodgeball coins

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#284]
![image](https://user-images.githubusercontent.com/23409983/44999807-f75b3780-af8d-11e8-9859-ee742136efe1.png)

happened when i tried to use a challenge coin on the workshop version of tfdb_shapes on maverick.
tried a dangerous speed and triple trouble coin to no avail, so assuming all db coins are affected by this

**Comment by EgocentricPoliceDick** [comment]
What specific map was this?

**Comment by infinitephantasm** [comment]
workshop/tfdb_shapes_rc1.ugc1498435996

**Comment by EgocentricPoliceDick** [comment]
(i am an idiot)

**Comment by EgocentricPoliceDick** [comment]
Likely that this is just a config issue, I'll check to confirm

**Comment by infinitephantasm** [comment]
still happening, same map as before
if it matters, this was on armstrong

**Comment by FortyTwoFortyTwo** [comment]
still happening, raiden as well.

**Comment by itVictor** [comment]
bumping as issue still occurs, happened with tfdb_bwcell on raiden

**Comment by koopa516** [comment]
Fixed
