### ISSUE TITLE
VSH Rewrite: Painis Cupcake model bugs out when Soldier's zombie cosmetic is equipped

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#286]
https://gfycat.com/VainGargantuanAmericanlobster
https://i.imgur.com/ziorqed.jpg
title

**Comment by Benoist3012** [comment]
Thanks for report i'll make sure to fix this!

**Comment by FortyTwoFortyTwo** [comment]
I'm assuming this bug affects all bosses, which i've fixed it

**Comment by FortyTwoFortyTwo** [comment]
Actually fixed it for real in https://github.com/EgocentricPoliceDick/VSH-Rewrite/commit/1872cd2b886b60423315baee9fc70560fd5c3710
