### ISSUE TITLE
Loadout: Several Season of Screams II items are missing their event vanity text

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#287]
This isn't really a bug, but rather an inconsistency issue that could be considered as (very?) low priority.

The only items from the event that have the "Season of Screams II (2017)" vanity text are the contract pass and premium music kits released back then. If this makes it easier for you, I'll list all of the items that should have it (to make it consistent with items from any other event, I'll go for items that could be crafted in Haunted quality, items that can be unboxed from crate 3 and the title that people got for finding enough gifts):

Battlecry: Ellis _*this item was technically released before SoS2, but was used for the event_
Death: A Heavy Death
Death: Good Night!
Lookout Louis
Respawn: Chozo's Revival
Respawn: Michael Rosen
Respawn: The Brother's Bout
The Crusader's Call
Title: A Sweet Treat
Title: Death's Locksmith
Title: Death's Metalworker
Trail: Cotton Candy
Trail: Marble Ice Cream
Trail: Midnight Drive
Trail: Ocean Breeze
Trail: rabscootle's Legacy
Trail: The Music Scene
Trail: Trick-or-Treat
Trail: X4
Übercharge Music: Brain Power
Übercharge Music: Poltercharge 5000
Übercharge Music: Temporary Badass

**Comment by EgocentricPoliceDick** [comment]
A minor issue at best. I'll fix this when there's time.

**Comment by EgocentricPoliceDick** [comment]
fixed
