### ISSUE TITLE
szf_isaac_v2 badges not unlocking

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#288]
[demo file where CHAD and ??? fight was won, but no badges were unlocked](https://share.dmca.gripe/9AnfziK9YBM3uQfk.dem)

i don't exactly know what's causing this, but these badges are currently unattainable as far as i know. this was on armstrong, server was above 10 players so it definitely should be able to be earned

**Comment by FortyTwoFortyTwo** [comment]
Buildbot is currently having a problem uploading plugins to Armstrong with "access declined" or whatever it is, meaning that all plugins in armstrong have not been updated since late July iirc.

**Comment by Benoist3012** [comment]
On that note badges were also disabled. Unless Haru didn't.

**Comment by EgocentricPoliceDick** [comment]
Haven't touched anything lately @Benoist3012

**Comment by infinitephantasm** [comment]
people had these badges earned on server according to badge list, so i assumed they were active

**Comment by EgocentricPoliceDick** [comment]
Haven't heard anything for this in a while. Feel free to reopen if it's still an issue.
