### ISSUE TITLE
[VSH Rewrite] Prevent bosses taking fall damage

### ISSUE THREAD

**Issue by unitgon** [redsunservers/LoadoutBugTracker#291]
Bosses should probably not take fall damage, as their superjump is a pretty huge mode of transportation for them.

Currently with approximately 20 people in the server, you can basically self hurt yourself for 5 percent points of rage per jump.

Edit: didn't realise it was intentional, or so I heard.

**Comment by Benoist3012** [comment]
the fall damage are intentional (it's always 100) but building the rage with it sounds too much so i'll change that.

**Comment by Benoist3012** [comment]
Alright I've changed how fall damage functions, bosses will still take 100 fall damage unless their health is under 1k hp.
But you can no longer build up your rage with self inflicted damage.
