### ISSUE TITLE
Bug with Glitched Robot's Rage?

### ISSUE THREAD

**Issue by tacticturtle123** [redsunservers/LoadoutBugTracker#294]
playing as Glitched Robot on Mann.co HQ when I raged and hit a scout 3 times with my melee. the hit sound played 3 times and yet no damage was dealt.
I then raged again later on in the round, and the exact same thing happened: hit someone 4 times with the melee, hit sound played each time yet no damage was dealt.

sure, there is the chance that this is a coincidence, however the exact same thing used to happen in VSH rewrite when it was new, leading me to believe this is a bug. 

Can other people look out for this and see if it happens to them? note that each time this happened, the person was right next to me, meaning I had to look almost directly down. See if that could cause it.

**Comment by woisalreadytaken** [comment]
> Can other people look out for this and see if it happens to them?
yes, Glitched Robot's melee range during its rage increases client-side, but not server-side, resulting in a lot of ghost hits. Can't tell if it's supposed to be increased or not.

**Comment by FortyTwoFortyTwo** [comment]
I could just give glitched robot extra melee range when giant, though not sure if that would be too op

**Comment by FortyTwoFortyTwo** [comment]
Gave gliched robot melee range the same as giant scale during rage, which that fixes the fake melee hitsounds
https://github.com/EgocentricPoliceDick/VSH-Rewrite/commit/2dea7cce63ea06bb117177cf57381142d1728c27
