### ISSUE TITLE
Incorrect user card info for staff members in motd

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#296]
The user cards for the staff members listed at redsun.tf/motd say that every staff member is "browsing the loadout" even when they are obviously offline. If a staff member IS browsing the loadout or ingame on any of the servers the user card will display the proper information. 

The "players currently active" section on the home page does not have this issue.

**Comment by oWave** [comment]
Thanks for the report. Fix is already live.
