### ISSUE TITLE
Supply Crate Keys for the crates are not being consumed on use.

### ISSUE THREAD

**Issue by EgocentricPoliceDick** [redsunservers/LoadoutBugTracker#3]
On investigation, it seems like the crate is being consumed, but not the key.
Some attempts also show that neither is consumed.

**Comment by EgocentricPoliceDick** [comment]
Upon further inspection, Crate #2 is consuming keys designated for Crate #1.

**Comment by EgocentricPoliceDick** [comment]
tl;dr

Crate 1: Consumes the key, but not the crate.
Crate 2: Consumes Crate 1's keys. Crate itself is not consumed.
Crate 3: Crate itself is consumed, but key is not.

**Comment by EgocentricPoliceDick** [comment]
Correct crate series should now be consumed always on use.

Now to look at why the key being consumed is the series before...

**Comment by koopa516** [comment]
Fixed.
