### ISSUE TITLE
"Scream Fortress Win Contract Mk. III" not working on "cp_alamo_event"

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#30]
We've won about 5 times now, was at 6/12 before the map and it still is currently at 6/12. /refreshcontract does nothing. According to ShavedFanatic, scream fortress kills were counting on the map, despite wins not counting.

**Comment by CountSexulus** [comment]
*side note, this happened before the announcement saying some back end stuff had changed

**Comment by ramunecarbonated** [comment]
What category was this map in?

**Comment by ramunecarbonated** [comment]
okay, should be fixed for real now
