### ISSUE TITLE
The Retired Hermit item not working

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#300]
1. When item is equipped, jeers does not work at all, when you press C + 4, there is no sound. Also no error in console like an invalid sample rate
2.  Item description is wrong, https://i.imgur.com/ZnFKk2p.png Jeers is C + 4, not C + 3

**Comment by EgocentricPoliceDick** [comment]
Finally got time to work on these. Seems easy enough, will get through these.

**Comment by EgocentricPoliceDick** [comment]
2nd one fixed, checking 1st one
