### ISSUE TITLE
Combat Surf: Phlog taunt can be cancelled by bhopping

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#301]
Title, when you have full mmmph, hold jump, hold right click, and when you land you'll cancel out of the taunt, giving you uber and crits for a brief period of time

**Comment by EgocentricPoliceDick** [comment]
Fixed as of https://github.com/EgocentricPoliceDick/redsun-surf/commit/924df53b7730ec422171661039b0f60a3c8d77f7
