### ISSUE TITLE
Missing Collector: Captain Falcon Battlecry

### ISSUE THREAD

**Issue by VoidBlitz16** [redsunservers/LoadoutBugTracker#302]
As far as I know, if you can unbox an item, you can turn 20 of it into a collector's version.

Upon acquiring 20 of Captain Falcons from the shop since you can get a Strange version of it in Salvaged Supply Crate 8: Obligatory Celebrations, I found that you can't make a collectors of it.

tl:dr probably missing an item to the collector collection

**Comment by woisalreadytaken** [comment]
collectors items only apply to items that can be unboxed in unique quality, falcon battlecry can only be unboxed as strange so it isn't available in collector's quality

**Comment by EgocentricPoliceDick** [comment]
> 
> 
> collectors items only apply to items that can be unboxed in unique quality, falcon battlecry can only be unboxed as strange so it isn't available in collector's quality

Not a bug.
