### ISSUE TITLE
Gifted Supply Crate Key not working

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#306]
I was gifted two supply crate key to unbox #5 crates which do not work. I equiped the crate and tried to open it to no success, i refreshed multiple times, didn't work either.
![20181207151134_1](https://user-images.githubusercontent.com/45695904/49663124-00a4e600-fa4e-11e8-8319-3457e24b035a.jpg)
This is what i get. This could be caused by the fact the keys were gifted to me.

**Comment by EgocentricPoliceDick** [comment]
I have checked the items in question and they are showing as turned off/disabled (passive). I have enabled the items manually, please try again.

**Comment by UrUgli** [comment]
I got keys gifted again and still doesn't work

**Comment by oWave** [comment]
Issue should be fixed. Sorry about that
