### ISSUE TITLE
SZF: Tanks get healed from sandviches/other foodbox items

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#307]
Related to the new tank health system, Tanks can easily regen a lot of health by taking sandviches from other zombie heavies. (For example, if a Tank has 1000 max health, sandviches heal it for 500)

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/EgocentricPoliceDick/SZF-private/commit/789a69d79c6639d5ee76a0d29a4406e7b64686f4

However it possible this bug may still appear, feel free to reopen if so

**Comment by FortyTwoFortyTwo** [comment]
(why haven't anyone reopened this yet)
Not fixed

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/EgocentricPoliceDick/SZF-private/commit/67f62215fe9494e27e4cbd83350d7025e09e7381
