### ISSUE TITLE
SZF: Frenzy sets morale to 100

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#308]
Not too much to say about this one, it once happened when I had about 15 morale so I assume it just goes up straight to 100 instead of adding a lot.

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/EgocentricPoliceDick/SZF-private/commit/1bad07ef796901a1d17540bacbe77e34a3634396
