### ISSUE TITLE
Secret Santa 2018 title does not display properly in-game

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#309]
As of now, the title eats a couple of characters away from chat messages, uses wrong colors and interacts in a weird way with server messages like rtv/rolling a number

![image](https://user-images.githubusercontent.com/33163183/50426795-6d0d4b00-087e-11e9-9021-3459d8a11d2b.png)

![image](https://user-images.githubusercontent.com/33163183/50426801-8615fc00-087e-11e9-80e6-4954d4347eb1.png)

**Comment by EgocentricPoliceDick** [comment]
It's an issue with the data preview. I'll take a look at it.

**Comment by EgocentricPoliceDick** [comment]
I've tried something simple to fix this on Raiden. Will be applied on other servers shortly.
Can you confirm the issue is fixed or is it still happening?

**Comment by woisalreadytaken** [comment]
It's still happening

**Comment by EgocentricPoliceDick** [comment]
Currently in-game trying to determine the cause. Seems as though the chat plugin is skipping a termination character or something.

**Comment by EgocentricPoliceDick** [comment]
Looks like some shitty level json fuckery. It'll iron itself out over a forced restart on all servers.

**Comment by woisalreadytaken** [comment]
This started happening again, first seen yesterday on Raiden

**Comment by EgocentricPoliceDick** [comment]
christ on a cockstick
investigating

**Comment by EgocentricPoliceDick** [comment]
Was caused by something nulling the database's itemdata field for nametitle. Has been fixed.
I hate this thing.
