### ISSUE TITLE
Fart Coin doesn't play any sounds after its activation

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#31]
A farting noise plays when the coin is activated, but after that, nothing happens.

**Comment by ramunecarbonated** [comment]
Upon further investigation, it was not a bug but merely due to its extreme RNG. This will be addressed anyay.

**Comment by ramunecarbonated** [comment]
The chance for a fart to occur has been increased.

**Comment by Benoist3012** [comment]
*fart intensifies*
