### ISSUE TITLE
Dodgeball: Barrage coins don't last longer if the user has a high donator level

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#311]
Both Rocket and Striker Barrage Coins always last a fixed amount of time, regardless of donator level, I'm not sure if this is intended or not, but I'm putting it here if it isn't.

In the case it is, adding a negative description saying the donator perk won't work with the coins (like drop rate coins have) would be appreciated.

**Comment by EgocentricPoliceDick** [comment]
Looking into this.

**Comment by EgocentricPoliceDick** [comment]
I've looked through a large chunk of changes to the code of striker-related code for this and it does just seem to be a mislabelling or an oversight. I'll add the flavor text on the item itself, but we could add this later on as an actual feature if it's requested.
