### ISSUE TITLE
Premium Dodgeball Kits: Hover and LISA don't play their preround sounds

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#312]
This issue only happens with these two kits, the sounds are precached and download fine, no errors in console.

Possibly a related issue: unlike every other premium kit (except for the ones that add announcers), these two kits also don't have rare win sounds, I'm not sure if this is intended or they're just missing.

**Comment by EgocentricPoliceDick** [comment]
I think I might know why this is happening. Give me a while to take a look.
