### ISSUE TITLE
Szf: reserve ammo persisting through different weapons

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#313]
If you pick up a scottish resistance in a round and then pick up a stock stickybomb launcher later, the launcher's reserve ammo will still be 36 (from the resistance) instead of the normal 24 for the launcher.

Don't know if it happens with other weapons with different ammo counts as I did not get a chance to test.

**Comment by FortyTwoFortyTwo** [comment]
bug actually happened before 2.33_rsx, and still happening

**Comment by FortyTwoFortyTwo** [comment]
So it turns out benoist already made a fix for it about a year ago, but somehow got reverted one time, so i readded the fix
https://github.com/EgocentricPoliceDick/SZF-private/commit/a5b7e087747c79d491141010b31d185e12ff1c25
