### ISSUE TITLE
SZF: If a Soldier/Pyro grabs a Panic Attack while already having a primary weapon, the primary weapon will be stripped

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#315]
Their previous secondary weapon will be replaced as intended, but primary weapons just disappear, probably has something to do with the gamemode thinking it's an Engineer weapon at all times. Does not happen with the Shotgun.

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/EgocentricPoliceDick/SZF-private/commit/9fa17dc92a900af52eb6a33d8a9bb9130dab7ce6
