### ISSUE TITLE
outdated info in !hop/chat ads

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#316]
(remade as new issue as per request)

only happens on raiden, other servers not affected (basically same issue as #265 )

![image](https://user-images.githubusercontent.com/20176719/50621090-47f58980-0ec9-11e9-95a9-1643ea519f97.png)

**Comment by EgocentricPoliceDick** [comment]
Aside from the mis-attributed location tag, these servers resolve successfully.
Please be more descriptive of future issues.
