### ISSUE TITLE
"Key to Success" saysound pack can not be de/activated, as it's a hidden passive

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#317]
This probably happens because the item name has "Key" in it, so it doesn't show up in the equip page, like actual keys. If it was gifted, it can not be activated (unless this has already been changed with issue #306).

**Comment by EgocentricPoliceDick** [comment]
Applied a minor change as of https://github.com/EgocentricPoliceDick/redsun-website/commit/948ca4db48a865854fd4f06d4bea1c493860487e which should fix this.
