### ISSUE TITLE
Gifted key cant be used to unbox it

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#318]
Related to issue #306 (not sure if it also have anything to do with issue #317), i have 2 spooky key, both gifted. Since gifts force passive items to be disabled while keys don't appear in passive equip page, i'm unable to use those key to unbox crate #3.

Gifted key
![unbox1](https://user-images.githubusercontent.com/33488710/50709967-75753b00-1061-11e9-9af6-84a159aa30b3.jpg)
Passive equip page, keys not here
![unbox2](https://user-images.githubusercontent.com/33488710/50709981-84f48400-1061-11e9-918e-7a61e5501371.jpg)
Tried to unbox it, says i don't have it
![unbox3](https://user-images.githubusercontent.com/33488710/50709992-9473cd00-1061-11e9-9cac-d63b9bf99bf8.jpg)

**Comment by EgocentricPoliceDick** [comment]
*siiiiigh*

**Comment by EgocentricPoliceDick** [comment]
refer to https://github.com/EgocentricPoliceDick/redsun-website/commit/df762813ca15b2c0c64fe797c038d8e52f42a843m
change will go live shortly
