### ISSUE TITLE
Trails that were recently released are missing negative and neutral descriptions

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#32]
All trails from the halloween crate miss the "Only works on Deathrun and Combat Surf" and "Use /trail to hide the trail in first person." descriptions. 

Reporting this because I sometimes see people ask "why can't I see my trail?" outside of these gamemodes, so adding them will clear up any future confusions. Plus consistency is always nice.

**Comment by ramunecarbonated** [comment]
@koopa516 please keep item descriptions consistent

**Comment by ramunecarbonated** [comment]
Fixed, thanks for the report.

In addition I removed the fluff text of some of the new Halloween items that were residing in the "neutral" tag: we got a "vanity" tag for this so if they were to be added back they would be on that specific tag.
