### ISSUE TITLE
Tank Race: giants spawning in hell early on helltower/plr_hightower_event

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#320]
![image](https://user-images.githubusercontent.com/23409983/51082063-6b8cb100-16cd-11e9-9622-276ccd2e1408.png)

for some reason, giants can spawn in hell early on helltower, despite there being no captures of either tank (they were stalled by both teams at the time this happened, active and damageable).

this seemed to happen after both giants in the main area had died, so i don't know if that's possibly related.

**Comment by EgocentricPoliceDick** [comment]
I'm going to assume this is the rare offchance of something going tits up because of the special hell area called by this map which changes spawnpoints after the carts cap instead of calling a win for the capping team
get me some boomer drink, i will look at it

**Comment by FortyTwoFortyTwo** [comment]
Been a while since this bug appeared, and happened before the whole new STT update stuffs.
Either just a one time bug, or already fixed from the update. Though feel free to reopen if that happens again.
