### ISSUE TITLE
The Retired Hermit plays up to 3 different sounds at the same time when used

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#321]
From what I understand, since the sound files for the item are quiet, the code for it tries to play 3 of the same voice line so it sounds louder, but it ends up picking 3 of the possible sounds at random, making it so you can hear 1 (as intended, but it's pretty uncommon), 2 or 3 voice lines at once.

**Comment by EgocentricPoliceDick** [comment]
The code actually attempts to use a flag to change the output volume, which i think has been configured incorrectly.
