### ISSUE TITLE
The Stanley Parable respawn seems to only play one line.

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#322]
While using the stanley parable item i've realised that before it seemed to use multiple voicelines upon respawn such as "I will take a shot everytime you die, please try to not make end up in the hospital", but now it only says "Welcome once again to DIGITAL SPORTS". Is this on purpose or a bug ?

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/EgocentricPoliceDick/Loadout/commit/6fb9b1175032631a171c86219a70c4c20fa46bba

**Comment by EgocentricPoliceDick** [comment]
what a great issue number
not reopening but just saying
