### ISSUE TITLE
Medic swearing does not work as disguised spy

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#323]
When you disguise to let's say a soldier and use the jeer with stupidifier equipped it will play the soldier stupidifier jeer. But if you use the medic swearing call while disguised it will only use the normal voiceline calling medic for the class you are currently disguised as IE: Scout

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/EgocentricPoliceDick/Loadout/commit/14733b7ca42762727f1497c68cada8182404fff3
