### ISSUE TITLE
Loadout: Shop item tryout feature is missing

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#324]
Since The Blood Trials started, you can no longer try out items from the shop. I'm not sure if this is intended or not so I'm putting this out here in case it isn't.

**Comment by oWave** [comment]
Investigating. Send booze, I haven't even looked and already know that this is going to be fun.

**Comment by EgocentricPoliceDick** [comment]
was out when this was opened but i have an idea of what's causing it
