### ISSUE TITLE
VSH Rewrite: if Christian Brutal Sniper gets a kill from bleeding while charging his bow, he'll a-pose until he charges his bow again

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#325]
Title, it's a very specific issue but it has happened a few times. Probably related to being forced to use a different melee weapon on kill.

**Comment by FortyTwoFortyTwo** [comment]
Fixed, CBS active weapon no longer get force switch to melee if holding huntsman (melee weapon change from kill still takes into effect)

https://github.com/EgocentricPoliceDick/VSH-Rewrite/commit/fa24e28111ca2a9e449da5ba62f423b07d430029
