### ISSUE TITLE
Loudness Coin might be interacting incorrectly with other items' custom sounds

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#326]
The effects of the coin only work properly with stock TF2 sounds, but act very differently with custom sounds and it used not to be like this. Since the coin isn't very cheap and doesn't last long, testing attempts were limited so I can't give very detailed info about this issue (though, thanks to MercΩrius for using a couple of coins with his high donator level to help with this), but this is what I could gather:

- Items that only play one sound, or one sound per class (tested with Medic Call: Classic and Idiotizer): they might only be getting amplified client-side, and even then aren't nearly as loud as stock sounds.

- Items that may play more than one sound (tested with Battlecry: Koopa's Rage, Lookout Louis, Retired Hermit): they play multiple sounds at once (same as issue #321), unsure if others can hear overlapping sounds, and get amplified a bit, maybe only client-side as well.

**Comment by FortyTwoFortyTwo** [comment]
Should be fixed for the "amplified client-side", or loud did not take into effect in some situations.
As for the multiple sound played at once, it would take a lot of work to fix where it probably not worth at this point to fix this bug.
https://github.com/EgocentricPoliceDick/Loadout/commit/fbb0cbe05fcd0ba479b4fcef0911a746831d4407
