### ISSUE TITLE
GunGame Redux: Red Sun playerskins don't adapt to class changes

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#328]
Kinda-related issues: #11 #20 #65 #87

For example, if you're a Pyro with the Muscle Power skin, get a kill then become a Heavy, you'll still show up as a Pyro but with a minigun to others. Not sure if this persists through deaths, though.

(this is more related to red sun than gungame itself so I'm putting this here instead of using the tfgungame-redux bug tracker)

**Comment by EgocentricPoliceDick** [comment]
should have just patched this earlier, but i'll turn skins off if it's causing a problem which it seems to be causing
not as though anyone ever plays this mode hahaa
