### ISSUE TITLE
gungame: badge doesn't work

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#329]
The badge "I Won the GunGame" is not being awarded to players that fulfill its requirements, probably because the badge is not configured to work with the gungame rewrite.

**Comment by EgocentricPoliceDick** [comment]
The badge grant code was not added to the plugin code as of yet. This issue will be closed out once a commit adding this functionality does so.

**Comment by FortyTwoFortyTwo** [comment]
Readded in https://github.com/EgocentricPoliceDick/Loadout/commit/06726faec69ebc1093aa08db5757c82b295f009d
