### ISSUE TITLE
VSH: Hale modifier never appears itself at random

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#33]
Ever since Jugador added a command for admins to forcefully set next hale whatever special modifier, it however never appears itself at random.

**Comment by ramunecarbonated** [comment]
Assigning this to @Benoist3012 since he is responsible for the rewrite which will replace our VSH plugin completely (afaik)--

Issue won't be fixed, but is intended to be closed upon release of the new plugin.
