### ISSUE TITLE
vsh: medic still able to gain uber from healing buildings

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#331]
Despite what commit 57396fa from last Thursday states, medics are still able to build uber from buildings (unless it was reverted, which I disagree with because it makes getting uber very easy)

**Comment by FortyTwoFortyTwo** [comment]
Did tried to fix it, but healing sentry seems to have bypassed the uber rate penalty, so im gonna have to find myself another way to fix this

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/EgocentricPoliceDick/VSH-Rewrite/commit/734eb469734dd55677d0f4532210153c7042bc3a
