### ISSUE TITLE
vsh: medic gets no assist/score from healing sentries

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#333]
self-explanatory, medics don't get any assist damage when they are healing a sentry that is dealing damage to the hale

**Comment by EgocentricPoliceDick** [comment]
not necessarily a big per se, more likely a design decision, ask 42

**Comment by FortyTwoFortyTwo** [comment]
Done in https://github.com/EgocentricPoliceDick/VSH-Rewrite/commit/4976d94a95bc683e40f7775ae9062dfee3cb20f4
