### ISSUE TITLE
szf: tide turner turning control stays when picking up chargin targe

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#335]
If you have a tide turner equipped and then pick up a chargin targe, you will still keep the full turning control from the tide turner (the chargin targe is actually equipped on your viewmodel btw).

To reproduce:
1. get a tide turner
2. pick up a chargin targe
3. get results above

Expected behavior: can only charge in straight line with chargin targe according to its attributes

(I was unable to see if other attributes of the shields were still incorrect when this occurred, but the turning control was the most obvious one)

**Comment by FortyTwoFortyTwo** [comment]
Fixed, turns out that only happens in spawnroom where removing shield did not get checked
https://github.com/EgocentricPoliceDick/SZF-private/commit/003dec1aa95132727dee6922549a15f1b700804b
