### ISSUE TITLE
szf: weird interaction with tide turner and other demo secondary pickups

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#336]
(maybe related to #335 )
If you have a tide turner equipped and then pickup a(ny) stickybomb launcher from the map (dunno if it happens to shields as well), and then pickup the tide turner again, the launcher that you picked up won't go back to where it was found will be replaced with a tide turner instead. You will still get the shield, it's just that the launcher will disappear from the map.

To reproduce:
1. have a tide turner from somewhere
2. pickup a(ny) stickybomb launcher (and shields?)
3. pick up the tide turner again
4. get results above

Expected behavior: picking up a tide turner while having a different demo secondary will put the demo secondary back on the ground instead of leaving another tide turner (causing the launcher to disappear from the map)

To clarify, when you pickup the tide turner again, the shield replaces the launcher on you (as intended) but the pickup replacement on the map is incorrect.

**Comment by FortyTwoFortyTwo** [comment]
Fixing issue #335 seems to have also fix this issue itself
