### ISSUE TITLE
Premium Music Kit: Don't Lose Your Way is missing Premium Music Kit functionability

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#337]
Related to issue #278, it's closed but not locked, but it's old so I thought it'd be best to just make a new issue about it.

A while ago, the item got a few changes in the Loadout in preparation to become a premium kit in a future server update, that never happened, however.

Things that were changed: item name, item icon, price in shop (130 BP > 500 BP).
Things that were not changed: item functionability, positive description to fit other premium kits.

**Comment by EgocentricPoliceDick** [comment]
Haven't forgotten about this, this is really just "please change the icon".
If RatX isn't busy I'll ask him to conjure up something to replace the current icon.

This'll stay open until my lazy ass uploads it.

**Comment by FortyTwoFortyTwo** [comment]
Fixed the functionability part of this music kit, while also fixed Hover and Lisa not considered as premium kit.
(very very dumb fix)

**Comment by FortyTwoFortyTwo** [comment]
Updated description to fit with other premium kits
