### ISSUE TITLE
Music Kit: DOOM has Premium Music Kit functionality, but it was never updated in the Loadout

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#338]
Basically the reverse of issue #337, the item received changes in the servers but the Loadout item was never updated.

Things that were changed: item functionability
Things that were not changed: item name, item icon (a new icon for this might not exist at the moment but that's fine), positive description to fit other premium kits.

**Comment by EgocentricPoliceDick** [comment]
At the very most, this is an inconsistency and I've marked it as such. I'll close this out once I've obtained a new icon and updated the info on store.

**Comment by woisalreadytaken** [comment]
I was messaged by bung (who remade the kit's sounds), he told me an icon update for this item was made by bostonJunkie and was sent to Frosty (who was an admin at the time), but nothing was done to it. Here it is:
![image](https://user-images.githubusercontent.com/33163183/56447400-78c5c700-62de-11e9-86ce-8c3f085915dd.png)

**Comment by EgocentricPoliceDick** [comment]
done
