### ISSUE TITLE
Using demopan rage just before round starts causes the rage to be activated permanently

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#339]
So if you rage just before the new round begins as demopan you will see the "trade offers" but it won't go away, it will be stuck on that forever. Unless you alt tab out of the game, it removes itself.
![20190131194811_1](https://user-images.githubusercontent.com/45695904/52077395-35867280-2591-11e9-9486-0d864d2f875c.jpg)

**Comment by FortyTwoFortyTwo** [comment]
Fixed in https://github.com/EgocentricPoliceDick/VSH-Rewrite/commit/e9132481b7372c351dcbb2b656ddb6abfd771f94

**Comment by FortyTwoFortyTwo** [comment]
Nevermind, fix did not work
