### ISSUE TITLE
dodgeball: books sometimes labeled as magnets in the HUD

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#342]
Book rockets are sometimes (~50% of the time according to other players apparently) labeled as magnet rockets in the HUD element that shows the rocket type/speed, even though magnet rockets are no longer a thing and have not been a thing for a long time.

(only the hud element is affected afaik, the book rockets themselves are fine)

**Comment by FortyTwoFortyTwo** [comment]
dont quite see how it a 50/50 while i always get magnet, even when i force all rockets book. Fixed it anyway
https://github.com/EgocentricPoliceDick/Dodgeball/commit/d9d94f275d2cb5e1d424d4897670feb46a3de32c
