### ISSUE TITLE
Crate #8 may give out strange Stardust Congaway instead of possibly Peanut Butter battlecry

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#346]
Stardust Congaway is the only taunt effect that is available in the crate, but the crate's description doesn't specify taunt effects, so I assume this is not intended. Peanut Butter is the only battlecry (besides aaaiiieee and the BC2 ones) that I don't recall seeing any of in strange quality, so there's the possibility that they were swapped accidentally.

**Comment by EgocentricPoliceDick** [comment]
I'm looking into this right now (both the original crate listing and what is marked up in the database) and will get back to you with more information.

**Comment by EgocentricPoliceDick** [comment]
This doesn't seem to be any sort of mistake on our end, I'm going to mark this as closed.
