### ISSUE TITLE
Made In Heaven Title is not in Genuine rarity.

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#348]
Any player that gets the "Made In Heaven" title after the update, should receive it in genuine (as stated on the patch notes), here the title is actually Unique. It is also seen in Genuine Rarity in the chat after map completion despite the fact it's Unique in the loadout.

Proof : 
![broke](https://user-images.githubusercontent.com/45695904/53967945-732d6c80-40f6-11e9-9e99-8fd3dea3e7db.PNG)

**Comment by FortyTwoFortyTwo** [comment]
Fixed for new titles drops, however i can't do anything about converting all existing unique titles into genuine so i'll leave this issue open until someone does that

**Comment by EgocentricPoliceDick** [comment]
fixed entirely, closing
