### ISSUE TITLE
"Featured badges" font problem on "Players currently active" section.

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#349]
I noticed that 4 featured badges in this section have a messed up bold text, supposedly due to the brighting of the rectangle around the badge area. It's less seen on the 3rd screenshot but you can actually understand what i mean on the 1st and 2nd screenshot.

Proof : 
![bug 1](https://user-images.githubusercontent.com/45695904/53972902-fef7c680-40ff-11e9-8ef3-0c87d329331f.PNG)
![bug 2](https://user-images.githubusercontent.com/45695904/53972906-00c18a00-4100-11e9-962d-ed436ef6fbba.PNG)
![bug 3](https://user-images.githubusercontent.com/45695904/53972909-0323e400-4100-11e9-83c1-fcbbbbcbd06d.PNG)
![bug 5](https://user-images.githubusercontent.com/45695904/53973270-bdb3e680-4100-11e9-93cb-8854781f3909.PNG)

Here you can also see the luminosity is higher than on the other badges.

![bug 4](https://user-images.githubusercontent.com/45695904/53973118-6c0b5c00-4100-11e9-8ec5-2b7d3f6bd912.PNG)

**Comment by FortyTwoFortyTwo** [comment]
Updated all badges to remove brightness feature, there isnt really much reason to keep that feature
