### ISSUE TITLE
Research function in loadout seems to be missing keywords

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#353]
**The only one that are affected seems to be specific # 2 crate items**
While trying to search some items, i noticed that the item will only show up with certain specific keywords, here is an example: 

You can see that this item contains the word "Sandwich" and "Lament" but it only seems to detect the former.

![epic](https://user-images.githubusercontent.com/45695904/55078104-a29e1c00-5099-11e9-9369-249451a0b93c.PNG)
![epic2](https://user-images.githubusercontent.com/45695904/55078109-a467df80-5099-11e9-89d7-ff3029a1c458.PNG)

The you're too slow items only show up with the first word

![sonic_LI](https://user-images.githubusercontent.com/45695904/55078538-ad0ce580-509a-11e9-8dba-d32f2269a46e.jpg)
![sonic3](https://user-images.githubusercontent.com/45695904/55078544-b007d600-509a-11e9-9d64-390afc969587.PNG)

**Comment by woisalreadytaken** [comment]
it's not an issue limited to these items, basically the search box disregards everything past apostrophes ('), see #166

**Comment by EgocentricPoliceDick** [comment]
haHAAAAA ESCAPING
FUCK ME

**Comment by oWave** [comment]
Well this was fun to fix.
Hopefully there isn't more of this type.
