### ISSUE TITLE
"Play sound preview" missing on some shop items

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#354]
All of these items are missing a sound preview, unlike code: alpha which does have one.

![preview](https://user-images.githubusercontent.com/45695904/55080147-e3982f80-509d-11e9-9c1e-f6bcfc270ad9.PNG)

Missing previews (Also, i don't know if the Yes/No Thanks and laughter should have one so i didn't highlight them)

![beueueueu_LI](https://user-images.githubusercontent.com/45695904/55080184-fa3e8680-509d-11e9-9d05-8d7a4fbafbfc.jpg)

![bugggggg](https://user-images.githubusercontent.com/45695904/55275595-b2f80600-52e8-11e9-9f65-cde055f37a55.PNG)

**Comment by EgocentricPoliceDick** [comment]
This isn't a bug - it's just that those specific items don't have an uploaded preview file on the web server.
