### ISSUE TITLE
Items on sale on main menu are not clickable

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#356]
On the main menu, when items are on sale, you can't click on them, but when you are in the server shop only then you can actually click on it.

![AAAAAAAAA](https://user-images.githubusercontent.com/45695904/55081330-ed229700-509f-11e9-8642-d57db7a59257.PNG)

**Comment by oWave** [comment]
Currently intentional, since the shop logic is bound to the shop page only.
Only a full rewrite of the shop logic would fix this, which I currently do not plan on doing, but thank you for the report.
