### ISSUE TITLE
Small inconsistency on shop

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#359]
On the server shop sidebar it says "Spawn effect" when it is actually "Respawn effect", nothing much but a little typo.

![aez](https://user-images.githubusercontent.com/45695904/55279632-ebb0d300-531a-11e9-9176-479e6611924e.PNG)

![aezr](https://user-images.githubusercontent.com/45695904/55279633-ed7a9680-531a-11e9-8694-630f37819ae6.PNG)

**Comment by EgocentricPoliceDick** [comment]
just a minor inconsistency, internally it's referred to as a spawn effect but we publically show it as a respawn effect for better understanding.
will put a fix live whenever i forget i have a reason to live

**Comment by Mikusch** [comment]
I've corrected this in various places and will put it live later
