### ISSUE TITLE
Prophunt: player on Props team able to spawn as any class with weapons

### ISSUE THREAD

**Issue by unitgon** [redsunservers/LoadoutBugTracker#366]
(Not a demo of the full round as I joined late.)
[Demo File: unit_2019-04-23_00-46-30.zip](https://github.com/redsunservers/LoadoutBugTracker/files/3105122/unit_2019-04-23_00-46-30.zip)

I don't know the exact method on how the player was able to select Pyro, so more information may be necessary.

**Comment by FortyTwoFortyTwo** [comment]
It said that people got weapons from Gun Mettle weapon drops, while there a very old prophunt bug about props able to play as any class, so able to pickup dropped weapon from hunter team.

I've disabled weapon drops in Prophunt for it

**Comment by FortyTwoFortyTwo** [comment]
Bug still exists, nothing related to the Gun Mettle weapons

**Comment by unitgon** [comment]
Changed title to be more accurate and global

**Comment by unitgon** [comment]
Once more, more accurate. Attached is a demo including a Heavy spawn (second round, player did not intend to kill), and a Soldier spawn (last round, player went on the offense).

Demo file: [unit_2019-05-19_21-51-16.zip](https://github.com/redsunservers/LoadoutBugTracker/files/3195561/unit_2019-05-19_21-51-16.zip)

**Comment by FortyTwoFortyTwo** [comment]
Managed to reproduce it using the latest demo, working on a fix

**Comment by FortyTwoFortyTwo** [comment]
Not sure if i've broke something else during this fix, which case please make a new issue for it.
PH code stinks
