### ISSUE TITLE
vsh: jumper modifier for gentle spy does nothing (beneficial)

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#369]
due to gentle spy's current mechanics/rage, the jumper attribute does nothing beneficial for the boss, should either add functionality to the boss (somehow, without breaking his movestyle) or remove the modifier from the pool for gentle spy only

**Comment by FortyTwoFortyTwo** [comment]
Blutarch & Redmond also need something for Jumper modifier, along with upcoming bosses Announcer & HHH jr

**Comment by FortyTwoFortyTwo** [comment]
Ended up removing modifier, quite a few bosses without super-jump to think about it, while i'm not into adding some kind of a blacklist for bosses with whatever modifiers
