### ISSUE TITLE
Blu Sometimes Appearing as Humans in STT

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#37]
https://i.imgur.com/CZyFTYD.jpg

Not sure what the cause is, I saw an engineer playing as a human as well. Pretty sure this goes away after respawning.

**Comment by ramunecarbonated** [comment]
Will look when I get home.

**Comment by Benoist3012** [comment]
Assigning myself to this too

**Comment by ramunecarbonated** [comment]
Addressed.
