### ISSUE TITLE
Jukebox: Kirby Super Star song not playing

### ISSUE THREAD

**Issue by Drand0r** [redsunservers/LoadoutBugTracker#373]
When trying to play Kirby Super Star song from the jukebox, an Invalid sample rate error appears in the console and no song is played.
![bug](https://user-images.githubusercontent.com/37286193/57019371-32e1fa80-6c1e-11e9-8d86-340ab97ce9f9.PNG)

**Comment by EgocentricPoliceDick** [comment]
hotfix uploaded
