### ISSUE TITLE
szf: tank bug

### ISSUE THREAD

**Issue by drivoeggman** [redsunservers/LoadoutBugTracker#377]
there is a bug with the tank that you can switch classes and be a scout with 3k hp,or even spy but i don't know who would want to be a spy tank.
how to reproduce the bug: stay in spawn as tank and just switch class to scout or spy.

note: it doesen't always work

**Comment by FortyTwoFortyTwo** [comment]
late on reporting bug, but already fixed and in servers from commit `3b1856d`
