### ISSUE TITLE
Unusual Adachi skin still shows particles when invisible as Gentlespy.

### ISSUE THREAD

**Issue by Waifers** [redsunservers/LoadoutBugTracker#380]
reposted from https://github.com/redsunservers/VSH-Rewrite-Configs/issues/34 at request.

Expected interaction: When you have an Unusual Adachi skin equipped when you play Gentlespy, whenever you use the cloak, the unusual particles should go away until you become visible again.

Actual interaction: Unusual particles stay around Gentlespy whenever he cloaks, which gives away his position which should never be the case.

**Comment by ahamudo** [comment]
I can confirm that this happened to me, but it's a slightly different case: before becoming Gentle, I was an Engineer using a Haunted Glow Sentry Specialist skin, yet, despite me being a different class, the effect remained, thus leading to me being exposed when cloaked.

**Comment by FortyTwoFortyTwo** [comment]
Particles not even meant to be enabled if skins is disabled for said team, so i've fixed that.
Particles still show during cloak also happens outside of VSH, so i've also fixed that.
