### ISSUE TITLE
szf: spawning with 1/2 hp when tank spawns

### ISSUE THREAD

**Issue by drivoeggman** [redsunservers/LoadoutBugTracker#383]
so sometimes when a tank spawns in you just instantly respawn and have 1 or 2 hp AND you respawn near survivors.
i do not know what causes this yet

**Comment by itVictor** [comment]
I had this issue a while ago but I wasn't near survivors and I think it was a normal respawn, might be related to spawning at the exact same time a tank spawns.

**Comment by FortyTwoFortyTwo** [comment]
Found myself part of the code that likely seems to be causing this, but i've no clue the point of those stuff so i just removed that.
8 years old plugin i guess.
