### ISSUE TITLE
VSH: players sometimes don't spawn with weapons

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#388]
this seems to happen at random in normal gameplay, although on special rounds it becomes a bit more apparent with lots of players not spawning with weapons at all

![image](https://user-images.githubusercontent.com/23409983/59716800-aa76e380-91e4-11e9-9adf-0e97c71b1c47.png)

no clue as to why this happens

**Comment by StamatisP** [comment]
It happens especially when your class is forcibly changed. I saw it happen during the special round with all spies, and when you revive as a zombie scout. I have a demo, if you need it.
