### ISSUE TITLE
Donator/Flowey name icon can sometimes appear if loadout connection problem, even if don't have said icons

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#389]
![donator](https://user-images.githubusercontent.com/33488710/59792239-9b1e9580-92cb-11e9-8f96-6b43554a7a90.png)
Discord is full of faggots btw

**Comment by EgocentricPoliceDick** [comment]
Known problem, although iirc this is a regression from an earlier version of the chat plugin
