### ISSUE TITLE
cw: arena_bellick_b1 bug

### ISSUE THREAD

**Issue by drivoeggman** [redsunservers/LoadoutBugTracker#392]
on arena_bellick_b1 you can jump into pits that are supposed to kill you but they don't 
![20190623180220_1](https://user-images.githubusercontent.com/51297399/59978876-518ebd00-95e1-11e9-802a-3613712035a5.jpg)

**Comment by FortyTwoFortyTwo** [comment]
Can't really find myself a simple way to fix this without needing to recompile etc, removed map in rotation.
