### ISSUE TITLE
maplist: flag pd_watergate with disable Inverted Space Coin

### ISSUE THREAD

**Issue by unitgon** [redsunservers/LoadoutBugTracker#393]
Long story short, it becomes real difficult to jump into the beam with high gravity.

**Comment by FortyTwoFortyTwo** [comment]
Done, both Raiden and Armstrong

**Comment by unitgon** [comment]
@FortyTwoFortyTwo what do you feel about making this some sort of megathread for map flag suggestions?

Any way here's one more, and I'll copypaste it to a new issue if that's better.

* `arena_random_brick_a2`: add no-inverted-space flag, player is often not able to traverse very far without jumps because of the randomized map

**Comment by FortyTwoFortyTwo** [comment]
Preferred to make new thread with one big list, so i can work with all at once rather than doing once every so on.
Anyway, disabled inverted-space for said map
