### ISSUE TITLE
Bounce coin on randomizer causes engineer to spam same voiceline after each jump

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#395]
Pretty much what the title says, engineer won't stop spamming the same voice line once the bounce coin is activated and then he jumps everytime. (don't know if its randomizer only)

EDIT: Ok so it's for all classes actually

**Comment by woisalreadytaken** [comment]
this isn't really a bug, bouncing triggers the 'positive' voice command, and the Engineer only has one line for it. Other classes mostly chuckle, but they have more than one voiceline each.

**Comment by FortyTwoFortyTwo** [comment]
Plugin does indeed force players use positive (C + 5) voiceines, where valve gave Engineer only 1 voiceline to use. We could instead create list of voicelines outside of C + 5 to pick at random, but i don't see myself worth doing it when problem is just a sound effect only for 1 class
