### ISSUE TITLE
Loadout: Collector's Music Kits only receive "general" strange trackers

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#396]
This is likely not intended as this used to happen with collector's über music items instead of tracking übers but it was patched a while ago, while music kits were left untouched (rather than tracking Dodgeball-related stuff).

By general, I mean the Kills, Wins and Minutes Played stat trackers.

Example:

![comparison](https://user-images.githubusercontent.com/33163183/60531839-4408bf80-9cd2-11e9-9388-1922e11d452e.png)

**Comment by oWave** [comment]
This is just a note for me because I'm busy with exams:
DB Kits should only receive db strange types (id 4,5,6)

**Comment by Mikusch** [comment]
Collector's music kits will now correctly get "Dodgeball Kills", "Dodgeball Wins" and "Music Kit Plays" types again.
All existing bugged music kits had their strange type adjusted, and their score reset.
