### ISSUE TITLE
Instant death on boundary_final1 at 2nd checkpoint [STT]

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#397]
Near the second checkpoint of the map, if you are close enough to the tank (whatever your place) you will be instakilled. We were behind the tank and some a bit behind and they still got killed.

**Comment by FortyTwoFortyTwo** [comment]
That area is quite small/crowded, so of course kills from tank is to be expected there.
But even then, tried to get myself killed in the narrow upward tunnel, but couldn't do it. Not much i can say about this.
