### ISSUE TITLE
Death: Good Night! using wrong description(?)

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#4]
<img width="296" alt="screen shot 2017-10-31 at 8 40 07 pm" src="https://user-images.githubusercontent.com/20176719/32256223-d19c10b8-be7b-11e7-9c92-955f4d2cd202.png">

I'm assuming that "Time's up Luigi" should be a neutral description instead of negative, at least if you want to maintain consistency with other items

**Comment by koopa516** [comment]
was originally intentional but if consistency matters that much then consider it fixed
