### ISSUE TITLE
"Sentry Buster Contract" Not Working As Intended/Misleading Description 

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#40]
First time I was a sentry buster, I walked over to spawn, killed a person and a teleporter and dispenser, which should have been 3 points. The contract only went up by 1.
Second time, walked up to an engineer with all his buildings, (including both teleporters) and killed him along with all of his buildings. This should have been 5 points. Contract only went up by 1 again, now at 2/4.
The third time, I missed the engie and his sentry and only managed to get his dispenser and teleporter, which should have been 2 points. The contract didn't even go up this time, and remained at 2/4.
Building destruction and player kills should all be 1 point a piece, according to https://wiki.teamfortress.com/wiki/Scoreboard#Points , yet it seems to only count player/sentry kills, or is capped at one point per life or something, baring in mind the description is to score 4 points as a sentry buster.

**Comment by CountSexulus** [comment]
Update: It's people that count towards the contract. So basically the contract is get 4 kills as a sentry buster, rather than just points

**Comment by koopa516** [comment]
will look into asap

**Comment by ramunecarbonated** [comment]
This is because STT doesn't credit the Sentry Buster for killing buildings in the plugin, so it is safe to assume that this behaviour was intended. As such I have corrected the text on the contract.
