### ISSUE TITLE
VSH: Announcer's gun may not swap a target's team

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#400]
In some cases, the weapon from Announcer's rage doesn't change a player's team, but deals damage as if it wasn't modified. It's possible that this only happens with overhealed players, but can't tell for sure.

**Comment by FortyTwoFortyTwo** [comment]
Fixed, full detailed on this bug:
There a stock that checks whenever if you are ubercharged or not by conds, including `TFCond_UberchargeFading` which is given when still "ubered" but about to expire.

However medigun's area of range acts weird when giving uber. Entering in and out of range can sometimes give permanent `TFCond_UberchargeFading` cond, even when actually not ubered.

I could fix by force removing said cond, but a lot of situations can break or ends up with a messy code, so i simply just remove the check on bugged uber cond.

This fix should also fix the shield not breaking, and scare rage not working on some people even when right in-front of it.

Thanks to wo and Likveh for testing to find this big hidden bug.
