### ISSUE TITLE
Song missing from Armstrong's jukebox

### ISSUE THREAD

**Issue by Zane-Truesdale** [redsunservers/LoadoutBugTracker#404]
It appears the song **Kings and Folk - Country Rounds** is not present in the jukebox list on Armstrong. Every other server has it but it is absent there.
Some pics to compare. Top: Armstrong. Bottom: Raiden.
![Armstrong](https://user-images.githubusercontent.com/45983028/61671150-4b5d3080-acb4-11e9-9bad-50097acc995a.jpg)
![Raiden](https://user-images.githubusercontent.com/45983028/61671158-51531180-acb4-11e9-8cdc-cf434214b0c6.jpg)

**Comment by FortyTwoFortyTwo** [comment]
Fixed

**Comment by Zane-Truesdale** [comment]
Thanks mate
