### ISSUE TITLE
/spoiler command not functioning correctly

### ISSUE THREAD

**Issue by tacticturt** [redsunservers/LoadoutBugTracker#411]
Firstly, using saysounds and greentext (starting a message with >) is now possible while also using a spoiler tag. This will change the colour of the text (as expected) but remove the spoiler colour (leading me to believe it's unintentional..?)

secondly and more importantly if you do use a greentext or saysound while using a spoiler tag all future spoiler- tagged messages will appear in the same colour you would expect from using a saysound/greentext, regardless of whether or not the player is actually using one.

![spoilergreen](https://user-images.githubusercontent.com/37385016/62788591-255ecb00-babf-11e9-8576-d91bc774a132.PNG)

![spoilersaysound](https://user-images.githubusercontent.com/37385016/62788598-298ae880-babf-11e9-8518-121d8f5e0665.PNG)

![spoilersaysound2](https://user-images.githubusercontent.com/37385016/62788952-db2a1980-babf-11e9-9c15-ab0d4bb53a4b.PNG)

**Comment by haxtonsale** [comment]
Should be fixed now, thanks for the report
