### ISSUE TITLE
Prophunt: Flame Thrower sometimes does 10 dmg/tick

### ISSUE THREAD

**Issue by unitgon** [redsunservers/LoadoutBugTracker#413]
Flame Thrower sometimes does 10 damage/tick, aka a thousand million billion damage per second.

POV demo on PH Campsite.
[unit_2019-08-12_17-04-54.dem.gz](https://github.com/redsunservers/LoadoutBugTracker/files/3493146/unit_2019-08-12_17-04-54.dem.gz)

**Comment by FortyTwoFortyTwo** [comment]
Fixed, it's because prophunt config is outdated without Tough Break update weapons, so i've updated to latest version and manually uploaded to all servers.

Tough Break is back in late 2015, how have we not found this till now.
