### ISSUE TITLE
Versus Saxton Hale: Bugged spawn model

### ISSUE THREAD

**Issue by JUSTMagic-re** [redsunservers/LoadoutBugTracker#419]
It was a round all scouts vs double boss and i spawned with a bugged hud (demo holding the eyelander) and without weapons

**Comment by FortyTwoFortyTwo** [comment]
I suspect same issue #388 returned/not fixed

**Comment by FortyTwoFortyTwo** [comment]
Do you remember when this bug happened, **everyone** spawned with bugged loadout/hud, or just yourself? If everyone, bug is already fixed
