### ISSUE TITLE
MicroTF2: Clear Microrun badge bug

### ISSUE THREAD

**Issue by karlwantstodie** [redsunservers/LoadoutBugTracker#423]
I got the clear microrun badge while i lost a lot of microgames and was last (Yes i was there at the start of the round).

**Comment by FortyTwoFortyTwo** [comment]
Did you lose every single singe microgames, or was there special round during it? Also by mean "last", you meant you had the lowest score?

**Comment by karlwantstodie** [comment]
No, i lost only a couple of rounds which meant i had the lowest score and was last. Also there was no special round iirc.

**Comment by FortyTwoFortyTwo** [comment]
Heaven't touched badges code for a while, but also havent heard from anyone else on this bug, not sure what happened to this
