### ISSUE TITLE
GunGame: Weapons are missing from a few rotations

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#43]
The rotation that has the grenade launcher as rank 1 is missing the minigun at rank 5 and I'm not sure what weapon at rank 6 (class however was Pyro), the players at the server RPS'd through these and after that, weapons were being given out as intended.

The rotation that has the rocket launcher as rank 1 is missing a weapon at rank 8 (don't know which weapon, class was Heavy), RPS'd through and everything else was fine. The minigun is also in this rotation, but it worked fine.

Didn't have the time to check for other weapon rotations.

Related to GunGame: random crits are enabled, I heard they're supposed to be disabled.

**Comment by ramunecarbonated** [comment]
Okay, so I have added a TF2items-based fallback, intended for the weapons that are currently not working. Fix should be out when we actually push the stuff, so I will close this ticket. Thank you so much for reporting these by the way.
