### ISSUE TITLE
gungame: set tfgg_spawnprotect_length convar to a reasonable number

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#430]
per the gungame documentation: 

`tfgg_spawnprotect_length` sets `Length of the spawn protection for players, set to 0.0 to disable and -1.0 for infinite length`

this is set to -1 on redsun so players can be invulnerable forever if they don't move

**Comment by FortyTwoFortyTwo** [comment]
Set ConVar to 0.5 seconds
