### ISSUE TITLE
Bombermod: eyeballs get stuck when they spawn inside candy

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#432]
~~the eyeball spawns on this map are kinda fucked, they can get stuck in the ground/wall meaning that they can't move (either all or some of them get stuck)~~

~~happened when they spawned in the outer corner of the map~~

**Comment by woisalreadytaken** [comment]
This didn't happen because of the map, this happened because eyeballs spawned inside a piece of candy

**Comment by FortyTwoFortyTwo** [comment]
Fixed by @Alex-Turtle, ghosts can now destroy powerups
