### ISSUE TITLE
SZF: Sandman's max health reduction makes Scouts almost unable to rage

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#44]
Scout's health will be capped at 110 but the plugin hp regen will still overheal to 125 (while decaying back to 110), it's still possible to rage if Scouts call for medic at the tick they're at 125 hp.

**Comment by ramunecarbonated** [comment]
Rage is now (current health * 1.5) instead of (max health * 1.5) and can now be used on any percentage of health.
Fix should be out when we actually push the stuff, so I will close this ticket. Thank you so much for reporting these by the way.
