### ISSUE TITLE
Combat Surf: End zones sometimes don't load in GMM servers

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#441]
Unfortunately the cause is unknown, and it happens often but not all the time. As the title implies, this only happens in Raiden and Armstrong, but works fine in Ocelot.

**Comment by FortyTwoFortyTwo** [comment]
I assume it because of surf zones config does not exist for some maps in raiden/armstrong, but ocelot only

**Comment by FortyTwoFortyTwo** [comment]
Copied all configs from Ocelot to Raiden and Armstrong

**Comment by ScrewdriverHyena** [comment]
the assumption is incorrect, I have had to remake zones before
