### ISSUE TITLE
Windows 95 and DFS logo image much larger than expected

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#442]
Windows 95 Screenshot and bug found by Zane. Image resolution is 550x550, while all resolutions should be 128x128
![windows95](https://user-images.githubusercontent.com/33488710/70231927-33fa7d80-1753-11ea-876c-3e8f1581fbb1.png)

Somewhat similar issue to DFS logo aswell, larger than other Affliates and Providers logos.
![providers](https://user-images.githubusercontent.com/33488710/70232105-95bae780-1753-11ea-9c1c-c9540735c8f4.png)

**Comment by EgocentricPoliceDick** [comment]
item image for windows98 spray has been applied, please allow time for cdn to grab newer source image
as for dfs image that is externally hosted, i will need to locally host that and resize

**Comment by woisalreadytaken** [comment]
this is a closed issue but it's worth mentioning that this happens with the Pimp's Play icon as well

**Comment by EgocentricPoliceDick** [comment]
fixed listed items, please let cdn update to accomodate changes
