### ISSUE TITLE
Loadout: equip page should order items better

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#444]
on the equip page the ordering for items is a big mess, I'd like to suggest ordering by item (so same items of different quality are grouped together), then date obtained (or quality)

goes for the ones that require a slot and the passive items

**Comment by Mikusch** [comment]
Items on https://redsun.tf/equip will now be ordered by title, quality, strange type, unusual effect and acquisition date, in that order. This applies to slot items, passive items and even crate keys.

You likely won't notice much of a difference on slot items unless you own several duplicate strange or collector's, though.

Will close this issue later once I've uploaded it to live.
