### ISSUE TITLE
Unable to turn in completed contract

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#448]
fucking stupid numpad enter

completed a gungame contract, but it refuses to let me turn it in, saying i don't have any finished
![image](https://user-images.githubusercontent.com/23409983/71503881-b18a4880-283c-11ea-841b-08cc6c1551f3.png)

this happens even after refreshing contracts, reloading loadout, and rejoining
have no clue what to do about this

**Comment by FortyTwoFortyTwo** [comment]
I believe it because your contract could not be marked as completed during when there less than 10 players in server, i've made a fix for it but not live in servers yet. See if you can load your contracts when there more than 10 players, and close this issue if so

**Comment by infinitephantasm** [comment]
seems to have resolved after that, closing
