### ISSUE TITLE
Loadout server stats don't appear to be updating after maintenance

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#452]
![image](https://user-images.githubusercontent.com/23409983/73978306-af161680-48f1-11ea-9eb7-aa96bf9263f8.png)

for some reason, server player counts and maps don't seem to be updating. at the time of writing, raiden is on ph_timbertown_a3 with a playercount of 12, armstrong is on szf_skyrim_v6a, mistral is on szf_cityhunter_b3_jugfix2, and ocelot is on surf_legendary_lite_fix_v3. ocelot lines up but the rest are incorrect.

perhaps something wrong happened over the unexpected maint?

**Comment by EgocentricPoliceDick** [comment]
Manually ran the tasks through ssh, seems to run fine. If it's still happening then it may be an issue with the cron scheduler itself, which should be an easy fix.

**Comment by EgocentricPoliceDick** [comment]
web service didn't have cron scheduler on as i thought, has been resolved.
