### ISSUE TITLE
Tidus Experience does not play when either baby coin is in effect.

### ISSUE THREAD

**Issue by Zane-Truesdale** [redsunservers/LoadoutBugTracker#454]
Title. When a baby coin is in effect, it plays the stock Schadenfreude sound instead of the Tidus laugh.
I have a video showing this, but GitHub's 10MB upload limit is gay so I can't attach it

**Comment by FortyTwoFortyTwo** [comment]
I think it best for this bug to be fixed in whole items rewrite (haven't touched for a while), otherwise it wont be nice to fix with current code

**Comment by FortyTwoFortyTwo** [comment]
Seems to have fixed itself, likely from items rewrite.

**Comment by Zane-Truesdale** [comment]
Just tested this on Raiden and it appears to be still present.
