### ISSUE TITLE
Dodgeball: Challenge Coins causing permanent challenge rounds

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#455]
upon using a challenge coin ingame, the user will be stuck in a case where they will always be on the enemy side, while everyone else is on the other side. this should obviously not be the case and reset after they first die.

despite this, the badge does not seem to be attainable after dying the first time.

unsure if this affects raiden, but this is occuring on armstrong and persisted through a map change

**Comment by FortyTwoFortyTwo** [comment]
Very likely because of dodgeball using old stats system which threw errors, causing other errors to popup (challenge coins, dodgeball kit not played).

I've updated dodgeball (and all other plugins) to use new stats system
