### ISSUE TITLE
Dodgeball: Rockets reflected once not doing instant-kill damage

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#456]
rockets that only get reflected once have recently not been doing that much damage. they tend to do around 1xx damage, but never enough actually kill the player you hit with it.

i'm not sure what's causing this behavior as of recent

**Comment by FortyTwoFortyTwo** [comment]
Seems like rocket damage works fine until some time the damages then get changed, I imagine one of the gamemode or map cause tf2 convar to change and not get reset, affecting rest of gamemodes including dodgeball.

Just need to find when it happened

**Comment by infinitephantasm** [comment]
bug is still occurring, happened today on raiden

**Comment by FortyTwoFortyTwo** [comment]
Looked at raiden logs and went though some maps recently played, still couldn't find one causing this bug. I have 6 maps that were recently played and somewhat recently added/updated from rotation.
```
arena_vessel
dr_wastelabs
games_minecraft
mg_testing_complex
tfdb_bustle
warioware_redux
```

Going to wait until server restart to see this bug happening again, hopefully the list will be smaller this time to track it.

**Comment by infinitephantasm** [comment]
i haven't seen this issue in several months afaik, so i'm just gonna close this for now
