### ISSUE TITLE
The Grandfather skin glitches out when using Taunt: The Victory Lap

### ISSUE THREAD

**Issue by PixelatedPyro** [redsunservers/LoadoutBugTracker#459]
As i said in the title, it glitches out. The cart turns around very quick, model doesn't hold the steering wheel. I think it should be looked into.
I made a screenshot, im gonna upload it after a bit because my PC is shit and can't do it now.

**Comment by PixelatedPyro** [comment]
![image](https://user-images.githubusercontent.com/59366255/86284670-9598a280-bbe3-11ea-8fef-26987cc3d04b.png)
The way it was glitched occured on VSH and Ballon Race. After that it remained like it shows in the screenshot

**Comment by woisalreadytaken** [comment]
I don't know what you mean by it turning around very quick, but some taunt objects being in the wrong position are also an issue with the aperture skins (for the victory lap specifically, left arms aren't animated correctly)
![image](https://user-images.githubusercontent.com/33163183/86306618-22932a00-bbeb-11ea-965e-6ff1b4cb29ba.png)

**Comment by KirillianAmu** [comment]
i'll fix it if i'll have the time

**Comment by Mikusch** [comment]
I've added the fixed models by @KirillianAmu
