### ISSUE TITLE
pd_sfoth_a6 (Sword Fight on the Heights) doesn't spawn powerups

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#460]
here's an issue i knew about for a while but didn't bother reporting for some reason

the map has powerup spawns across the map, however they don't seem to spawn at all (it makes sense, considering the grapple hook).

according to the map description on TF2Maps, it requires `tf_powerup_mode 1` to be active in order to spawn them. maybe this can be changed to 1 on this map, and changed back to 0 on other maps?

**Comment by Mikusch** [comment]
Apparently someone bothered enough to enable grappling hooks but not enough to enable powerups. Fixed.
