### ISSUE TITLE
Combat Surf: end zones broken/disabled entirely, regardless of easy mode setting (?)

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#461]
how is this not in bugtracker already

end zones do not work on any server. assuming from info i've gathered, after the easy mode toggle addition (lowering gravity and disabling end zones for the user), end zones are currently disabled for any player, regardless of if they have easy mode on or not. no badges, no rewards, no surf clears occur. this happens on both gamemode madness servers and the main surf server, from what i can tell. 

EDIT: just for reference, this is unrelated to issue #441

**Comment by woisalreadytaken** [comment]
easy mode doesn't disable end zones, it still lets people finish the map with very limited rewards

it is related to #441 but apparently more broke recently, i easy mode probably doesn't have anything to do with this

**Comment by infinitephantasm** [comment]
hm, alright

mostly did some backlogging and recent discuss in #redsun-chat in the discord, so it seemed like that was the issue
will close issue, then
