### ISSUE TITLE
More descriptive messages in chat about coin usage (when coin is not available)

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#462]
Currently, the chat messages about using coins while they're on cooldown are not very descriptive. I think it would be beneficial to specifically include the cooldown in the message. eg "You must wait xx seconds before using this coin."

In addition the wording could be better in cases where the coin is already in use or not available (disabled) for the current map/rotation. eg "This coin is already in use! Please wait xx seconds before trying again." or "The effects of this coin are not available on this map/gamemode."

**Comment by FortyTwoFortyTwo** [comment]
done
