### ISSUE TITLE
Servers: two new items may not be working

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#463]
Death: Bud Lightbeer uses an invalid sample rate and does not play, Console reads:

> *** Invalid sample rate (32000) for sound 'redsun\items\death\607.mp3'.

As usual with these, here's a quick fix: https://cdn.discordapp.com/attachments/332809334339665930/765121143648157696/607_fix.mp3

BP Find: Bloodpoints may also not play anything, I don't have the item but somebody who does noticed this, and I can't find the files for it locally so they may not have been uploaded to the servers.

**Comment by Mikusch** [comment]
I'll upload the fix later, thanks for that. I can't see why Bloodpoints would fail to download, as the files are present in the FastDL. Will need to take a closer look.

**Comment by Mikusch** [comment]
All done. BP Find sounds are still using the old system so it was really easy to miss, we will definitely need to update that.
