### ISSUE TITLE
Chat: When sending a message, it might not send in the chat and you can't send the same message again

### ISSUE THREAD

**Issue by NextinMono** [redsunservers/LoadoutBugTracker#464]
It's hard to reproduce but:
Try to say either a voice line or a message soon after someone else says something, and it'll not send the message in the chat, but when you try to do it again, it'll say you can't send it again because you already sent the same message.

EDIT: Also it happens more with voicelines compared to normal messages but it still happens with messages sometimes

**Comment by FortyTwoFortyTwo** [comment]
Fixed
