### ISSUE TITLE
'madlad' jukebox is constantly redownloaded on every connection/map change

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#465]
anytime you connect to the server, or the map changes while still connected, the 'madlad' set of jukebox mp3s will redownload. this has occurred even after deleting the files and letting them redownload again fully. before deletion, the .mp3s were there, but so were the .bz2s. now, it just doesn't even appear in the folder at all.

![image](https://user-images.githubusercontent.com/23409983/105540395-c1809000-5cbb-11eb-8451-2425c638dbef.png)

**Comment by FortyTwoFortyTwo** [comment]
fixed
