### ISSUE TITLE
/nextmap or !nextmap does not trigger the correct nextmap

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#466]
occurring on raiden as of recent
when using `/nextmap` or `!nextmap`, instead of showing the custom nextmap that shows the map name and its gamemode in orange + green text (`sm_nextmap`), you are instead shown the more basic version that i'm pretty sure comes with sourcemod default plugins (`nextmap`), and also doesn't change upon changelevel (e.g. if prophunt was voted for, and the map changes to prophunt, it will still show the next map as the prophunt map voted for)
![image](https://user-images.githubusercontent.com/23409983/105873028-ab771600-5fc0-11eb-9037-b7564881e197.png)

i'm assuming this is due to the recent reinstallation across all servers (although i don't know if this has affected others) of sourcemod as a result of crashes and lag issues that occurred yesterday

**Comment by Mikusch** [comment]
Yeah, some default SM plugin is overriding the command. Should be an easy fix, I'll do it when I get home.

**Comment by Mikusch** [comment]
It's fixed, will need a server restart though since the command is now registered and can't be overridden.
