### ISSUE TITLE
Gifting: popup doesn't go away

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#47]
When gifting an item, the gift window doesn't go away when you do "confirm gift", the buttons are just grayed out. You can click outside the window to make it disappear, but the gift/delete items remained grayed out when you click an item. Refreshing the page fixes it.

**Comment by ramunecarbonated** [comment]
Does the gifting process still finish?

**Comment by itVictor** [comment]
yes, when I closed out of the window the item I gifted was still there/selected, but refreshing made the item disappear. I can confirm the recipient got the item.

**Comment by ramunecarbonated** [comment]
I tried to address this by streamlining the gifting code, not sure if it works since I could not reproduce your bug at all.

**Comment by itVictor** [comment]
Just tested it and it is not fixed, unfortunately.

**Comment by ramunecarbonated** [comment]
forgot to upload the files lmao
