### ISSUE TITLE
Combat Surf/Ocelot: Instant respawn not functional

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#470]
if you die, instead of respawning instantly like usual, it takes more than a few seconds to actually respawn. this is occurring on ocelot at the moment, but i'm unsure if it's actually affecting other servers.

**Comment by FortyTwoFortyTwo** [comment]
Accidently deleted one of the needed file when cleaning up stuffs in ocelot, fixed it
