### ISSUE TITLE
Smash Fortress: Plugin not loading

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#472]
@ around 1:35PM today on raiden, smash fortress was selected (on the map Skyscraper if it matters), but the plugin didn't load, so the map was basically just arena with no capture point.

i was told by Sylvii that apparently it also happened earlier this morning, but i wasn't around for that so i can't confirm

**Comment by FortyTwoFortyTwo** [comment]
Latest version of smash plugin wasn't uploaded properly, fixed
