### ISSUE TITLE
Team Color Unusuals Visible Through Disquise

### ISSUE THREAD

**Issue by gaidaBG** [redsunservers/LoadoutBugTracker#473]
the tittle says it,team colored unusual effects dont change color or dissapear when a spy disquises,basically making the spy even more obviouse then before

**Comment by FortyTwoFortyTwo** [comment]
Unusual effect shouldn't really show when disguised, could even show disguised target's unusual effect instead but probably not worth it

**Comment by FortyTwoFortyTwo** [comment]
done
