### ISSUE TITLE
Loadout: Items not being automatically refreshed in-browser, and not being automatically reloaded in-game

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#474]
normally, when changing an item in the loadout, the page quickly shows a UI window signifying you've equipped the item, and changes the loadout to suit. however, currently, this seems to do absolutely nothing, resulting in you equipping the item, it not being shown, and requiring you to reload the page in order to see the resulting effects.

![issue](https://5key.is-fi.re/3ZUyHY2.gif)

this also seems to be affected in-game as well, as despite me equipping items, the server doesn't seem to actually notice and requires me to reload manually using the /reload command to actually allow my items to reflect the change.

![issue](https://5key.is-fi.re/4hwdHcQ.gif)

**Comment by Mikusch** [comment]
This issue only happened on Ocelot due to outdated server configs. Fixed.

**Comment by infinitephantasm** [comment]
issue has returned, this time on raiden

**Comment by Mikusch** [comment]
Fixed
