### ISSUE TITLE
Combat Surf: Surf completions being tracked regardless of cooldown

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#475]
when entering a completion zone on a surf map, regardless of a message not appearing saying you've completed a map, the stat will still be added to, leaving me to believe that the cooldown isn't being used stat-wise.

my surf completions @ 15:18:10
![image](https://user-images.githubusercontent.com/23409983/127390684-3f64e944-a1df-4b59-a885-312d7e4d11cb.png)

a few minutes later @ 15:22:09, after mindlessly walking back & forth into the endzone of surf_meister several times
![image](https://user-images.githubusercontent.com/23409983/127390695-e19a7083-9067-48b3-95f0-d1e08a76094a.png)

this can be used to grind out the surf mastery badges very easily depending on a map and its ability to enter the end zone. not exactly an important/vital issue, but still

**Comment by FortyTwoFortyTwo** [comment]
Fixed
