### ISSUE TITLE
Server/Bans: Server kicks player with Gameplay ban after map change under server ban disconnect message

### ISSUE THREAD

**Issue by JanKonesCZ** [redsunservers/LoadoutBugTracker#476]
Happened at RAIDEN before 19:30 when map changed from granary to pass_district, happened yesterday with different maps but i dont think map change is what affects it

First time in the day joined server when granary was on, afterwards map change to district where i was connected for minute and after loadout loaded for me, the server kicked me under the server ban record message while im only gameplay banned

Only affects raiden, ignores other servers
Current gameplay ban was applied through website

**Comment by FortyTwoFortyTwo** [comment]
Fix bug that any bans was treated as server ban, give servers some time to update to let you able to join again
