### ISSUE TITLE
General: Thriller taunt appearing way too often

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#477]
before health packs were changed back to normal via the removing of a plugin, and adding another, the thriller taunt would basically never appear. however, some time after this, the taunt now appears basically every single time you taunt regularly, unless it's like, a tauntkill. i don't know if this original plugin used to control/prevent it from happening, or if the No Thriller Taunt plugin's gamedata suddenly isn't correct but it's now occurring far too often, when it probably shouldn't be happening at all

**Comment by Mikusch** [comment]
My best guess is that the gamedata is outdated, I will take a look

**Comment by FortyTwoFortyTwo** [comment]
Mikusch fixed it ~3 weeks ago by reverting the change back to what it was
