### ISSUE TITLE
Loadout: some newer badge descriptions tend to be inconsistent with older ones

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#478]
This is a minor issue and should be low priority, it's just text!

Older badges always mention either the gamemode or map it's available in, but badges for some (relatively) newer gamemodes don't.

The badges for the following gamemodes have this issue:
- MvM
- SCP
- TF:GO
- specifically the Your Eternal Demise badge, that came with VSH Rewrite

**Comment by FortyTwoFortyTwo** [comment]
Done
