### ISSUE TITLE
Featured badge still doesn't use the color filter / doesn't update correctly

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#48]
I know I reported this several times in the past but it still isn't fixed and it triggers my autism.

As the title says, featured badges still don't use the color filter, it just shows the default color for the first badge of that kind (eg any hale badge would show the color normally reserved for Hale's Own).

On a semi-related note, featured badges do not update when you obtain a badge of the same rarity (eg rare -> rare), even though it used to be that way when featured badges were first introduced.

I know these issues might mean nothing with the new loadout coming soon but I'm reporting them anyways.

**Comment by ramunecarbonated** [comment]
To be fixed with the new Loadout.

**Comment by ramunecarbonated** [comment]
whatever i fixed it for you baby
