### ISSUE TITLE
Ocelot: Loadout/Red Sun server plugins entirely unloaded/non-existent

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#482]
ocelot issue #27920

almost nothing is loaded except for the barebones minimum (bhop, hop (as in server hop), a few other random plugins/commands)

it works for doing surf, but for now that's really about it lol

**Comment by FortyTwoFortyTwo** [comment]
I noticed errors in logs similar to when I broke Raiden and other servers 6 days ago, but apparently Ocelot doesn't have automictic server restart for fixes to apply. Manually restarting server fixes it.

**Comment by HeatRiser** [comment]
readded daily restart task to Ocelot, no idea why I didn't spot it before
