### ISSUE TITLE
Using Dodgeball Challenge Coin does nothing

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#485]
It's announced in chat that coin is used, but no gameplay was changed next round

**Comment by FortyTwoFortyTwo** [comment]
Not sure if I fixed it properly, need a test with actual players to see if it works

**Comment by FortyTwoFortyTwo** [comment]
it does work now

**Comment by woisalreadytaken** [comment]
looks like this is still a thing

**Comment by FortyTwoFortyTwo** [comment]
FIX
