### ISSUE TITLE
Dodgeball: Premium Music Kit functionality is partially missing

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#487]
(ty ahamudo for helping with testing)

Checked in both servers with a variety of music kits, preround sounds don't play and rare win sounds never seem to be chosen. The sound for dying to nukes works, though.

**Comment by FortyTwoFortyTwo** [comment]
Fixed presound music kit not playing, might infact be related to issue #485 

As for rare win sound, it works fine, just have 1 in a 7 chance to appear. Though it may depend on which music kit item though, as some have multiple sounds to select or some premium kits don't even have one for rare win sound.

**Comment by woisalreadytaken** [comment]
probably just got really unlucky, won over 20 rounds with older premium kits that should have one working sound (pendulum, doom, persona 4 arena, binding of isaac) and couldn't get rare win to play at all

**Comment by woisalreadytaken** [comment]
this is fixed
