### ISSUE TITLE
Music Kit: DOOM may be incorrectly set as a regular music kit instead of a premium music kit

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#491]
A while ago, it was updated to be a premium kit but its name wasn't changed. Now, it feels like it's acting as a regular music kit (preround sound is not playing, can't get rare win sound to play, didn't test nuke death sound).

**Comment by FortyTwoFortyTwo** [comment]
Update title, description, and made it premium. There was also unused sound `sound/redsun/items/dbkit/164_1/challenge.mp3.bz2`, which I assume it was for challenge coin, but didn't bothered to make it functional.
