### ISSUE TITLE
Unable to download maps

### ISSUE THREAD

**Issue by Vista2003** [redsunservers/LoadoutBugTracker#494]
Even with custom content download set to allow all, maps will now not download onto my system and instead I would get disconnected from the server with the error of Missing map <MAP NAME>, disconnecting.

https://user-images.githubusercontent.com/55105920/156843470-8e2f7e03-b59f-4477-9c82-86e14c6e2b44.mp4

**Comment by FortyTwoFortyTwo** [comment]
Tohru fixed it yesterday
