### ISSUE TITLE
Loadout: map list expansion for staff members

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#496]
I suggested this a while ago but putting it here for better tracking.

The map list should show maps/gamemodes that are not in active rotation (ie can only be set by staff members) and should be labelled as such on the page. Could possibly restrict this behavior so that only people who have access to setting maps can see these (super dev + mods and above). Maybe something that only admins (and/or any people who have access to uploading maps to the servers)  can see but idk else there would be for them.

**Comment by FortyTwoFortyTwo** [comment]
Already done weeks ago
