### ISSUE TITLE
Soldier Banners won't work on PvM.

### ISSUE THREAD

**Issue by SilvaStars** [redsunservers/LoadoutBugTracker#5]
All of the soldier banners would not work during boss_flowey_v4_1, because the banners would not charge rage.

**Comment by koopa516** [comment]
I've assigned ramune to this issue

**Comment by ramunecarbonated** [comment]
This issue will be fixed with an enhancement update, should be ready in a few.

**Comment by ramunecarbonated** [comment]
Addressed in today's update @ https://steamcommunity.com/groups/redsunoverparadise#announcements/detail/1452835473494984186
