### ISSUE TITLE
Loadout: high cpu usage on loading certain pages

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#500]
Already being looked into afaik, but it seems like certain pages that need to load a lot of images (particularly steam avatars) can cause massive spikes in cpu usage according to task manager. I've also observed affected pages not always loading all the avatars needed as a result.

Known affected pages: Mod panel -> Ignores (the graph), Leaderboard

**Comment by FortyTwoFortyTwo** [comment]
Probably resolved when I improve loading from tooltips weeks ago
