### ISSUE TITLE
Loadout: Badges on own profile show 'undefined' on top of tooltip.

### ISSUE THREAD

**Issue by sascheh** [redsunservers/LoadoutBugTracker#501]
Hi, first of, great job with the site! It's very cool to see it still being maintained after so long.

As for the bug, whenever I hover over my badges on my profile, it will show an 'undefined' on top. This was a bug I also had when I used to work on the Loadout but I am not sure what exactly caused that again / whether my findings would be relevant considering the codebase very likely now actually makes sense to begin with and what not.

**Important to note, this only happens to me when visiting your own profile through https://redsun.tf/profiles/player/**, when visiting my profile with my steam id behind it, this does not happen.

![image](https://user-images.githubusercontent.com/16175575/166672391-dbb0f0a0-8871-4d9d-ada5-d1b2265fad3a.png)

**Comment by FortyTwoFortyTwo** [comment]
I boke it when redoing whole tooltips, should be fixed now in latest commit.
