### ISSUE TITLE
Loadout: Equipping an item you recently found in new items shows up as undefined and doesn't change your current equipped item.

### ISSUE THREAD

**Issue by sascheh** [redsunservers/LoadoutBugTracker#503]
hello, me again

![image](https://user-images.githubusercontent.com/16175575/167319638-0c081ff6-beed-43b1-94bb-651a70c13f44.png)

When you want to right-click equip an item you recently acquired inside `New Items`, it shows up as `undefined`. When you do equip this 'undefined' item, you do not change your current equipped item in any shape or form.

**Reproduction steps:**

1. Generate yourself an item or find it on the server.
2. Go to https://redsun.tf/profiles/inventory/
3. Right click the new item and try to equip it.

**Comment by FortyTwoFortyTwo** [comment]
Fixed
