### ISSUE TITLE
Dodgeball: rockets may target dead-but-alive players

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#504]
unfortunately I don't remember why this happens or how to replicate, [but a similar issue was recently addressed in VSH](https://github.com/redsunservers/VSH-Rewrite/commit/1ba2a2f795ffc79031174aa79554dbb3f984e11f).

**Comment by FortyTwoFortyTwo** [comment]
Used same attempt as VSH on attempting to fix this, dunno if it actually fixed for real, will have to see
