### ISSUE TITLE
Loadout: Synthwave Surfer badge not obtained despite fulfilling required conditions

### ISSUE THREAD

**Issue by Phoestre** [redsunservers/LoadoutBugTracker#506]
Sorry in advance if this is a gamemode specific bug rather than a loadout bug, but basically: During a round on dr_neonoir on the day I am writing this, I completed the Techno minigame. Despite completing this mini, however, the Synthwave Surfer badge was not awarded to my account, and still remains unrewarded. 

https://user-images.githubusercontent.com/65366850/168502099-c139c2ab-e31a-4331-9c4a-7d5a534290fe.mp4

**Comment by woisalreadytaken** [comment]
Hello, it's been a little while, but I fixed this now, thank you for reporting this bug.
Unfortunately, rewarding the badge is not something I personally can do, but I remember being there and seeing this happen, if it means anything to anyone else.
