### ISSUE TITLE
SCP: in Armstrong, ghosts can interact with living players and some map entities

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#507]
posting so it's harder to forget, and there may be some I'm missing, but the interactions from ghosts that happen in Armstrong but not Raiden I can remember are:

* can hold doors open
* can trigger... triggers
* can block melee swings (may confuse dogs)

**Comment by FortyTwoFortyTwo** [comment]
Found an obscure plugin from Armstrong that seems to be affecting this, removed it from server.
