### ISSUE TITLE
Contract not updating

### ISSUE THREAD

**Issue by lordfreezeflame** [redsunservers/LoadoutBugTracker#51]
I have the Scream Fortress wins contract and it won't update past 2/3 despite winning multiple rounds on Scream Fortress maps. I turned it in previously when it was at 2/3 because it allowed me to, now it has come back around and won't update.

**Comment by koopa516** [comment]
I have not been able to reproduce the bug and have not seen it reported by another user recently, I'm closing this issue but if I get more reports I will re-open it
