### ISSUE TITLE
Cant make a collector out of "Lookout Louis" item

### ISSUE THREAD

**Issue by MrCow1** [redsunservers/LoadoutBugTracker#510]
i tried to make a collector out of my 20 Lookout Louis but i just.. cant
it doesnt show on the crafting page.
![IJVoeh4](https://user-images.githubusercontent.com/89941274/189477544-2466e6fe-f4f7-4801-878f-cd52ef4fe1bc.png)

**Comment by Mikusch** [comment]
Fixed

**Comment by MrCow1** [comment]
> Fixed
thank you papa mikusch
