### ISSUE TITLE
Death sound replacements make Soldier's melee taunt and Scaredy-Cat taunt silent

### ISSUE THREAD

**Issue by Mikusch** [redsunservers/LoadoutBugTracker#511]
We are probably replacing the wrong file.

**Comment by Mikusch** [comment]
In that case we should still allow death voice lines to play if the player
is currently taunting

**Comment by woisalreadytaken** [comment]
Death scream voicelines can happen outside of taunting as well (only case I can remember this happening is with Painis Cupcake's rage though), so this was fixed in a different way. Thanks for reporting!
