### ISSUE TITLE
Loadout: Potentially allow for 'Heartfelt Thanks' to be equipped alongside other 'Voiceline: Thanks' sound replacements?

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#515]
as Heartfelt Thanks is only a particle effect, and not an actual sound item, i think it'd be nice if it could be equipped alongside sound replacement items under the same category, if at all possible. i'm not sure if this would result in too many changes to things or is just straight up not possible as it is now (or if it's just not a desired idea), so it's mainly just a potential QoL suggestion

**Comment by FortyTwoFortyTwo** [comment]
It's very to do it as we can reuse same equip functionality as taunt type, just a question on whenever if we want to do it or not to keep it's equip understanding simple. If were to do it, we should mention in desc that it can be equipped with other thanks item.

**Comment by FortyTwoFortyTwo** [comment]
I instead moved Heartfelt item to Misc item type instead of keeping in thanks type.
