### ISSUE TITLE
BomberMod using the in game "Sound Volume" slider for music instead of the "Music Volume" slider.

### ISSUE THREAD

**Issue by windflow5** [redsunservers/LoadoutBugTracker#516]
I've noticed this problem for about a month now but didn't know where to submit it.
I am currently aware that this happens on the following maps.
-Temple of Ninja Masters
-bm_mario_v3
-bm_mandrillmaze

**Comment by windflow5** [comment]
Issue is also present in the Smash Fortress gamemode.

**Comment by windflow5** [comment]
Issue is also present on Versus Saxton Hale: Rewrite with the Glitched Robot and Merasmus bosses.
(Most likely a present on all bosses with a theme/song.)

**Comment by woisalreadytaken** [comment]
Was addressed for BomberMod and Smash Fortress a few days ago, and may be addressed for VSH soon, hopefully. Thanks for the report.
Map-specific music most likely will not be changed. I don't even know if that's possible to be changed through Stripper, but even if it is, I don't think anyone is going to look into each individual map that is missing music volume compatibility.

I'll leave this open for now, anyone is free to point out other inconsistencies related to music volume.
