### ISSUE TITLE
STT/Tank Race: bugged weapons for giants

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#52]
The weapons given to giants are (in most cases) bugged in some way. Some examples are: all miniguns and the widowmaker don't do any damage at all, the GRU, which drains roughly 2/3rds of your health almost instantly, and all demo primaries have a bugged clip size (from my experience as a rapid fire demo, I had 62 grenades in the clipped when I first spawned, but when I reloaded it went down to 5 like normal, something similar happened to somebody who was sir nukesalot).

I haven't noticed any issues with weapons for non-giants.

**Comment by Benoist3012** [comment]
that sounds like an error within the code execution, because I fixed that issue last month, I'll check this later

**Comment by Benoist3012** [comment]
As I thought issue fixed long ago, that bug isn't occurring anymore
