### ISSUE TITLE
Forums: Unable to login with or associate connected accounts on mobile

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/LoadoutBugTracker#521]
for some reason, any attempts to login or connect a new associated account on a mobile web browser results in the error `There is no valid connected account request available. Please try again.` appearing and nothing actually happening.

this error does not seem to occur on desktop, and even after logging in and out in an attempt to refresh the session doesn't fix it. this occurs with both Discord and Steam logins.

**Comment by HeatRiser** [comment]
We disallow discord oauth for logins, only account linking so I am unsure why or how you're attempting to use it to login.

I'm unable to replicate the issue either on a mobile device. Can you show pictures of the issue?

**Comment by infinitephantasm** [comment]
![Screenshot_20230604-211352](https://github.com/redsunservers/LoadoutBugTracker/assets/23409983/883bcc41-51f7-426e-9779-668f6dea92df)

screenshot of the error in question.

> We disallow discord oauth for logins, only account linking so I am unsure why or how you're attempting to use it to login.

this was mostly in reference to the association process -- obviously not being used for login, but this issue does apply to steam logins as well

**Comment by HeatRiser** [comment]
I can't rule out earlier service degradation with discord's services as a possible cause but it is possible.
I am not seeing anything within the site's logs that would suggest anything otherwise yet.

**Comment by infinitephantasm** [comment]
closing this due to it being caused by some strange issue regarding AdGuard on my phone blocking this from working on Wi-Fi, but not on mobile data??

i don't know it's dumb
