### ISSUE TITLE
Unable to save Surf and Deathrun preferences on multiple servers.

### ISSUE THREAD

**Issue by Darkita162** [redsunservers/LoadoutBugTracker#522]
As the title suggests, the Redsun servers (all three of them) have trouble syncing up with each other for preferences on Surf and Deathrun.

I've noticed for a while now that if you use /trail on one server, let's say Raiden, and you then go to Armstrong if it has a surf or deathrun map active or just Ocelot in general. Those will not be synced. The weird part is, if you do /trail or /speed or whatever on another server, then on Raiden/Ocelot, they revert back to their default values. Meaning I can see my trail in first person again.

It seems that whenever these commands are run through on one server, it doesn't send that information to the others, or it is, just not correctly. I think it's noticing something is different, but it doesn't know what and to avoid it shitting itself, it just reverts back to default.

**Comment by Mikusch** [comment]
That's normal, client preferences are stored per-server. Not a bug.
VSH does some extra work to sync it but it's not really worth it for the other modes.
