### ISSUE TITLE
Loadout: Don't mute dodgeball kits when "Play Jukebox Music" is disabled

### ISSUE THREAD

**Issue by pokemonpasta** [redsunservers/LoadoutBugTracker#527]
Unless this has been fixed and I missed it, currently when you disable "Play Jukebox Music" in preferences it also disables dodgeball kit music. When I brought this up in the discord a while back wo said it's because that's how earplugs worked.

For me personally I want to mute jukebox and not dodgeball, so I suggest either just not muting it when you mute jukebox music or making it a separate toggle entirely.

**Comment by woisalreadytaken** [comment]
Added a separate toggle for music kits
