### ISSUE TITLE
STT(?)/Tank Race: contracts are inconsistent

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#53]
Several people have reported that many STT related contracts are very glitchy in Tank Race, as in they only count progress some of the time. As far as I know, there is no pattern to when they actually count. Known contracts that behave in this way are sentry buster kills and giant MVP.

I assume that they work fine in STT, but if they were intended to only work in STT maybe it should be clearer that those contracts won't count in Tank Race.

**Comment by ShavedFanatic** [comment]
It didn't count for me. I was on pl_cashworks_final1 and I was Giant MVP for both a Giant Sniper and a Giant Rapid Fire Demoman and it didn't count for either.

**Comment by ramunecarbonated** [comment]
@koopa516 any updates on this?

**Comment by ShavedFanatic** [comment]
I got a Sentry Buster kill on pl_badwater_tilt and it didn't count towards my contract.

**Comment by ramunecarbonated** [comment]
As of still, @koopa516 can't find the cause of this. Apologies for the quite huge inconvenience.

**Comment by ramunecarbonated** [comment]
gonna assume this will be left untouched
