### ISSUE TITLE
SZF: Server sometimes crashes on round end

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#54]
I wish I had more information about this to narrow the issue down, but SZF just randomly crashes the server when a round ends.

**Comment by ramunecarbonated** [comment]
As it started happened recently, I assume, this could be because I brutally set the max health of all classes on spawn which has proven to not work at all: so I will get rid of that change.

Along with that I will also be cleaning up the code a small bit, hope it helps.

**Comment by ramunecarbonated** [comment]
Addressed, thanks.
