### ISSUE TITLE
The Flower Power badge isn't being given away when players beat boss_flowey

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#55]
The badge isn't limited, so I assume this isn't intended behaviour. I realized that I hadn't seen any badges being given when players beat the map through this event, so I've checked some newer accounts right after they beat it (and double checked a few minutes later to make sure the profiles refreshed properly) and they indeed never got it.

**Comment by ramunecarbonated** [comment]
Addressed, thanks.
