### ISSUE TITLE
map not set up correctly in rotation

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#56]
I have no idea if I should be using the tracker to report specific map issues but here we go:

Yesterday, during ebbi's event (where players could pick the next map), I picked team_trial_cooperation_inc, and he was able to set it. However, checking /nextmap did not show that the set map had been changed, meaning it was impossible for the map to be played. I'm reporting this because I thought that it was really suspicious that the map never appeared normally (in team battles), and I knew it was done (according to the mapmaker), so there was no reason for it to not be in the rotation; as far as I'm aware anyways.

I really liked this map so I hope it gets fixed :(

**Comment by koopa516** [comment]
fixing

**Comment by koopa516** [comment]
fixed
