### ISSUE TITLE
Death's Locksmith badge image is missing

### ISSUE THREAD

**Issue by ramunecarbonated** [redsunservers/LoadoutBugTracker#57]
The Death's Locksmith image is missing from the CDN, resulting in a 404 / generic fallback image.

This error applies to:

- [User card](https://pomf.ramune.me/files/jbzarrj.png)
- [Player profile](https://pomf.ramune.me/files/cussowp.png)
- Occurs on all players who have this badge.

(i dont have the source image so i cant add it myself)

**Comment by itVictor** [comment]
same issue with this badge: 

<img width="322" alt="screen shot 2017-11-19 at 11 19 32 pm" src="https://user-images.githubusercontent.com/20176719/33003415-30728fdc-cd80-11e7-955a-44cf0aed1cc6.png">

**Comment by ramunecarbonated** [comment]
@itVictor make a seperate issue for that and I will address it today

**Comment by ramunecarbonated** [comment]
![sos2_locksmith](https://user-images.githubusercontent.com/16175575/33039725-361fb4aa-ce39-11e7-945e-b8dd89993d2b.png)

beauty
