### ISSUE TITLE
sweet victory MAX badge has missing image

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#58]
made as separate issue by request of darth

<img width="322" alt="screen shot 2017-11-19 at 11 19 32 pm" src="https://user-images.githubusercontent.com/20176719/33003860-1027d2e8-cd83-11e7-9800-d55ae683d5a7.png">

**Comment by ramunecarbonated** [comment]
apparantly the image completely dissapeared from the website so I will have to make a new one when I am home.

**Comment by ramunecarbonated** [comment]
Addressed and uploaded max images for several other type of achievements along with a surf badge update.
