### ISSUE TITLE
The Crusader's Call's sound file cannot be played in TF2

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#6]
The sound file was sampled at 32000Hz, so whenever it tries to be played (even through the 'play' command), the console displays this error:

> *** Invalid sample rate (32000) for sound 'redsun\items\banner\433.mp3'.

I remade the sound and sampled it to 44100Hz as a fix (bitrate remains at 80kbps), so TF2 supports it. Otherwise you could ask Dosh to fix it as it's his item. Or fix it yourselves, that's fine too.

[https://cdn.discordapp.com/attachments/332809334339665930/375533499869954048/433_fix.mp3](url)

**Comment by ramunecarbonated** [comment]
I have assigned Frosty or Tohru to upload this asap I currently cannot upload files until friday night.

**Comment by ramunecarbonated** [comment]
Issue was adderessed but assignees forgot to close.
