### ISSUE TITLE
body count MAX also has missing image

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#60]
![bodycount2](https://user-images.githubusercontent.com/33488710/33091248-7075599c-ceee-11e7-9842-05d33e450273.jpg)

**Comment by ramunecarbonated** [comment]
that is not good, sorry about that, i will whip up something amazing!

**Comment by ramunecarbonated** [comment]
![killsmade_max](https://user-images.githubusercontent.com/16175575/33094066-197201a2-ceff-11e7-92e4-36278e2cc994.png)

Done.
