### ISSUE TITLE
Dodgeball changes from the November 17th update were not applied on Raiden

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#61]
The jetpack cooldown is still 120 seconds and the Thriller and Pendulum DB kits still don't work completely (though the Pendulum DB kit doesn't work in both servers still, but that's another issue). Only applies to Raiden.

**Comment by ramunecarbonated** [comment]
plugin didnt compile because I did some modifications to the weapon generation system so it was never updated to reflect the changes

**Comment by ramunecarbonated** [comment]
fixed, don't know much about the pendulum kits though since Frosty did that fix.
