### ISSUE TITLE
Music Kit: The Binding of Isaac doesn't play all sounds it should

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#63]
- The preround sound doesn't play when a round starts
- When dying to a nuke, it just plays the regular death sound (this might be an issue with all premium kits, needs further testing)
- The "rare win" sound might never play, as I hear the winrare sound from other premium kits every now and then, but never had the chance to hear Isaac's (and Isaac kits happen to be more common than other premium kits)

Kinda feels like it's a regular kit rather than a premium one. Console shows no errors and this happens in both servers.

**Comment by ramunecarbonated** [comment]
Took a small look: the Isaac kit is apparantly not even defined as a premium kit.
@koopa516 cc to take note of this when adding items next time

**Comment by ramunecarbonated** [comment]
fix coming up later, thanks for reporting
