### ISSUE TITLE
Music Kit: Pendulum might not be available in Strange quality

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#64]
I've seen tons of strange premium kits being unboxed, but I've never seen a strange Pendulum kit. I've even just checked Frosty's Red Sun profile, saw tons of the other three kits available in the same crate in strange quality, assuming he mass unboxed strange items (testing stuff, I guess), but no Pendulum.

Maybe this was just fixed with issue #63, or the kit isn't supposed to be unboxed in strange quality at all. If that's the case, then sorry.

**Comment by FortyTwoFortyTwo** [comment]
Another note is the amount of Strange Isaac kit I've seen unboxed is a lot, which makes me think it been listed twice, where one of them should've been Pendulum. Even Frosty have a lot of strange Isaac kit in his inv.

**Comment by koopa516** [comment]
Fixed
