### ISSUE TITLE
PropHunt: "The One and Only" badge awarding the wrong person on round end.

### ISSUE THREAD

**Issue by JoeyLoser** [redsunservers/LoadoutBugTracker#66]
Two cases back to back on ph_buckethunt_event_c1 on Armstrong. Badge being awarded to second last alive instead of the respected person who was actually alive last. First case was Blotz being last and 42 being the second person last alive that round, However 42 was awarded the badge instead. Second case was me(Loser) and Drandor, same events happened where Drandor was awarded the badge when I was last alive in the round.

**Comment by ramunecarbonated** [comment]
should be fixed now, thanks for reporting.
