### ISSUE TITLE
Contract: Can't complete "Your Best Friend Contract"

### ISSUE THREAD

**Issue by justingg4711** [redsunservers/LoadoutBugTracker#67]
The contract tells me to: "Defeat Flowey on boss_flowey once" I've done it twice, both time i've seen no notification in the chat that i've completed the contract and on the contract page itself it tells me that i have beaten Flowey 2/1 times, and it still isn't completed.

**Comment by ramunecarbonated** [comment]
tried /turnin?

**Comment by justingg4711** [comment]
I haven't. (Didnt know that was a command, so heh.) Well, i've tried it now and it worked. So thanks for telling me!

**Comment by ramunecarbonated** [comment]
we used to have it auto-complete but it caused our servers to crash for some reason, so that is why.
