### ISSUE TITLE
BP found items do not play their sounds

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#7]
(as of ~11 pm est last night on Armstrong)

Bp found items do not play their sounds when receiving random bp drops, the default sounds are played instead.

I did notice a few side notes:

1. In boss_flowey, I heard the correct sounds after I got the bp for winning, but the sound did not play until the very start of the next round (did not change maps)
2. Somebody reported that they heard their bp drop item sounds when they died, can not independently reproduce at this time (this was a different map btw, not flowey)

**Comment by ramunecarbonated** [comment]
issue has been addressed in the most recent server build, thanks for reporting
