### ISSUE TITLE
Unique Pendulum Premium Kit plays no sound on round win

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#71]
May also extend to strange kit

**Comment by woisalreadytaken** [comment]
Adding to this: the preround sound for the Pendulum kit works, but no other sounds do. Console shows no errors

**Comment by ramunecarbonated** [comment]
fuck the pendulum kit tbh

**Comment by ramunecarbonated** [comment]
oh nice the fix was actually never uploaded in the first place, try this i guess
