### ISSUE TITLE
szf: zombies still getting health penalties 

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#72]
(continuation of #8)

zombies are still getting health penalties with the affected weapons, though I believe the effects have changed since the last update

sandman: gradual decrease to 110 (always equipped due to plugin)
kunai: spawns at 70
big earner: spawns at 100
GRU: drains to 280
Eviction Notice: drains to 100(?) (stats are unchanged compared to vanilla)

should also note that the health drain with gru/eviction makes the overheal relatively useless because it drains so fast

**Comment by ramunecarbonated** [comment]
This is probably due to the fact that these weapons are no longer spawned thru the TF2Items extension, the fix required these weapons to spawn through that extension.
