### ISSUE TITLE
phrase being blocked by the chat filter at the wrong time

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#73]
(credit to Ebbi and 42 for finding the bug)

We noticed that when 42 said "ph_trainyard" it was being blocked by the chat filter. Further investigation has led to use figuring out that the "nya" was causing it to be blocked by the chat filter, however it's a phrase that should only being blocked when ROBOTSUN is active, even though it definitely wasn't at the time it was said. Specfically, "It's every phrase under 'ovvo meme, stale and overused.  Good riddance'" that is being triggered all the time, whether ROBOTSUN is active or not.

On a similar note, we noticed that having the phrase and a mention in the same message resulted in the receiver of the mention getting the sound, but not seeing the message because it was being filtered. For example,  if 42 said  "@Victor owo" I would hear the mention but not see the message, and 42 would be the only one in the server to see it since he sent it.

**Comment by ramunecarbonated** [comment]
will be addressed

**Comment by koopa516** [comment]
fixed

**Comment by ramunecarbonated** [comment]
if you have been given an automated ban as of recent due to this oversight please tell us asap and we will remove it, even if it already expired: since it is an unjust ban you have on record.
