### ISSUE TITLE
weapons for giants are still bugged (STT/Tank Race)

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#76]
(continuation of #52 )

once again, weapons for giants are still bugged (same problems as mentioned previously)

I'd also like to point out that it was claimed it was fixed "over a month ago" which isn't true because it was definitely happening the day before the original issue was made and is still happening today, so either that fix wasn't uploaded or didn't work.

**Comment by Benoist3012** [comment]
You are rigth it seems that the fix i have made didn't get through, I'll
fix this later today.

**Comment by Benoist3012** [comment]
Fixed thanks for the report!
