### ISSUE TITLE
silence coins cannot be used at all

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#77]
silence coins cannot be used on any map, I've tested this on several maps where I know that there was no map music and jukebox coins worked fine, but flipping a silence coin always gives "cannot use this coin right now"

**Comment by ramunecarbonated** [comment]
prolly because of the new convar for it that has been added since.. don't know too much about its intended usage.

**Comment by ramunecarbonated** [comment]
config wasnt resetting that convar
