### ISSUE TITLE
SZF: items that decrease max health applies to zombies

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#8]
Items that normally limit/drain the max health of the player applies to zombies, this should not be the case.

Weapons affected:
Sandman, Kunai, Big Earner, Gloves of Running Urgently, Eviction Notice

First three weapons cut the player's max health, but the health gained on rage is unaffected (though the max HP in overheal is lowered because of the cut).

The GRU drains your health on spawn to 280 and stays there. Eating a lunchbox item will give the player health, but will drain again to 280 afterwards. The only way to rage when the GRU is enabled is to activate it while eating a lunchbox item at the same time. Again, max overheal is affected, and the player will lose the overheal faster.

~~Interestingly, the Eviction Notice (which should also drain health) appears to be completely unaffected.~~

**EDIT**: Eviction Notice is also affected, it drains the player's health to 100 and and stays there. If you go under 100 hp it will regain health as normal until it reaches 100.
I should also note that rage can be used at any point when the health is draining.

Testing the health drain on Mistral has proven to be extremely inconsistent with regards to whether it actually drains health, but the other weapons that only cut max health are consistent. Regardless of the Mistral testing, all affected weapons are consistently bugged on Raiden/Armstrong.

**Comment by Benoist3012** [comment]
Noted, I'll be fixing this soon.

**Comment by Benoist3012** [comment]
These health penalty attribs are now stripped from the weps.
