### ISSUE TITLE
SZF: Reserve Shooter has no attributes

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#80]
The Reserve Shooter has no attributes attached to it, making it functionally identical to a stock shotgun. Seen in Armstrong and I remember this happening in all servers before the weapon became unable to be picked up (thanks for the fix, by the way!)

**Comment by ramunecarbonated** [comment]
items made through the tf2items fallback for the weapon generation code (multi-class non-stock items were mostly affected by this) were not made with their attributes preserved, so they should be now.
