### ISSUE TITLE
GunGame: Shotgun-based secondaries don't have attributes

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#81]
This applies to the Reserve Shooter, Panic Attack and Family Business. The Frontier Justice is fine, though. I've seen this happen in Raiden and Armstrong.

**Comment by ramunecarbonated** [comment]
items made through the tf2items fallback for the weapon generation code (multi-class non-stock items were mostly affected by this) were not made with their attributes preserved, so they should be now.

**Comment by itVictor** [comment]
@ramunecarbonated bumping as this issue is happening again for the panic attack only, the other shotgun-based weapons seem to have the correct attributes

**Comment by woisalreadytaken** [comment]
a bit late here, but the Panic Attack is working as intended in GunGame right now (at least in Raiden)

![image](https://user-images.githubusercontent.com/33163183/34463372-e579d562-ee40-11e7-85da-a2f4405bbfa5.png)

**Comment by ramunecarbonated** [comment]
guess this was resolved already.
