### ISSUE TITLE
SZF: The interaction with flare guns ( all variants ) and reserve shooter

### ISSUE THREAD

**Issue by Datjazzi** [redsunservers/LoadoutBugTracker#82]
There is weird bug with Flares and reserve shooter.

If you pickup a reserve shooter while holding flare gun (any) the flare gun you hold goes to the table and you get reserve shooter as normally, but if you try to switch back to last weapon you get your flare gun back but it discards the whole reserve shooter away.  may work just by selecting your secondary again.

i had one round where i could select between reserve shooter and normal flare gun, but was unable to make it happen again mostly due to map limit and weapon rng. When this bug happened the reserve shooter was in primary weapon slot and flare gun was in secondary. ( i was pressing 1 for reserve and 2 for flare gun. )

I hope this info is sufficient enough to understand and find the problem

-Heroin Hero

**Comment by ramunecarbonated** [comment]
the non-tf2items and the tf2items-fallback based weapon creation code are not going well together, it seems

ill fix that before i leave for my booze and food tonight
