### ISSUE TITLE
Freeze Tag: arena rounds doesn't end on all team players killed

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#84]
In freeze tag arena_powerhouse, after all blu players killed round does not end. Guessing it due to server thinking it a koth round. Happened in Raiden

**Comment by ramunecarbonated** [comment]
I'm off to my booze and food but I'll take a peek at this this week.

**Comment by ramunecarbonated** [comment]
> "arena_"
	{
		(...)
		"eliminations"     "1"
(...)
	}

Seems to work fine config-wise 🤔

**Comment by koopa516** [comment]
>when you get assigned to an issue but dont even have access to the repo
