### ISSUE TITLE
Rewards for killing Merasmus are only handed out once until the server restarts

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#85]
People have been saying rewards are supposed to be given once per map (as long as there's Merasmus to kill), but after killing him once the server just seems to forget about it until it restarts. Benoist was able to make rewards be given multiple times without restarting the server but he said he was "cheating the system", maybe reloading a plugin?
Seen in Raiden today and Armstrong yesterday.

**Comment by Benoist3012** [comment]
Event is over but issue is fixed. Thanks for report!
