### ISSUE TITLE
Merasmus is not forced to level 8, as he should

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#86]
The pop-up that shows up when Merasmus spawns will always say that he's level 8, but that's just a visual thing. He will behave as if he was level 1 (or higher if he was already beaten before). Once he dies/leaves, the pop up will show his actual level instead (or not if he's level 1).

**Comment by koopa516** [comment]
I deployed a fix for this, however to be honest I'm not sure if it's working. If it is, I will close the issue

**Comment by woisalreadytaken** [comment]
Just checked, Merasmus' level still starts from 1 but the spawn pop-up doesn't lie about it being 8 anymore, like as if nothing was done to him

**Comment by Benoist3012** [comment]
Despite that the event ended I'll fix this, and also implement custom lvl support for monoculus.
