### ISSUE TITLE
did contracts but they did not give me my stuff (and did one twice with bug)

### ISSUE THREAD

**Issue by Buckaduck** [redsunservers/LoadoutBugTracker#88]
i was doing the ZTF contract to kill 30 people and i was the last survivor and i died with the contract done and then i turned it in and it didn't give me any of my stuff even though it counted as "finished" then something stranger happen the kills from the ZTF contract carried over to the next contract witch was demos eye(i do not know its name) witch i turn it in.. it say i finished it and it said it gave me my items but it didn't so i refresh it to find out it was there AGAIN with kills too so i return it in still no items AND it didn't count to the finished missions (ZTF counted) but after this everything in the contract list looks normal.what i am guessing that cause this to happen is due to the fact i have 2 of the Halloween contract items active at once. pictures showing the buging are down below
![20171204165334_1](https://user-images.githubusercontent.com/34257786/33586522-5c28f980-d92f-11e7-8cf2-a4fde5a8405e.jpg)
![20171204165329_1](https://user-images.githubusercontent.com/34257786/33586528-60def100-d92f-11e7-8dcc-96058808e427.jpg)
![20171204165337_1](https://user-images.githubusercontent.com/34257786/33586583-a415d48e-d92f-11e7-9b55-06519a273ff3.jpg)

IF you want to see items request as a comment
EDIT:i do not know how to put label so yeah..

**Comment by woisalreadytaken** [comment]
adding to this: players won't receive any Red Sun items from the servers (random drops, gift drops, contracts, etc.), but the "player has found" message will still show up

**Comment by Buckaduck** [comment]
thx woi

**Comment by ramunecarbonated** [comment]
It doesn't matter how many Contract Passes you own.

**Comment by koopa516** [comment]
fixed
