### ISSUE TITLE
Amplified shot for grenade launcher no longer proc-ing

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#89]
No amplified grenade launcher pills were being created against B1 despite landing 5+ shots. This occurred on Armstrong.

I'm also going to assume the same problem occurs with rockets because I did not see crit rockets hitting B1 outside of Kritzkrieg charge.

**Comment by ramunecarbonated** [comment]
Amplified shots only have an audio effect, no visual effect whatsoever.

**Comment by bwauts** [comment]
There is no loud audio effect when fighting B1 when firing 5+ shots.

It used to work when you fired 5 pills inside Flowey's TV, but that also doesn't seem to happen anymore.

**Comment by ramunecarbonated** [comment]
Will investigate, but this will prolly be quite a tough one since detecting a hit seems to only happrn consistently with hitscan. (We rely on entity inputs for that.)

**Comment by ramunecarbonated** [comment]
added a snippet to get the owner of the projectile in case it doesnt direct a client on the spot, cant promise if it works tho or not
