### ISSUE TITLE
Premium Dodgeball Kit: The Binding of Isaac(?) has incorrect file paths on download

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#9]
A nameless folder shows up where the item ID should be when a premium DB Kit tries to be downloaded, like so:

![hl2_2017-11-03_12-17-57](https://user-images.githubusercontent.com/33163183/32379756-8df3b5a2-c095-11e7-8426-f1772c075034.png)

related issue: DB Kits 164_1 and 259_1 are cached but also can't be downloaded

**Comment by ramunecarbonated** [comment]
I'll fix this before I leave for my party tonight, bit occupied with in the noon so expect a fix in ~2-3 hours.

**Comment by ramunecarbonated** [comment]
Addressed in today's server update. Thanks for reporting!
https://steamcommunity.com/groups/redsunoverparadise#announcements/detail/1452835735000425987
