### ISSUE TITLE
all item drops don't actually give you the item(s)

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#90]
this affects contract rewards, gifts, random item drops, and merasmus drops

you will see the text for getting the item in chat like normal, but the item(s) won't actually be in your inventory. I should note that the other aspects of drops like contract progress and the gift counter in profiles work as normal, it's just the actual item generation that's borked.

**Comment by ramunecarbonated** [comment]
Suspecting buildbot bug but will look regardless

**Comment by ramunecarbonated** [comment]
lol im retarded
