### ISSUE TITLE
SZF: No weapon is given when trying to pick up a Reserve Shooter

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#92]
As seen earlier in issue #79 (and also #82) but it's not quite the same thing, now you're able to "pick the weapon up", but you will not get a secondary weapon. If you already had a secondary weapon, "picking the reserve shooter up" will strip you off of it. Seen in Raiden and Armstrong.

**Comment by itVictor** [comment]
similar issue happens in gungame with the family business: you end up as a civilian so it makes it impossible to complete a round since nobody can progress beyond that level

**Comment by woisalreadytaken** [comment]
^ since we're already here, that also happens with the panic attack and the reserve shooter
(I was going to make a separate issue about that)

**Comment by ramunecarbonated** [comment]
Will investigate, but I do expect a buildbot issue for issue #91 which came immediately with this issue post.

**Comment by ramunecarbonated** [comment]
Like-wise for #89 and #90.

**Comment by ramunecarbonated** [comment]
fix for GunGame up, unsure if fix retroactively applies to Super Zombie Fortress, if it doesn't make a new issue
