### ISSUE TITLE
missing images on loadout

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#94]
<img width="466" alt="screen shot 2017-12-09 at 4 39 23 pm" src="https://user-images.githubusercontent.com/20176719/33800103-9233df12-dcff-11e7-9461-f1905e095c41.png">
<img width="312" alt="screen shot 2017-12-09 at 4 39 13 pm" src="https://user-images.githubusercontent.com/20176719/33800104-9243de62-dcff-11e7-87f2-551bbb816bec.png">

**Comment by EgocentricPoliceDick** [comment]
ctrl+f5, your client didnt download the images from cdn

**Comment by itVictor** [comment]
@EgocentricPoliceDick several other people are also seeing it so I don't think it's an issue on my end. Also it seems to be happening with any common series crate.

**Comment by ramunecarbonated** [comment]
re-opening since there are actually images missing. @koopa516 will take care of these.

**Comment by EgocentricPoliceDick** [comment]
images are up
