### ISSUE TITLE
special/limited badge in featured badge list inconsistencies with border

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#95]
Not sure if this is intentional, but it seems to be different for other people.

(mine)
<img width="632" alt="screen shot 2017-12-09 at 4 40 38 pm" src="https://user-images.githubusercontent.com/20176719/33800116-d08ec9ca-dcff-11e7-8adc-b7871c4f7522.png">

(ebbi)
![t](https://user-images.githubusercontent.com/20176719/33800126-05d742d8-dd00-11e7-9f07-9ec0430b4142.png)

**Comment by ramunecarbonated** [comment]
client-specific fixes is not something i will be looking into, this is a browser issue as for the glow we use keyframes and box-shadow. 

https://caniuse.com/#feat=css-animation
https://caniuse.com/#feat=css-boxshadow
