### ISSUE TITLE
coin effect math on donator page possibly displaying wrong

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#98]
I'm level 5, so by the math shown it should be 12.5% instead of 10%, unless I'm missing something. Pretty sure that the % is rounded down, but this seems to be a bit much.

<img width="326" alt="screen shot 2017-12-09 at 4 46 56 pm" src="https://user-images.githubusercontent.com/20176719/33800179-c0e13782-dd00-11e7-819b-7648aa4eec8e.png">

**Comment by ramunecarbonated** [comment]
Already addressed on our side, I need to upload it which I will do with some other fixes in a short moment.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
